In [1]:
import os
import numpy as np
import pandas as pd
from glob import glob
from tqdm import tqdm

In [2]:
# load new classification
df = pd.read_table("/lustre/bio_running/GTEx_Long_Project/metadata/GTEx.chrM_info_extended.7S.reverse.reads.classified.v2.tsv.new_classification.tsv")
df

,Chr,ChrStart,ChrEnd,read_id,MAPQ,strand,read_length,alignment_length,reference_length,polyA_length,sample,overlapping_gene_ids,overlapping_gene_names,n_overlapping_gene_ids,chrM_primary_class,new_class
0,chrM,189,397,8219ade2-143f-4d8b-b15a-fc02f6430ea9,60,-,216.0,205,208,32,GTA1,7S,7S,1,complete_gene,fully_cleaved
1,chrM,189,396,4ed13e94-9fc0-4635-831b-d1ac2708c6ba,60,-,239.0,211,207,29,GTA1,7S,7S,1,complete_gene,fully_cleaved
2,chrM,189,397,0ae625d5-6c3e-4f83-ac35-9dc6731d3b9b,60,-,210.0,207,208,24,GTA1,7S,7S,1,complete_gene,fully_cleaved
3,chrM,189,397,cab401c4-514b-4b1f-8691-c46bb744c605,60,-,213.0,208,208,29,GTA1,7S,7S,1,complete_gene,fully_cleaved
4,chrM,189,398,66097d6c-e560-4a0e-913c-4fad5cd0c7bc,60,-,242.0,210,209,59,GTA1,7S,7S,1,complete_gene,fully_cleaved
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
789846,chrM,16388,16569,4f8cec63-475c-40f8-a615-a3e1796952d8,60,-,359.0,184,181,11,GTH9,NaN,NaN,0,non_coding_region,partially_cleaved_short
789847,chrM,16389,16569,5fe5947e-4bee-4f72-aa38-56b6b91b23ea,60,-,254.0,180,180,15,GTH9,NaN,NaN,0,non_coding_region,partially_cleaved_short
789848,chrM,16393,16569,1300a2cc-7fea-47ef-ab23-b5771b7e30fb,60,-,239.0,174,176,0,GTH9,NaN,NaN,0,non_coding_region,partially_cleaved_short
789849,chrM,16395,16564,46ce9b31-c444-4caa-8573-aece049e5431,60,-,182.0,169,169,4,GTH9,NaN,NaN,0,non_coding_region,partially_cleaved_short
789850,chrM,16405,16569,f166ea81-0dec-4d42-b67d-81007c196b80,60,-,320.0,165,164,10,GTH9,NaN,NaN,0,non_coding_region,partially_cleaved_short

In [3]:
df.new_class.value_counts()

partially_cleaved_short    369133
partially_cleaved_long     367166
fully_cleaved               53552
Name: new_class, dtype: int64

In [4]:
df[["sample", "new_class"]].value_counts()

sample  new_class
GTA9    partially_cleaved_long     62147
        partially_cleaved_short    33341
GTC9    partially_cleaved_long     26662
GTG5    partially_cleaved_short    20857
GTH5    partially_cleaved_short    19300
                                   ...
GTB1    partially_cleaved_long        39
GTF9    fully_cleaved                 37
GTD1    fully_cleaved                 27
GTF7    fully_cleaved                 25
GTB1    fully_cleaved                  4
Length: 219, dtype: int64

In [5]:
basepath = "/lustre/bio_running/GTEx_Long_Project/analysis"
samples = df["sample"].value_counts().index.to_list()

failed = []
for _,sample in enumerate(samples):
    print()
    print("\n######################################################################################################")
    print("######################################################################################################")
    print("######################################################################################################")
    print(sample, f"Total Processed samples: {_}/{len(samples)}")
    df_sample = df[df["sample"] == sample].copy()
    unique_reads = df_sample.read_id.value_counts().index.tolist()
    number_of_unique_reads = len(unique_reads)
    print("Shape of df-reads for current sample:", df_sample.shape)
    print("Unique number of reads:", number_of_unique_reads)
    display(df_sample.head(2))
    print("CHECKING number of reads:")
    if not df_sample.shape[0] == number_of_unique_reads:
        print("!!!!!!!!ERROR!!!!!!!!!!! ")
        break
    mitoBAM_fp = os.path.join(basepath, sample, f"{sample}.genome.chrM.reverse.bam")
    print("Starting mito-BAM filepath:", mitoBAM_fp)
    for new_class in ["fully_cleaved", "partially_cleaved_short", "partially_cleaved_long"]:
        print(f"\n#####\nElaborating class: {new_class}")
        df_sample_current_class = df_sample.query(f"new_class == '{new_class}'")
        if df_sample_current_class.empty:
            print("!!! Problem with current class !!! Empty reads-list for this sample/class combination.")
            failed.append(f"{sample}|{new_class}")
            continue
        display(df_sample_current_class[["sample", "new_class"]].value_counts())
        reads_list_current_class = df_sample_current_class.read_id
        print(df_sample_current_class.shape)
        print(f"Number of reads for current class: {len(reads_list_current_class)}")
        out_mitoBAM_fp = mitoBAM_fp + f".{new_class}.bam"
        out_mitoBAM_readslist_fp = out_mitoBAM_fp + ".readslist"
        out_mitoBAM_depth_fp = out_mitoBAM_fp + ".depth.txt"
        print(f"- output mitoBAM for current class: {out_mitoBAM_fp}")
        print(f"- output mitoBAM readslist for current class: {out_mitoBAM_readslist_fp}")
        print(f"- output mitoBAM depth file for current class: {out_mitoBAM_depth_fp}")
        # write readslist on disk
        with open(out_mitoBAM_readslist_fp, "w") as out_mitoBAM_readslist:
            for read in reads_list_current_class:
                out_mitoBAM_readslist.write(read + "\n")
        os.system(f"cat {out_mitoBAM_readslist_fp} | wc -l")
        # create sub-mitoBAM file, indexing it, creating corresponding depth file
        os.system(f"samtools view -F 2308 -@ 24 -b -N {out_mitoBAM_readslist_fp} {mitoBAM_fp} > {out_mitoBAM_fp}")
        os.system(f"samtools index -@ 24 {out_mitoBAM_fp}")
        os.system(f"samtools depth -a -@ 24 {out_mitoBAM_fp} > {out_mitoBAM_depth_fp}")
        os.system(f"samtools view -@ 24 {out_mitoBAM_fp} | cut -f 2,3 | sort | uniq -c | sort -nr")
        os.system(f"wc -l {out_mitoBAM_depth_fp}")

print("\n\n\nComputation Finised!")
print(f"Total Processed samples: {_+1}/{len(samples)}")
print(f"Failed sample|new_class combinations: {len(failed)}")

######################################################################################################
######################################################################################################
######################################################################################################
GTA9 Total Processed samples: 0/73
Shape of df-reads for current sample: (99127, 16)
Unique number of reads: 99127

,Chr,ChrStart,ChrEnd,read_id,MAPQ,strand,read_length,alignment_length,reference_length,polyA_length,sample,overlapping_gene_ids,overlapping_gene_names,n_overlapping_gene_ids,chrM_primary_class,new_class
4059,chrM,189,395,ab175762-42da-4f10-8966-6032a392965c,60,-,225.0,206,206,62,GTA9,7S,7S,1,complete_gene,fully_cleaved
4060,chrM,189,396,a265af16-4b83-4fdc-bdb9-cd3b65328196,60,-,233.0,208,207,10,GTA9,7S,7S,1,complete_gene,fully_cleaved

CHECKING number of reads:
Starting mito-BAM filepath: /lustre/bio_running/GTEx_Long_Project/analysis/GTA9/GTA9.genome.chrM.reverse.bam

#####
Elaborating class: fully_cleaved

sample  new_class
GTA9    fully_cleaved    3639
dtype: int64

(3639, 16)
Number of reads for current class: 3639
- output mitoBAM for current class: /lustre/bio_running/GTEx_Long_Project/analysis/GTA9/GTA9.genome.chrM.reverse.bam.fully_cleaved.bam
- output mitoBAM readslist for current class: /lustre/bio_running/GTEx_Long_Project/analysis/GTA9/GTA9.genome.chrM.reverse.bam.fully_cleaved.bam.readslist
- output mitoBAM depth file for current class: /lustre/bio_running/GTEx_Long_Project/analysis/GTA9/GTA9.genome.chrM.reverse.bam.fully_cleaved.bam.depth.txt
3639
   3639 16	chrM
16569 /lustre/bio_running/GTEx_Long_Project/analysis/GTA9/GTA9.genome.chrM.reverse.bam.fully_cleaved.bam.depth.txt

#####
Elaborating class: partially_cleaved_short

sample  new_class
GTA9    partially_cleaved_short    33341
dtype: int64

(33341, 16)
Number of reads for current class: 33341
- output mitoBAM for current class: /lustre/bio_running/GTEx_Long_Project/analysis/GTA9/GTA9.genome.chrM.reverse.bam.partially_cleaved_short.bam
- output mitoBAM readslist for current class: /lustre/bio_running/GTEx_Long_Project/analysis/GTA9/GTA9.genome.chrM.reverse.bam.partially_cleaved_short.bam.readslist
- output mitoBAM depth file for current class: /lustre/bio_running/GTEx_Long_Project/analysis/GTA9/GTA9.genome.chrM.reverse.bam.partially_cleaved_short.bam.depth.txt
33341
  33341 16	chrM
16569 /lustre/bio_running/GTEx_Long_Project/analysis/GTA9/GTA9.genome.chrM.reverse.bam.partially_cleaved_short.bam.depth.txt

#####
Elaborating class: partially_cleaved_long

sample  new_class
GTA9    partially_cleaved_long    62147
dtype: int64

(62147, 16)
Number of reads for current class: 62147
- output mitoBAM for current class: /lustre/bio_running/GTEx_Long_Project/analysis/GTA9/GTA9.genome.chrM.reverse.bam.partially_cleaved_long.bam
- output mitoBAM readslist for current class: /lustre/bio_running/GTEx_Long_Project/analysis/GTA9/GTA9.genome.chrM.reverse.bam.partially_cleaved_long.bam.readslist
- output mitoBAM depth file for current class: /lustre/bio_running/GTEx_Long_Project/analysis/GTA9/GTA9.genome.chrM.reverse.bam.partially_cleaved_long.bam.depth.txt
62147
  62147 16	chrM
16569 /lustre/bio_running/GTEx_Long_Project/analysis/GTA9/GTA9.genome.chrM.reverse.bam.partially_cleaved_long.bam.depth.txt


######################################################################################################
######################################################################################################
######################################################################################################
GTC9 Total Processed samples: 1/73
Shape of df-reads for current sample: (41969, 16)
Unique number of reads: 41969

,Chr,ChrStart,ChrEnd,read_id,MAPQ,strand,read_length,alignment_length,reference_length,polyA_length,sample,overlapping_gene_ids,overlapping_gene_names,n_overlapping_gene_ids,chrM_primary_class,new_class
17030,chrM,189,397,0e87a8b6-9fac-4a98-abeb-4b240670d56d,60,-,216.0,211,208,38,GTC9,7S,7S,1,complete_gene,fully_cleaved
17031,chrM,189,397,9c1d9206-d1e2-4b86-a3ce-d98d08f49c0e,60,-,222.0,211,208,41,GTC9,7S,7S,1,complete_gene,fully_cleaved

CHECKING number of reads:
Starting mito-BAM filepath: /lustre/bio_running/GTEx_Long_Project/analysis/GTC9/GTC9.genome.chrM.reverse.bam

#####
Elaborating class: fully_cleaved

sample  new_class
GTC9    fully_cleaved    2282
dtype: int64

(2282, 16)
Number of reads for current class: 2282
- output mitoBAM for current class: /lustre/bio_running/GTEx_Long_Project/analysis/GTC9/GTC9.genome.chrM.reverse.bam.fully_cleaved.bam
- output mitoBAM readslist for current class: /lustre/bio_running/GTEx_Long_Project/analysis/GTC9/GTC9.genome.chrM.reverse.bam.fully_cleaved.bam.readslist
- output mitoBAM depth file for current class: /lustre/bio_running/GTEx_Long_Project/analysis/GTC9/GTC9.genome.chrM.reverse.bam.fully_cleaved.bam.depth.txt
2282
   2282 16	chrM
16569 /lustre/bio_running/GTEx_Long_Project/analysis/GTC9/GTC9.genome.chrM.reverse.bam.fully_cleaved.bam.depth.txt

#####
Elaborating class: partially_cleaved_short

sample  new_class
GTC9    partially_cleaved_short    13025
dtype: int64

(13025, 16)
Number of reads for current class: 13025
- output mitoBAM for current class: /lustre/bio_running/GTEx_Long_Project/analysis/GTC9/GTC9.genome.chrM.reverse.bam.partially_cleaved_short.bam
- output mitoBAM readslist for current class: /lustre/bio_running/GTEx_Long_Project/analysis/GTC9/GTC9.genome.chrM.reverse.bam.partially_cleaved_short.bam.readslist
- output mitoBAM depth file for current class: /lustre/bio_running/GTEx_Long_Project/analysis/GTC9/GTC9.genome.chrM.reverse.bam.partially_cleaved_short.bam.depth.txt
13025
  13025 16	chrM
16569 /lustre/bio_running/GTEx_Long_Project/analysis/GTC9/GTC9.genome.chrM.reverse.bam.partially_cleaved_short.bam.depth.txt

#####
Elaborating class: partially_cleaved_long

sample  new_class
GTC9    partially_cleaved_long    26662
dtype: int64

(26662, 16)
Number of reads for current class: 26662
- output mitoBAM for current class: /lustre/bio_running/GTEx_Long_Project/analysis/GTC9/GTC9.genome.chrM.reverse.bam.partially_cleaved_long.bam
- output mitoBAM readslist for current class: /lustre/bio_running/GTEx_Long_Project/analysis/GTC9/GTC9.genome.chrM.reverse.bam.partially_cleaved_long.bam.readslist
- output mitoBAM depth file for current class: /lustre/bio_running/GTEx_Long_Project/analysis/GTC9/GTC9.genome.chrM.reverse.bam.partially_cleaved_long.bam.depth.txt
26662
  26662 16	chrM
16569 /lustre/bio_running/GTEx_Long_Project/analysis/GTC9/GTC9.genome.chrM.reverse.bam.partially_cleaved_long.bam.depth.txt


######################################################################################################
######################################################################################################
######################################################################################################
GTG5 Total Processed samples: 2/73
Shape of df-reads for current sample: (41143, 16)
Unique number of reads: 41143

,Chr,ChrStart,ChrEnd,read_id,MAPQ,strand,read_length,alignment_length,reference_length,polyA_length,sample,overlapping_gene_ids,overlapping_gene_names,n_overlapping_gene_ids,chrM_primary_class,new_class
40368,chrM,189,397,f874f75b-43ea-4605-a30b-6bb351589bc7,60,-,241.0,208,208,26,GTG5,7S,7S,1,complete_gene,fully_cleaved
40369,chrM,189,397,a3a1f0ab-e061-4bcc-8f6a-d121be8e5917,60,-,238.0,207,208,11,GTG5,7S,7S,1,complete_gene,fully_cleaved

CHECKING number of reads:
Starting mito-BAM filepath: /lustre/bio_running/GTEx_Long_Project/analysis/GTG5/GTG5.genome.chrM.reverse.bam

#####
Elaborating class: fully_cleaved

sample  new_class
GTG5    fully_cleaved    4811
dtype: int64

(4811, 16)
Number of reads for current class: 4811
- output mitoBAM for current class: /lustre/bio_running/GTEx_Long_Project/analysis/GTG5/GTG5.genome.chrM.reverse.bam.fully_cleaved.bam
- output mitoBAM readslist for current class: /lustre/bio_running/GTEx_Long_Project/analysis/GTG5/GTG5.genome.chrM.reverse.bam.fully_cleaved.bam.readslist
- output mitoBAM depth file for current class: /lustre/bio_running/GTEx_Long_Project/analysis/GTG5/GTG5.genome.chrM.reverse.bam.fully_cleaved.bam.depth.txt
4811
   4811 16	chrM
16569 /lustre/bio_running/GTEx_Long_Project/analysis/GTG5/GTG5.genome.chrM.reverse.bam.fully_cleaved.bam.depth.txt

#####
Elaborating class: partially_cleaved_short

sample  new_class
GTG5    partially_cleaved_short    20857
dtype: int64

(20857, 16)
Number of reads for current class: 20857
- output mitoBAM for current class: /lustre/bio_running/GTEx_Long_Project/analysis/GTG5/GTG5.genome.chrM.reverse.bam.partially_cleaved_short.bam
- output mitoBAM readslist for current class: /lustre/bio_running/GTEx_Long_Project/analysis/GTG5/GTG5.genome.chrM.reverse.bam.partially_cleaved_short.bam.readslist
- output mitoBAM depth file for current class: /lustre/bio_running/GTEx_Long_Project/analysis/GTG5/GTG5.genome.chrM.reverse.bam.partially_cleaved_short.bam.depth.txt
20857
  20857 16	chrM
16569 /lustre/bio_running/GTEx_Long_Project/analysis/GTG5/GTG5.genome.chrM.reverse.bam.partially_cleaved_short.bam.depth.txt

#####
Elaborating class: partially_cleaved_long

sample  new_class
GTG5    partially_cleaved_long    15475
dtype: int64

(15475, 16)
Number of reads for current class: 15475
- output mitoBAM for current class: /lustre/bio_running/GTEx_Long_Project/analysis/GTG5/GTG5.genome.chrM.reverse.bam.partially_cleaved_long.bam
- output mitoBAM readslist for current class: /lustre/bio_running/GTEx_Long_Project/analysis/GTG5/GTG5.genome.chrM.reverse.bam.partially_cleaved_long.bam.readslist
- output mitoBAM depth file for current class: /lustre/bio_running/GTEx_Long_Project/analysis/GTG5/GTG5.genome.chrM.reverse.bam.partially_cleaved_long.bam.depth.txt
15475
  15475 16	chrM
16569 /lustre/bio_running/GTEx_Long_Project/analysis/GTG5/GTG5.genome.chrM.reverse.bam.partially_cleaved_long.bam.depth.txt


######################################################################################################
######################################################################################################
######################################################################################################
GTA1 Total Processed samples: 3/73
Shape of df-reads for current sample: (37576, 16)
Unique number of reads: 37576

,Chr,ChrStart,ChrEnd,read_id,MAPQ,strand,read_length,alignment_length,reference_length,polyA_length,sample,overlapping_gene_ids,overlapping_gene_names,n_overlapping_gene_ids,chrM_primary_class,new_class
0,chrM,189,397,8219ade2-143f-4d8b-b15a-fc02f6430ea9,60,-,216.0,205,208,32,GTA1,7S,7S,1,complete_gene,fully_cleaved
1,chrM,189,396,4ed13e94-9fc0-4635-831b-d1ac2708c6ba,60,-,239.0,211,207,29,GTA1,7S,7S,1,complete_gene,fully_cleaved

CHECKING number of reads:
Starting mito-BAM filepath: /lustre/bio_running/GTEx_Long_Project/analysis/GTA1/GTA1.genome.chrM.reverse.bam

#####
Elaborating class: fully_cleaved

sample  new_class
GTA1    fully_cleaved    1479
dtype: int64

(1479, 16)
Number of reads for current class: 1479
- output mitoBAM for current class: /lustre/bio_running/GTEx_Long_Project/analysis/GTA1/GTA1.genome.chrM.reverse.bam.fully_cleaved.bam
- output mitoBAM readslist for current class: /lustre/bio_running/GTEx_Long_Project/analysis/GTA1/GTA1.genome.chrM.reverse.bam.fully_cleaved.bam.readslist
- output mitoBAM depth file for current class: /lustre/bio_running/GTEx_Long_Project/analysis/GTA1/GTA1.genome.chrM.reverse.bam.fully_cleaved.bam.depth.txt
1479
   1479 16	chrM
16569 /lustre/bio_running/GTEx_Long_Project/analysis/GTA1/GTA1.genome.chrM.reverse.bam.fully_cleaved.bam.depth.txt

#####
Elaborating class: partially_cleaved_short

sample  new_class
GTA1    partially_cleaved_short    17794
dtype: int64

(17794, 16)
Number of reads for current class: 17794
- output mitoBAM for current class: /lustre/bio_running/GTEx_Long_Project/analysis/GTA1/GTA1.genome.chrM.reverse.bam.partially_cleaved_short.bam
- output mitoBAM readslist for current class: /lustre/bio_running/GTEx_Long_Project/analysis/GTA1/GTA1.genome.chrM.reverse.bam.partially_cleaved_short.bam.readslist
- output mitoBAM depth file for current class: /lustre/bio_running/GTEx_Long_Project/analysis/GTA1/GTA1.genome.chrM.reverse.bam.partially_cleaved_short.bam.depth.txt
17794
  17794 16	chrM
16569 /lustre/bio_running/GTEx_Long_Project/analysis/GTA1/GTA1.genome.chrM.reverse.bam.partially_cleaved_short.bam.depth.txt

#####
Elaborating class: partially_cleaved_long

sample  new_class
GTA1    partially_cleaved_long    18303
dtype: int64

(18303, 16)
Number of reads for current class: 18303
- output mitoBAM for current class: /lustre/bio_running/GTEx_Long_Project/analysis/GTA1/GTA1.genome.chrM.reverse.bam.partially_cleaved_long.bam
- output mitoBAM readslist for current class: /lustre/bio_running/GTEx_Long_Project/analysis/GTA1/GTA1.genome.chrM.reverse.bam.partially_cleaved_long.bam.readslist
- output mitoBAM depth file for current class: /lustre/bio_running/GTEx_Long_Project/analysis/GTA1/GTA1.genome.chrM.reverse.bam.partially_cleaved_long.bam.depth.txt
18303
  18303 16	chrM
16569 /lustre/bio_running/GTEx_Long_Project/analysis/GTA1/GTA1.genome.chrM.reverse.bam.partially_cleaved_long.bam.depth.txt


######################################################################################################
######################################################################################################
######################################################################################################
GTE2 Total Processed samples: 4/73
Shape of df-reads for current sample: (35062, 16)
Unique number of reads: 35062

,Chr,ChrStart,ChrEnd,read_id,MAPQ,strand,read_length,alignment_length,reference_length,polyA_length,sample,overlapping_gene_ids,overlapping_gene_names,n_overlapping_gene_ids,chrM_primary_class,new_class
28664,chrM,189,396,d9fe2a1c-7a67-4ae5-811b-3d7ad2f206d5,60,-,237.0,208,207,63,GTE2,7S,7S,1,complete_gene,fully_cleaved
28665,chrM,189,397,5df59974-bc96-4fc0-997d-1c6b81c0d7f4,60,-,220.0,210,208,60,GTE2,7S,7S,1,complete_gene,fully_cleaved

CHECKING number of reads:
Starting mito-BAM filepath: /lustre/bio_running/GTEx_Long_Project/analysis/GTE2/GTE2.genome.chrM.reverse.bam

#####
Elaborating class: fully_cleaved

sample  new_class
GTE2    fully_cleaved    2681
dtype: int64

(2681, 16)
Number of reads for current class: 2681
- output mitoBAM for current class: /lustre/bio_running/GTEx_Long_Project/analysis/GTE2/GTE2.genome.chrM.reverse.bam.fully_cleaved.bam
- output mitoBAM readslist for current class: /lustre/bio_running/GTEx_Long_Project/analysis/GTE2/GTE2.genome.chrM.reverse.bam.fully_cleaved.bam.readslist
- output mitoBAM depth file for current class: /lustre/bio_running/GTEx_Long_Project/analysis/GTE2/GTE2.genome.chrM.reverse.bam.fully_cleaved.bam.depth.txt
2681
   2681 16	chrM
16569 /lustre/bio_running/GTEx_Long_Project/analysis/GTE2/GTE2.genome.chrM.reverse.bam.fully_cleaved.bam.depth.txt

#####
Elaborating class: partially_cleaved_short

sample  new_class
GTE2    partially_cleaved_short    17010
dtype: int64

(17010, 16)
Number of reads for current class: 17010
- output mitoBAM for current class: /lustre/bio_running/GTEx_Long_Project/analysis/GTE2/GTE2.genome.chrM.reverse.bam.partially_cleaved_short.bam
- output mitoBAM readslist for current class: /lustre/bio_running/GTEx_Long_Project/analysis/GTE2/GTE2.genome.chrM.reverse.bam.partially_cleaved_short.bam.readslist
- output mitoBAM depth file for current class: /lustre/bio_running/GTEx_Long_Project/analysis/GTE2/GTE2.genome.chrM.reverse.bam.partially_cleaved_short.bam.depth.txt
17010
  17010 16	chrM
16569 /lustre/bio_running/GTEx_Long_Project/analysis/GTE2/GTE2.genome.chrM.reverse.bam.partially_cleaved_short.bam.depth.txt

#####
Elaborating class: partially_cleaved_long

sample  new_class
GTE2    partially_cleaved_long    15371
dtype: int64

(15371, 16)
Number of reads for current class: 15371
- output mitoBAM for current class: /lustre/bio_running/GTEx_Long_Project/analysis/GTE2/GTE2.genome.chrM.reverse.bam.partially_cleaved_long.bam
- output mitoBAM readslist for current class: /lustre/bio_running/GTEx_Long_Project/analysis/GTE2/GTE2.genome.chrM.reverse.bam.partially_cleaved_long.bam.readslist
- output mitoBAM depth file for current class: /lustre/bio_running/GTEx_Long_Project/analysis/GTE2/GTE2.genome.chrM.reverse.bam.partially_cleaved_long.bam.depth.txt
15371
  15371 16	chrM
16569 /lustre/bio_running/GTEx_Long_Project/analysis/GTE2/GTE2.genome.chrM.reverse.bam.partially_cleaved_long.bam.depth.txt


######################################################################################################
######################################################################################################
######################################################################################################
GTH5 Total Processed samples: 5/73
Shape of df-reads for current sample: (29886, 16)
Unique number of reads: 29886

,Chr,ChrStart,ChrEnd,read_id,MAPQ,strand,read_length,alignment_length,reference_length,polyA_length,sample,overlapping_gene_ids,overlapping_gene_names,n_overlapping_gene_ids,chrM_primary_class,new_class
49041,chrM,189,397,988ebe53-f17e-4a4d-aa4b-11da6d08256e,60,-,329.0,305,208,12,GTH5,7S,7S,1,complete_gene,fully_cleaved
49042,chrM,189,397,54b9d431-52a9-4842-b2e8-969b99fe4faf,60,-,214.0,209,208,48,GTH5,7S,7S,1,complete_gene,fully_cleaved

CHECKING number of reads:
Starting mito-BAM filepath: /lustre/bio_running/GTEx_Long_Project/analysis/GTH5/GTH5.genome.chrM.reverse.bam

#####
Elaborating class: fully_cleaved

sample  new_class
GTH5    fully_cleaved    1699
dtype: int64

(1699, 16)
Number of reads for current class: 1699
- output mitoBAM for current class: /lustre/bio_running/GTEx_Long_Project/analysis/GTH5/GTH5.genome.chrM.reverse.bam.fully_cleaved.bam
- output mitoBAM readslist for current class: /lustre/bio_running/GTEx_Long_Project/analysis/GTH5/GTH5.genome.chrM.reverse.bam.fully_cleaved.bam.readslist
- output mitoBAM depth file for current class: /lustre/bio_running/GTEx_Long_Project/analysis/GTH5/GTH5.genome.chrM.reverse.bam.fully_cleaved.bam.depth.txt
1699
   1699 16	chrM
16569 /lustre/bio_running/GTEx_Long_Project/analysis/GTH5/GTH5.genome.chrM.reverse.bam.fully_cleaved.bam.depth.txt

#####
Elaborating class: partially_cleaved_short

sample  new_class
GTH5    partially_cleaved_short    19300
dtype: int64

(19300, 16)
Number of reads for current class: 19300
- output mitoBAM for current class: /lustre/bio_running/GTEx_Long_Project/analysis/GTH5/GTH5.genome.chrM.reverse.bam.partially_cleaved_short.bam
- output mitoBAM readslist for current class: /lustre/bio_running/GTEx_Long_Project/analysis/GTH5/GTH5.genome.chrM.reverse.bam.partially_cleaved_short.bam.readslist
- output mitoBAM depth file for current class: /lustre/bio_running/GTEx_Long_Project/analysis/GTH5/GTH5.genome.chrM.reverse.bam.partially_cleaved_short.bam.depth.txt
19300
  19300 16	chrM
16569 /lustre/bio_running/GTEx_Long_Project/analysis/GTH5/GTH5.genome.chrM.reverse.bam.partially_cleaved_short.bam.depth.txt

#####
Elaborating class: partially_cleaved_long

sample  new_class
GTH5    partially_cleaved_long    8887
dtype: int64

(8887, 16)
Number of reads for current class: 8887
- output mitoBAM for current class: /lustre/bio_running/GTEx_Long_Project/analysis/GTH5/GTH5.genome.chrM.reverse.bam.partially_cleaved_long.bam
- output mitoBAM readslist for current class: /lustre/bio_running/GTEx_Long_Project/analysis/GTH5/GTH5.genome.chrM.reverse.bam.partially_cleaved_long.bam.readslist
- output mitoBAM depth file for current class: /lustre/bio_running/GTEx_Long_Project/analysis/GTH5/GTH5.genome.chrM.reverse.bam.partially_cleaved_long.bam.depth.txt
8887
   8887 16	chrM
16569 /lustre/bio_running/GTEx_Long_Project/analysis/GTH5/GTH5.genome.chrM.reverse.bam.partially_cleaved_long.bam.depth.txt


######################################################################################################
######################################################################################################
######################################################################################################
GTD9 Total Processed samples: 6/73
Shape of df-reads for current sample: (29286, 16)
Unique number of reads: 29286

,Chr,ChrStart,ChrEnd,read_id,MAPQ,strand,read_length,alignment_length,reference_length,polyA_length,sample,overlapping_gene_ids,overlapping_gene_names,n_overlapping_gene_ids,chrM_primary_class,new_class
27092,chrM,189,388,d388bb51-c497-44ae-acdc-cdea3f84c69b,60,-,229.0,195,199,20,GTD9,7S,7S,1,complete_gene,fully_cleaved
27093,chrM,189,397,469204a8-a795-4bf3-9278-cf917fb45f10,60,-,208.0,203,208,48,GTD9,7S,7S,1,complete_gene,fully_cleaved

CHECKING number of reads:
Starting mito-BAM filepath: /lustre/bio_running/GTEx_Long_Project/analysis/GTD9/GTD9.genome.chrM.reverse.bam

#####
Elaborating class: fully_cleaved

sample  new_class
GTD9    fully_cleaved    1532
dtype: int64

(1532, 16)
Number of reads for current class: 1532
- output mitoBAM for current class: /lustre/bio_running/GTEx_Long_Project/analysis/GTD9/GTD9.genome.chrM.reverse.bam.fully_cleaved.bam
- output mitoBAM readslist for current class: /lustre/bio_running/GTEx_Long_Project/analysis/GTD9/GTD9.genome.chrM.reverse.bam.fully_cleaved.bam.readslist
- output mitoBAM depth file for current class: /lustre/bio_running/GTEx_Long_Project/analysis/GTD9/GTD9.genome.chrM.reverse.bam.fully_cleaved.bam.depth.txt
1532
   1532 16	chrM
16569 /lustre/bio_running/GTEx_Long_Project/analysis/GTD9/GTD9.genome.chrM.reverse.bam.fully_cleaved.bam.depth.txt

#####
Elaborating class: partially_cleaved_short

sample  new_class
GTD9    partially_cleaved_short    12762
dtype: int64

(12762, 16)
Number of reads for current class: 12762
- output mitoBAM for current class: /lustre/bio_running/GTEx_Long_Project/analysis/GTD9/GTD9.genome.chrM.reverse.bam.partially_cleaved_short.bam
- output mitoBAM readslist for current class: /lustre/bio_running/GTEx_Long_Project/analysis/GTD9/GTD9.genome.chrM.reverse.bam.partially_cleaved_short.bam.readslist
- output mitoBAM depth file for current class: /lustre/bio_running/GTEx_Long_Project/analysis/GTD9/GTD9.genome.chrM.reverse.bam.partially_cleaved_short.bam.depth.txt
12762
  12762 16	chrM
16569 /lustre/bio_running/GTEx_Long_Project/analysis/GTD9/GTD9.genome.chrM.reverse.bam.partially_cleaved_short.bam.depth.txt

#####
Elaborating class: partially_cleaved_long

sample  new_class
GTD9    partially_cleaved_long    14992
dtype: int64

(14992, 16)
Number of reads for current class: 14992
- output mitoBAM for current class: /lustre/bio_running/GTEx_Long_Project/analysis/GTD9/GTD9.genome.chrM.reverse.bam.partially_cleaved_long.bam
- output mitoBAM readslist for current class: /lustre/bio_running/GTEx_Long_Project/analysis/GTD9/GTD9.genome.chrM.reverse.bam.partially_cleaved_long.bam.readslist
- output mitoBAM depth file for current class: /lustre/bio_running/GTEx_Long_Project/analysis/GTD9/GTD9.genome.chrM.reverse.bam.partially_cleaved_long.bam.depth.txt
14992
  14992 16	chrM
16569 /lustre/bio_running/GTEx_Long_Project/analysis/GTD9/GTD9.genome.chrM.reverse.bam.partially_cleaved_long.bam.depth.txt


######################################################################################################
######################################################################################################
######################################################################################################
GTF4 Total Processed samples: 7/73
Shape of df-reads for current sample: (29211, 16)
Unique number of reads: 29211

,Chr,ChrStart,ChrEnd,read_id,MAPQ,strand,read_length,alignment_length,reference_length,polyA_length,sample,overlapping_gene_ids,overlapping_gene_names,n_overlapping_gene_ids,chrM_primary_class,new_class
34589,chrM,189,395,1eb52a2b-fe68-47cc-bb84-59a71fd7170a,60,-,212.0,207,206,41,GTF4,7S,7S,1,complete_gene,fully_cleaved
34590,chrM,189,397,ad34ca66-29cc-419b-aa02-85aa9317db5c,60,-,237.0,223,208,43,GTF4,7S,7S,1,complete_gene,fully_cleaved

CHECKING number of reads:
Starting mito-BAM filepath: /lustre/bio_running/GTEx_Long_Project/analysis/GTF4/GTF4.genome.chrM.reverse.bam

#####
Elaborating class: fully_cleaved

sample  new_class
GTF4    fully_cleaved    2127
dtype: int64

(2127, 16)
Number of reads for current class: 2127
- output mitoBAM for current class: /lustre/bio_running/GTEx_Long_Project/analysis/GTF4/GTF4.genome.chrM.reverse.bam.fully_cleaved.bam
- output mitoBAM readslist for current class: /lustre/bio_running/GTEx_Long_Project/analysis/GTF4/GTF4.genome.chrM.reverse.bam.fully_cleaved.bam.readslist
- output mitoBAM depth file for current class: /lustre/bio_running/GTEx_Long_Project/analysis/GTF4/GTF4.genome.chrM.reverse.bam.fully_cleaved.bam.depth.txt
2127
   2127 16	chrM
16569 /lustre/bio_running/GTEx_Long_Project/analysis/GTF4/GTF4.genome.chrM.reverse.bam.fully_cleaved.bam.depth.txt

#####
Elaborating class: partially_cleaved_short

sample  new_class
GTF4    partially_cleaved_short    14646
dtype: int64

(14646, 16)
Number of reads for current class: 14646
- output mitoBAM for current class: /lustre/bio_running/GTEx_Long_Project/analysis/GTF4/GTF4.genome.chrM.reverse.bam.partially_cleaved_short.bam
- output mitoBAM readslist for current class: /lustre/bio_running/GTEx_Long_Project/analysis/GTF4/GTF4.genome.chrM.reverse.bam.partially_cleaved_short.bam.readslist
- output mitoBAM depth file for current class: /lustre/bio_running/GTEx_Long_Project/analysis/GTF4/GTF4.genome.chrM.reverse.bam.partially_cleaved_short.bam.depth.txt
14646
  14646 16	chrM
16569 /lustre/bio_running/GTEx_Long_Project/analysis/GTF4/GTF4.genome.chrM.reverse.bam.partially_cleaved_short.bam.depth.txt

#####
Elaborating class: partially_cleaved_long

sample  new_class
GTF4    partially_cleaved_long    12438
dtype: int64

(12438, 16)
Number of reads for current class: 12438
- output mitoBAM for current class: /lustre/bio_running/GTEx_Long_Project/analysis/GTF4/GTF4.genome.chrM.reverse.bam.partially_cleaved_long.bam
- output mitoBAM readslist for current class: /lustre/bio_running/GTEx_Long_Project/analysis/GTF4/GTF4.genome.chrM.reverse.bam.partially_cleaved_long.bam.readslist
- output mitoBAM depth file for current class: /lustre/bio_running/GTEx_Long_Project/analysis/GTF4/GTF4.genome.chrM.reverse.bam.partially_cleaved_long.bam.depth.txt
12438
  12438 16	chrM
16569 /lustre/bio_running/GTEx_Long_Project/analysis/GTF4/GTF4.genome.chrM.reverse.bam.partially_cleaved_long.bam.depth.txt


######################################################################################################
######################################################################################################
######################################################################################################
GTG9 Total Processed samples: 8/73
Shape of df-reads for current sample: (24957, 16)
Unique number of reads: 24957

,Chr,ChrStart,ChrEnd,read_id,MAPQ,strand,read_length,alignment_length,reference_length,polyA_length,sample,overlapping_gene_ids,overlapping_gene_names,n_overlapping_gene_ids,chrM_primary_class,new_class
46593,chrM,189,398,2bad6be1-9ca3-4891-b91f-03e484066de4,60,-,219.0,209,209,53,GTG9,7S,7S,1,complete_gene,fully_cleaved
46594,chrM,189,397,83ffbacf-ac18-444d-8755-d8ec16de9a59,60,-,224.0,209,208,36,GTG9,7S,7S,1,complete_gene,fully_cleaved

CHECKING number of reads:
Starting mito-BAM filepath: /lustre/bio_running/GTEx_Long_Project/analysis/GTG9/GTG9.genome.chrM.reverse.bam

#####
Elaborating class: fully_cleaved

sample  new_class
GTG9    fully_cleaved    1165
dtype: int64

(1165, 16)
Number of reads for current class: 1165
- output mitoBAM for current class: /lustre/bio_running/GTEx_Long_Project/analysis/GTG9/GTG9.genome.chrM.reverse.bam.fully_cleaved.bam
- output mitoBAM readslist for current class: /lustre/bio_running/GTEx_Long_Project/analysis/GTG9/GTG9.genome.chrM.reverse.bam.fully_cleaved.bam.readslist
- output mitoBAM depth file for current class: /lustre/bio_running/GTEx_Long_Project/analysis/GTG9/GTG9.genome.chrM.reverse.bam.fully_cleaved.bam.depth.txt
1165
   1165 16	chrM
16569 /lustre/bio_running/GTEx_Long_Project/analysis/GTG9/GTG9.genome.chrM.reverse.bam.fully_cleaved.bam.depth.txt

#####
Elaborating class: partially_cleaved_short

sample  new_class
GTG9    partially_cleaved_short    15671
dtype: int64

(15671, 16)
Number of reads for current class: 15671
- output mitoBAM for current class: /lustre/bio_running/GTEx_Long_Project/analysis/GTG9/GTG9.genome.chrM.reverse.bam.partially_cleaved_short.bam
- output mitoBAM readslist for current class: /lustre/bio_running/GTEx_Long_Project/analysis/GTG9/GTG9.genome.chrM.reverse.bam.partially_cleaved_short.bam.readslist
- output mitoBAM depth file for current class: /lustre/bio_running/GTEx_Long_Project/analysis/GTG9/GTG9.genome.chrM.reverse.bam.partially_cleaved_short.bam.depth.txt
15671
  15671 16	chrM
16569 /lustre/bio_running/GTEx_Long_Project/analysis/GTG9/GTG9.genome.chrM.reverse.bam.partially_cleaved_short.bam.depth.txt

#####
Elaborating class: partially_cleaved_long

sample  new_class
GTG9    partially_cleaved_long    8121
dtype: int64

(8121, 16)
Number of reads for current class: 8121
- output mitoBAM for current class: /lustre/bio_running/GTEx_Long_Project/analysis/GTG9/GTG9.genome.chrM.reverse.bam.partially_cleaved_long.bam
- output mitoBAM readslist for current class: /lustre/bio_running/GTEx_Long_Project/analysis/GTG9/GTG9.genome.chrM.reverse.bam.partially_cleaved_long.bam.readslist
- output mitoBAM depth file for current class: /lustre/bio_running/GTEx_Long_Project/analysis/GTG9/GTG9.genome.chrM.reverse.bam.partially_cleaved_long.bam.depth.txt
8121
   8121 16	chrM
16569 /lustre/bio_running/GTEx_Long_Project/analysis/GTG9/GTG9.genome.chrM.reverse.bam.partially_cleaved_long.bam.depth.txt


######################################################################################################
######################################################################################################
######################################################################################################
GTC8 Total Processed samples: 9/73
Shape of df-reads for current sample: (24489, 16)
Unique number of reads: 24489

,Chr,ChrStart,ChrEnd,read_id,MAPQ,strand,read_length,alignment_length,reference_length,polyA_length,sample,overlapping_gene_ids,overlapping_gene_names,n_overlapping_gene_ids,chrM_primary_class,new_class
15253,chrM,189,397,c2162e2d-6dba-4b03-ab6c-e8a22973779a,60,-,218.0,211,208,43,GTC8,7S,7S,1,complete_gene,fully_cleaved
15254,chrM,189,392,52c82088-1b25-49be-9b65-aa77c9ea466b,60,-,216.0,206,203,43,GTC8,7S,7S,1,complete_gene,fully_cleaved

CHECKING number of reads:
Starting mito-BAM filepath: /lustre/bio_running/GTEx_Long_Project/analysis/GTC8/GTC8.genome.chrM.reverse.bam

#####
Elaborating class: fully_cleaved

sample  new_class
GTC8    fully_cleaved    1777
dtype: int64

(1777, 16)
Number of reads for current class: 1777
- output mitoBAM for current class: /lustre/bio_running/GTEx_Long_Project/analysis/GTC8/GTC8.genome.chrM.reverse.bam.fully_cleaved.bam
- output mitoBAM readslist for current class: /lustre/bio_running/GTEx_Long_Project/analysis/GTC8/GTC8.genome.chrM.reverse.bam.fully_cleaved.bam.readslist
- output mitoBAM depth file for current class: /lustre/bio_running/GTEx_Long_Project/analysis/GTC8/GTC8.genome.chrM.reverse.bam.fully_cleaved.bam.depth.txt
1777
   1777 16	chrM
16569 /lustre/bio_running/GTEx_Long_Project/analysis/GTC8/GTC8.genome.chrM.reverse.bam.fully_cleaved.bam.depth.txt

#####
Elaborating class: partially_cleaved_short

sample  new_class
GTC8    partially_cleaved_short    12770
dtype: int64

(12770, 16)
Number of reads for current class: 12770
- output mitoBAM for current class: /lustre/bio_running/GTEx_Long_Project/analysis/GTC8/GTC8.genome.chrM.reverse.bam.partially_cleaved_short.bam
- output mitoBAM readslist for current class: /lustre/bio_running/GTEx_Long_Project/analysis/GTC8/GTC8.genome.chrM.reverse.bam.partially_cleaved_short.bam.readslist
- output mitoBAM depth file for current class: /lustre/bio_running/GTEx_Long_Project/analysis/GTC8/GTC8.genome.chrM.reverse.bam.partially_cleaved_short.bam.depth.txt
12770
  12770 16	chrM
16569 /lustre/bio_running/GTEx_Long_Project/analysis/GTC8/GTC8.genome.chrM.reverse.bam.partially_cleaved_short.bam.depth.txt

#####
Elaborating class: partially_cleaved_long

sample  new_class
GTC8    partially_cleaved_long    9942
dtype: int64

(9942, 16)
Number of reads for current class: 9942
- output mitoBAM for current class: /lustre/bio_running/GTEx_Long_Project/analysis/GTC8/GTC8.genome.chrM.reverse.bam.partially_cleaved_long.bam
- output mitoBAM readslist for current class: /lustre/bio_running/GTEx_Long_Project/analysis/GTC8/GTC8.genome.chrM.reverse.bam.partially_cleaved_long.bam.readslist
- output mitoBAM depth file for current class: /lustre/bio_running/GTEx_Long_Project/analysis/GTC8/GTC8.genome.chrM.reverse.bam.partially_cleaved_long.bam.depth.txt
9942
   9942 16	chrM
16569 /lustre/bio_running/GTEx_Long_Project/analysis/GTC8/GTC8.genome.chrM.reverse.bam.partially_cleaved_long.bam.depth.txt


######################################################################################################
######################################################################################################
######################################################################################################
GTB6 Total Processed samples: 10/73
Shape of df-reads for current sample: (21798, 16)
Unique number of reads: 21798

,Chr,ChrStart,ChrEnd,read_id,MAPQ,strand,read_length,alignment_length,reference_length,polyA_length,sample,overlapping_gene_ids,overlapping_gene_names,n_overlapping_gene_ids,chrM_primary_class,new_class
10587,chrM,189,390,f6448092-1158-4b31-9b68-075e276ac2b3,60,-,213.0,204,201,34,GTB6,7S,7S,1,complete_gene,fully_cleaved
10588,chrM,189,397,be0f2290-d81e-420f-b604-64748bac0fda,60,-,226.0,211,208,43,GTB6,7S,7S,1,complete_gene,fully_cleaved

CHECKING number of reads:
Starting mito-BAM filepath: /lustre/bio_running/GTEx_Long_Project/analysis/GTB6/GTB6.genome.chrM.reverse.bam

#####
Elaborating class: fully_cleaved

sample  new_class
GTB6    fully_cleaved    697
dtype: int64

(697, 16)
Number of reads for current class: 697
- output mitoBAM for current class: /lustre/bio_running/GTEx_Long_Project/analysis/GTB6/GTB6.genome.chrM.reverse.bam.fully_cleaved.bam
- output mitoBAM readslist for current class: /lustre/bio_running/GTEx_Long_Project/analysis/GTB6/GTB6.genome.chrM.reverse.bam.fully_cleaved.bam.readslist
- output mitoBAM depth file for current class: /lustre/bio_running/GTEx_Long_Project/analysis/GTB6/GTB6.genome.chrM.reverse.bam.fully_cleaved.bam.depth.txt
697
    697 16	chrM
16569 /lustre/bio_running/GTEx_Long_Project/analysis/GTB6/GTB6.genome.chrM.reverse.bam.fully_cleaved.bam.depth.txt

#####
Elaborating class: partially_cleaved_short

sample  new_class
GTB6    partially_cleaved_short    10270
dtype: int64

(10270, 16)
Number of reads for current class: 10270
- output mitoBAM for current class: /lustre/bio_running/GTEx_Long_Project/analysis/GTB6/GTB6.genome.chrM.reverse.bam.partially_cleaved_short.bam
- output mitoBAM readslist for current class: /lustre/bio_running/GTEx_Long_Project/analysis/GTB6/GTB6.genome.chrM.reverse.bam.partially_cleaved_short.bam.readslist
- output mitoBAM depth file for current class: /lustre/bio_running/GTEx_Long_Project/analysis/GTB6/GTB6.genome.chrM.reverse.bam.partially_cleaved_short.bam.depth.txt
10270
  10270 16	chrM
16569 /lustre/bio_running/GTEx_Long_Project/analysis/GTB6/GTB6.genome.chrM.reverse.bam.partially_cleaved_short.bam.depth.txt

#####
Elaborating class: partially_cleaved_long

sample  new_class
GTB6    partially_cleaved_long    10831
dtype: int64

(10831, 16)
Number of reads for current class: 10831
- output mitoBAM for current class: /lustre/bio_running/GTEx_Long_Project/analysis/GTB6/GTB6.genome.chrM.reverse.bam.partially_cleaved_long.bam
- output mitoBAM readslist for current class: /lustre/bio_running/GTEx_Long_Project/analysis/GTB6/GTB6.genome.chrM.reverse.bam.partially_cleaved_long.bam.readslist
- output mitoBAM depth file for current class: /lustre/bio_running/GTEx_Long_Project/analysis/GTB6/GTB6.genome.chrM.reverse.bam.partially_cleaved_long.bam.depth.txt
10831
  10831 16	chrM
16569 /lustre/bio_running/GTEx_Long_Project/analysis/GTB6/GTB6.genome.chrM.reverse.bam.partially_cleaved_long.bam.depth.txt


######################################################################################################
######################################################################################################
######################################################################################################
GTH2 Total Processed samples: 11/73
Shape of df-reads for current sample: (21140, 16)
Unique number of reads: 21140

,Chr,ChrStart,ChrEnd,read_id,MAPQ,strand,read_length,alignment_length,reference_length,polyA_length,sample,overlapping_gene_ids,overlapping_gene_names,n_overlapping_gene_ids,chrM_primary_class,new_class
47878,chrM,189,400,94e0fc22-ec9e-4d9d-a3e3-7333c162f6d4,60,-,242.0,212,211,29,GTH2,7S,7S,1,complete_gene,fully_cleaved
47879,chrM,189,398,a68199a4-33d3-49ba-a35d-08221c913dd7,60,-,219.0,207,209,1,GTH2,7S,7S,1,complete_gene,fully_cleaved

CHECKING number of reads:
Starting mito-BAM filepath: /lustre/bio_running/GTEx_Long_Project/analysis/GTH2/GTH2.genome.chrM.reverse.bam

#####
Elaborating class: fully_cleaved

sample  new_class
GTH2    fully_cleaved    878
dtype: int64

(878, 16)
Number of reads for current class: 878
- output mitoBAM for current class: /lustre/bio_running/GTEx_Long_Project/analysis/GTH2/GTH2.genome.chrM.reverse.bam.fully_cleaved.bam
- output mitoBAM readslist for current class: /lustre/bio_running/GTEx_Long_Project/analysis/GTH2/GTH2.genome.chrM.reverse.bam.fully_cleaved.bam.readslist
- output mitoBAM depth file for current class: /lustre/bio_running/GTEx_Long_Project/analysis/GTH2/GTH2.genome.chrM.reverse.bam.fully_cleaved.bam.depth.txt
878
    878 16	chrM
16569 /lustre/bio_running/GTEx_Long_Project/analysis/GTH2/GTH2.genome.chrM.reverse.bam.fully_cleaved.bam.depth.txt

#####
Elaborating class: partially_cleaved_short

sample  new_class
GTH2    partially_cleaved_short    9293
dtype: int64

(9293, 16)
Number of reads for current class: 9293
- output mitoBAM for current class: /lustre/bio_running/GTEx_Long_Project/analysis/GTH2/GTH2.genome.chrM.reverse.bam.partially_cleaved_short.bam
- output mitoBAM readslist for current class: /lustre/bio_running/GTEx_Long_Project/analysis/GTH2/GTH2.genome.chrM.reverse.bam.partially_cleaved_short.bam.readslist
- output mitoBAM depth file for current class: /lustre/bio_running/GTEx_Long_Project/analysis/GTH2/GTH2.genome.chrM.reverse.bam.partially_cleaved_short.bam.depth.txt
9293
   9293 16	chrM
16569 /lustre/bio_running/GTEx_Long_Project/analysis/GTH2/GTH2.genome.chrM.reverse.bam.partially_cleaved_short.bam.depth.txt

#####
Elaborating class: partially_cleaved_long

sample  new_class
GTH2    partially_cleaved_long    10969
dtype: int64

(10969, 16)
Number of reads for current class: 10969
- output mitoBAM for current class: /lustre/bio_running/GTEx_Long_Project/analysis/GTH2/GTH2.genome.chrM.reverse.bam.partially_cleaved_long.bam
- output mitoBAM readslist for current class: /lustre/bio_running/GTEx_Long_Project/analysis/GTH2/GTH2.genome.chrM.reverse.bam.partially_cleaved_long.bam.readslist
- output mitoBAM depth file for current class: /lustre/bio_running/GTEx_Long_Project/analysis/GTH2/GTH2.genome.chrM.reverse.bam.partially_cleaved_long.bam.depth.txt
10969
  10969 16	chrM
16569 /lustre/bio_running/GTEx_Long_Project/analysis/GTH2/GTH2.genome.chrM.reverse.bam.partially_cleaved_long.bam.depth.txt


######################################################################################################
######################################################################################################
######################################################################################################
GTD2 Total Processed samples: 12/73
Shape of df-reads for current sample: (18627, 16)
Unique number of reads: 18627

,Chr,ChrStart,ChrEnd,read_id,MAPQ,strand,read_length,alignment_length,reference_length,polyA_length,sample,overlapping_gene_ids,overlapping_gene_names,n_overlapping_gene_ids,chrM_primary_class,new_class
19339,chrM,189,397,2101b287-b8b7-42af-aba2-95da90dc1e44,60,-,229.0,210,208,70,GTD2,7S,7S,1,complete_gene,fully_cleaved
19340,chrM,189,397,723ccd8e-b508-443c-8643-51cc6ab0df1a,60,-,230.0,205,208,23,GTD2,7S,7S,1,complete_gene,fully_cleaved

CHECKING number of reads:
Starting mito-BAM filepath: /lustre/bio_running/GTEx_Long_Project/analysis/GTD2/GTD2.genome.chrM.reverse.bam

#####
Elaborating class: fully_cleaved

sample  new_class
GTD2    fully_cleaved    1445
dtype: int64

(1445, 16)
Number of reads for current class: 1445
- output mitoBAM for current class: /lustre/bio_running/GTEx_Long_Project/analysis/GTD2/GTD2.genome.chrM.reverse.bam.fully_cleaved.bam
- output mitoBAM readslist for current class: /lustre/bio_running/GTEx_Long_Project/analysis/GTD2/GTD2.genome.chrM.reverse.bam.fully_cleaved.bam.readslist
- output mitoBAM depth file for current class: /lustre/bio_running/GTEx_Long_Project/analysis/GTD2/GTD2.genome.chrM.reverse.bam.fully_cleaved.bam.depth.txt
1445
   1445 16	chrM
16569 /lustre/bio_running/GTEx_Long_Project/analysis/GTD2/GTD2.genome.chrM.reverse.bam.fully_cleaved.bam.depth.txt

#####
Elaborating class: partially_cleaved_short

sample  new_class
GTD2    partially_cleaved_short    11691
dtype: int64

(11691, 16)
Number of reads for current class: 11691
- output mitoBAM for current class: /lustre/bio_running/GTEx_Long_Project/analysis/GTD2/GTD2.genome.chrM.reverse.bam.partially_cleaved_short.bam
- output mitoBAM readslist for current class: /lustre/bio_running/GTEx_Long_Project/analysis/GTD2/GTD2.genome.chrM.reverse.bam.partially_cleaved_short.bam.readslist
- output mitoBAM depth file for current class: /lustre/bio_running/GTEx_Long_Project/analysis/GTD2/GTD2.genome.chrM.reverse.bam.partially_cleaved_short.bam.depth.txt
11691
  11691 16	chrM
16569 /lustre/bio_running/GTEx_Long_Project/analysis/GTD2/GTD2.genome.chrM.reverse.bam.partially_cleaved_short.bam.depth.txt

#####
Elaborating class: partially_cleaved_long

sample  new_class
GTD2    partially_cleaved_long    5491
dtype: int64

(5491, 16)
Number of reads for current class: 5491
- output mitoBAM for current class: /lustre/bio_running/GTEx_Long_Project/analysis/GTD2/GTD2.genome.chrM.reverse.bam.partially_cleaved_long.bam
- output mitoBAM readslist for current class: /lustre/bio_running/GTEx_Long_Project/analysis/GTD2/GTD2.genome.chrM.reverse.bam.partially_cleaved_long.bam.readslist
- output mitoBAM depth file for current class: /lustre/bio_running/GTEx_Long_Project/analysis/GTD2/GTD2.genome.chrM.reverse.bam.partially_cleaved_long.bam.depth.txt
5491
   5491 16	chrM
16569 /lustre/bio_running/GTEx_Long_Project/analysis/GTD2/GTD2.genome.chrM.reverse.bam.partially_cleaved_long.bam.depth.txt


######################################################################################################
######################################################################################################
######################################################################################################
GTD7 Total Processed samples: 13/73
Shape of df-reads for current sample: (18070, 16)
Unique number of reads: 18070

,Chr,ChrStart,ChrEnd,read_id,MAPQ,strand,read_length,alignment_length,reference_length,polyA_length,sample,overlapping_gene_ids,overlapping_gene_names,n_overlapping_gene_ids,chrM_primary_class,new_class
25185,chrM,189,397,4ef25ff3-6df7-4ec3-8f63-824a8b1e5ad7,60,-,219.0,209,208,26,GTD7,7S,7S,1,complete_gene,fully_cleaved
25186,chrM,189,388,19011e8e-99fd-484a-adbd-40ceb6f60a18,60,-,216.0,199,199,41,GTD7,7S,7S,1,complete_gene,fully_cleaved

CHECKING number of reads:
Starting mito-BAM filepath: /lustre/bio_running/GTEx_Long_Project/analysis/GTD7/GTD7.genome.chrM.reverse.bam

#####
Elaborating class: fully_cleaved

sample  new_class
GTD7    fully_cleaved    1391
dtype: int64

(1391, 16)
Number of reads for current class: 1391
- output mitoBAM for current class: /lustre/bio_running/GTEx_Long_Project/analysis/GTD7/GTD7.genome.chrM.reverse.bam.fully_cleaved.bam
- output mitoBAM readslist for current class: /lustre/bio_running/GTEx_Long_Project/analysis/GTD7/GTD7.genome.chrM.reverse.bam.fully_cleaved.bam.readslist
- output mitoBAM depth file for current class: /lustre/bio_running/GTEx_Long_Project/analysis/GTD7/GTD7.genome.chrM.reverse.bam.fully_cleaved.bam.depth.txt
1391
   1391 16	chrM
16569 /lustre/bio_running/GTEx_Long_Project/analysis/GTD7/GTD7.genome.chrM.reverse.bam.fully_cleaved.bam.depth.txt

#####
Elaborating class: partially_cleaved_short

sample  new_class
GTD7    partially_cleaved_short    8123
dtype: int64

(8123, 16)
Number of reads for current class: 8123
- output mitoBAM for current class: /lustre/bio_running/GTEx_Long_Project/analysis/GTD7/GTD7.genome.chrM.reverse.bam.partially_cleaved_short.bam
- output mitoBAM readslist for current class: /lustre/bio_running/GTEx_Long_Project/analysis/GTD7/GTD7.genome.chrM.reverse.bam.partially_cleaved_short.bam.readslist
- output mitoBAM depth file for current class: /lustre/bio_running/GTEx_Long_Project/analysis/GTD7/GTD7.genome.chrM.reverse.bam.partially_cleaved_short.bam.depth.txt
8123
   8123 16	chrM
16569 /lustre/bio_running/GTEx_Long_Project/analysis/GTD7/GTD7.genome.chrM.reverse.bam.partially_cleaved_short.bam.depth.txt

#####
Elaborating class: partially_cleaved_long

sample  new_class
GTD7    partially_cleaved_long    8556
dtype: int64

(8556, 16)
Number of reads for current class: 8556
- output mitoBAM for current class: /lustre/bio_running/GTEx_Long_Project/analysis/GTD7/GTD7.genome.chrM.reverse.bam.partially_cleaved_long.bam
- output mitoBAM readslist for current class: /lustre/bio_running/GTEx_Long_Project/analysis/GTD7/GTD7.genome.chrM.reverse.bam.partially_cleaved_long.bam.readslist
- output mitoBAM depth file for current class: /lustre/bio_running/GTEx_Long_Project/analysis/GTD7/GTD7.genome.chrM.reverse.bam.partially_cleaved_long.bam.depth.txt
8556
   8556 16	chrM
16569 /lustre/bio_running/GTEx_Long_Project/analysis/GTD7/GTD7.genome.chrM.reverse.bam.partially_cleaved_long.bam.depth.txt


######################################################################################################
######################################################################################################
######################################################################################################
GTH6 Total Processed samples: 14/73
Shape of df-reads for current sample: (16893, 16)
Unique number of reads: 16893

,Chr,ChrStart,ChrEnd,read_id,MAPQ,strand,read_length,alignment_length,reference_length,polyA_length,sample,overlapping_gene_ids,overlapping_gene_names,n_overlapping_gene_ids,chrM_primary_class,new_class
50740,chrM,189,388,781a46ec-ae99-418f-8344-3f2a251d747e,60,-,211.0,199,199,32,GTH6,7S,7S,1,complete_gene,fully_cleaved
50741,chrM,189,394,f82c6ffb-fe84-4236-a2e9-a669eb1c6c46,60,-,216.0,206,205,22,GTH6,7S,7S,1,complete_gene,fully_cleaved

CHECKING number of reads:
Starting mito-BAM filepath: /lustre/bio_running/GTEx_Long_Project/analysis/GTH6/GTH6.genome.chrM.reverse.bam

#####
Elaborating class: fully_cleaved

sample  new_class
GTH6    fully_cleaved    684
dtype: int64

(684, 16)
Number of reads for current class: 684
- output mitoBAM for current class: /lustre/bio_running/GTEx_Long_Project/analysis/GTH6/GTH6.genome.chrM.reverse.bam.fully_cleaved.bam
- output mitoBAM readslist for current class: /lustre/bio_running/GTEx_Long_Project/analysis/GTH6/GTH6.genome.chrM.reverse.bam.fully_cleaved.bam.readslist
- output mitoBAM depth file for current class: /lustre/bio_running/GTEx_Long_Project/analysis/GTH6/GTH6.genome.chrM.reverse.bam.fully_cleaved.bam.depth.txt
684
    684 16	chrM
16569 /lustre/bio_running/GTEx_Long_Project/analysis/GTH6/GTH6.genome.chrM.reverse.bam.fully_cleaved.bam.depth.txt

#####
Elaborating class: partially_cleaved_short

sample  new_class
GTH6    partially_cleaved_short    8925
dtype: int64

(8925, 16)
Number of reads for current class: 8925
- output mitoBAM for current class: /lustre/bio_running/GTEx_Long_Project/analysis/GTH6/GTH6.genome.chrM.reverse.bam.partially_cleaved_short.bam
- output mitoBAM readslist for current class: /lustre/bio_running/GTEx_Long_Project/analysis/GTH6/GTH6.genome.chrM.reverse.bam.partially_cleaved_short.bam.readslist
- output mitoBAM depth file for current class: /lustre/bio_running/GTEx_Long_Project/analysis/GTH6/GTH6.genome.chrM.reverse.bam.partially_cleaved_short.bam.depth.txt
8925
   8925 16	chrM
16569 /lustre/bio_running/GTEx_Long_Project/analysis/GTH6/GTH6.genome.chrM.reverse.bam.partially_cleaved_short.bam.depth.txt

#####
Elaborating class: partially_cleaved_long

sample  new_class
GTH6    partially_cleaved_long    7284
dtype: int64

(7284, 16)
Number of reads for current class: 7284
- output mitoBAM for current class: /lustre/bio_running/GTEx_Long_Project/analysis/GTH6/GTH6.genome.chrM.reverse.bam.partially_cleaved_long.bam
- output mitoBAM readslist for current class: /lustre/bio_running/GTEx_Long_Project/analysis/GTH6/GTH6.genome.chrM.reverse.bam.partially_cleaved_long.bam.readslist
- output mitoBAM depth file for current class: /lustre/bio_running/GTEx_Long_Project/analysis/GTH6/GTH6.genome.chrM.reverse.bam.partially_cleaved_long.bam.depth.txt
7284
   7284 16	chrM
16569 /lustre/bio_running/GTEx_Long_Project/analysis/GTH6/GTH6.genome.chrM.reverse.bam.partially_cleaved_long.bam.depth.txt


######################################################################################################
######################################################################################################
######################################################################################################
GTH7 Total Processed samples: 15/73
Shape of df-reads for current sample: (15824, 16)
Unique number of reads: 15824

,Chr,ChrStart,ChrEnd,read_id,MAPQ,strand,read_length,alignment_length,reference_length,polyA_length,sample,overlapping_gene_ids,overlapping_gene_names,n_overlapping_gene_ids,chrM_primary_class,new_class
51424,chrM,189,397,dee37395-b6df-4234-8682-6586ca0c8263,60,-,242.0,213,208,25,GTH7,7S,7S,1,complete_gene,fully_cleaved
51425,chrM,189,397,7838f76a-10f4-4414-aeb0-c06d266ed863,60,-,238.0,209,208,20,GTH7,7S,7S,1,complete_gene,fully_cleaved

CHECKING number of reads:
Starting mito-BAM filepath: /lustre/bio_running/GTEx_Long_Project/analysis/GTH7/GTH7.genome.chrM.reverse.bam

#####
Elaborating class: fully_cleaved

sample  new_class
GTH7    fully_cleaved    733
dtype: int64

(733, 16)
Number of reads for current class: 733
- output mitoBAM for current class: /lustre/bio_running/GTEx_Long_Project/analysis/GTH7/GTH7.genome.chrM.reverse.bam.fully_cleaved.bam
- output mitoBAM readslist for current class: /lustre/bio_running/GTEx_Long_Project/analysis/GTH7/GTH7.genome.chrM.reverse.bam.fully_cleaved.bam.readslist
- output mitoBAM depth file for current class: /lustre/bio_running/GTEx_Long_Project/analysis/GTH7/GTH7.genome.chrM.reverse.bam.fully_cleaved.bam.depth.txt
733
    733 16	chrM
16569 /lustre/bio_running/GTEx_Long_Project/analysis/GTH7/GTH7.genome.chrM.reverse.bam.fully_cleaved.bam.depth.txt

#####
Elaborating class: partially_cleaved_short

sample  new_class
GTH7    partially_cleaved_short    8351
dtype: int64

(8351, 16)
Number of reads for current class: 8351
- output mitoBAM for current class: /lustre/bio_running/GTEx_Long_Project/analysis/GTH7/GTH7.genome.chrM.reverse.bam.partially_cleaved_short.bam
- output mitoBAM readslist for current class: /lustre/bio_running/GTEx_Long_Project/analysis/GTH7/GTH7.genome.chrM.reverse.bam.partially_cleaved_short.bam.readslist
- output mitoBAM depth file for current class: /lustre/bio_running/GTEx_Long_Project/analysis/GTH7/GTH7.genome.chrM.reverse.bam.partially_cleaved_short.bam.depth.txt
8351
   8351 16	chrM
16569 /lustre/bio_running/GTEx_Long_Project/analysis/GTH7/GTH7.genome.chrM.reverse.bam.partially_cleaved_short.bam.depth.txt

#####
Elaborating class: partially_cleaved_long

sample  new_class
GTH7    partially_cleaved_long    6740
dtype: int64

(6740, 16)
Number of reads for current class: 6740
- output mitoBAM for current class: /lustre/bio_running/GTEx_Long_Project/analysis/GTH7/GTH7.genome.chrM.reverse.bam.partially_cleaved_long.bam
- output mitoBAM readslist for current class: /lustre/bio_running/GTEx_Long_Project/analysis/GTH7/GTH7.genome.chrM.reverse.bam.partially_cleaved_long.bam.readslist
- output mitoBAM depth file for current class: /lustre/bio_running/GTEx_Long_Project/analysis/GTH7/GTH7.genome.chrM.reverse.bam.partially_cleaved_long.bam.depth.txt
6740
   6740 16	chrM
16569 /lustre/bio_running/GTEx_Long_Project/analysis/GTH7/GTH7.genome.chrM.reverse.bam.partially_cleaved_long.bam.depth.txt


######################################################################################################
######################################################################################################
######################################################################################################
GTB4 Total Processed samples: 16/73
Shape of df-reads for current sample: (15572, 16)
Unique number of reads: 15572

,Chr,ChrStart,ChrEnd,read_id,MAPQ,strand,read_length,alignment_length,reference_length,polyA_length,sample,overlapping_gene_ids,overlapping_gene_names,n_overlapping_gene_ids,chrM_primary_class,new_class
9088,chrM,189,395,6777b9a7-482a-49db-88a3-2a1e11ff6aba,60,-,221.0,206,206,18,GTB4,7S,7S,1,complete_gene,fully_cleaved
9089,chrM,189,398,675ce95a-9e9c-4ff2-ba87-79db5938b8bc,60,-,224.0,203,209,28,GTB4,7S,7S,1,complete_gene,fully_cleaved

CHECKING number of reads:
Starting mito-BAM filepath: /lustre/bio_running/GTEx_Long_Project/analysis/GTB4/GTB4.genome.chrM.reverse.bam

#####
Elaborating class: fully_cleaved

sample  new_class
GTB4    fully_cleaved    1354
dtype: int64

(1354, 16)
Number of reads for current class: 1354
- output mitoBAM for current class: /lustre/bio_running/GTEx_Long_Project/analysis/GTB4/GTB4.genome.chrM.reverse.bam.fully_cleaved.bam
- output mitoBAM readslist for current class: /lustre/bio_running/GTEx_Long_Project/analysis/GTB4/GTB4.genome.chrM.reverse.bam.fully_cleaved.bam.readslist
- output mitoBAM depth file for current class: /lustre/bio_running/GTEx_Long_Project/analysis/GTB4/GTB4.genome.chrM.reverse.bam.fully_cleaved.bam.depth.txt
1354
   1354 16	chrM
16569 /lustre/bio_running/GTEx_Long_Project/analysis/GTB4/GTB4.genome.chrM.reverse.bam.fully_cleaved.bam.depth.txt

#####
Elaborating class: partially_cleaved_short

sample  new_class
GTB4    partially_cleaved_short    6622
dtype: int64

(6622, 16)
Number of reads for current class: 6622
- output mitoBAM for current class: /lustre/bio_running/GTEx_Long_Project/analysis/GTB4/GTB4.genome.chrM.reverse.bam.partially_cleaved_short.bam
- output mitoBAM readslist for current class: /lustre/bio_running/GTEx_Long_Project/analysis/GTB4/GTB4.genome.chrM.reverse.bam.partially_cleaved_short.bam.readslist
- output mitoBAM depth file for current class: /lustre/bio_running/GTEx_Long_Project/analysis/GTB4/GTB4.genome.chrM.reverse.bam.partially_cleaved_short.bam.depth.txt
6622
   6622 16	chrM
16569 /lustre/bio_running/GTEx_Long_Project/analysis/GTB4/GTB4.genome.chrM.reverse.bam.partially_cleaved_short.bam.depth.txt

#####
Elaborating class: partially_cleaved_long

sample  new_class
GTB4    partially_cleaved_long    7596
dtype: int64

(7596, 16)
Number of reads for current class: 7596
- output mitoBAM for current class: /lustre/bio_running/GTEx_Long_Project/analysis/GTB4/GTB4.genome.chrM.reverse.bam.partially_cleaved_long.bam
- output mitoBAM readslist for current class: /lustre/bio_running/GTEx_Long_Project/analysis/GTB4/GTB4.genome.chrM.reverse.bam.partially_cleaved_long.bam.readslist
- output mitoBAM depth file for current class: /lustre/bio_running/GTEx_Long_Project/analysis/GTB4/GTB4.genome.chrM.reverse.bam.partially_cleaved_long.bam.depth.txt
7596
   7596 16	chrM
16569 /lustre/bio_running/GTEx_Long_Project/analysis/GTB4/GTB4.genome.chrM.reverse.bam.partially_cleaved_long.bam.depth.txt


######################################################################################################
######################################################################################################
######################################################################################################
GTC5 Total Processed samples: 17/73
Shape of df-reads for current sample: (15047, 16)
Unique number of reads: 15047

,Chr,ChrStart,ChrEnd,read_id,MAPQ,strand,read_length,alignment_length,reference_length,polyA_length,sample,overlapping_gene_ids,overlapping_gene_names,n_overlapping_gene_ids,chrM_primary_class,new_class
13898,chrM,189,397,be3cc99a-05e3-4a13-b12f-6201e7f2e365,60,-,246.0,208,208,35,GTC5,7S,7S,1,complete_gene,fully_cleaved
13899,chrM,189,397,9565833f-d4c8-47cc-ae93-73399c1c08f8,60,-,216.0,209,208,19,GTC5,7S,7S,1,complete_gene,fully_cleaved

CHECKING number of reads:
Starting mito-BAM filepath: /lustre/bio_running/GTEx_Long_Project/analysis/GTC5/GTC5.genome.chrM.reverse.bam

#####
Elaborating class: fully_cleaved

sample  new_class
GTC5    fully_cleaved    658
dtype: int64

(658, 16)
Number of reads for current class: 658
- output mitoBAM for current class: /lustre/bio_running/GTEx_Long_Project/analysis/GTC5/GTC5.genome.chrM.reverse.bam.fully_cleaved.bam
- output mitoBAM readslist for current class: /lustre/bio_running/GTEx_Long_Project/analysis/GTC5/GTC5.genome.chrM.reverse.bam.fully_cleaved.bam.readslist
- output mitoBAM depth file for current class: /lustre/bio_running/GTEx_Long_Project/analysis/GTC5/GTC5.genome.chrM.reverse.bam.fully_cleaved.bam.depth.txt
658
    658 16	chrM
16569 /lustre/bio_running/GTEx_Long_Project/analysis/GTC5/GTC5.genome.chrM.reverse.bam.fully_cleaved.bam.depth.txt

#####
Elaborating class: partially_cleaved_short

sample  new_class
GTC5    partially_cleaved_short    5370
dtype: int64

(5370, 16)
Number of reads for current class: 5370
- output mitoBAM for current class: /lustre/bio_running/GTEx_Long_Project/analysis/GTC5/GTC5.genome.chrM.reverse.bam.partially_cleaved_short.bam
- output mitoBAM readslist for current class: /lustre/bio_running/GTEx_Long_Project/analysis/GTC5/GTC5.genome.chrM.reverse.bam.partially_cleaved_short.bam.readslist
- output mitoBAM depth file for current class: /lustre/bio_running/GTEx_Long_Project/analysis/GTC5/GTC5.genome.chrM.reverse.bam.partially_cleaved_short.bam.depth.txt
5370
   5370 16	chrM
16569 /lustre/bio_running/GTEx_Long_Project/analysis/GTC5/GTC5.genome.chrM.reverse.bam.partially_cleaved_short.bam.depth.txt

#####
Elaborating class: partially_cleaved_long

sample  new_class
GTC5    partially_cleaved_long    9019
dtype: int64

(9019, 16)
Number of reads for current class: 9019
- output mitoBAM for current class: /lustre/bio_running/GTEx_Long_Project/analysis/GTC5/GTC5.genome.chrM.reverse.bam.partially_cleaved_long.bam
- output mitoBAM readslist for current class: /lustre/bio_running/GTEx_Long_Project/analysis/GTC5/GTC5.genome.chrM.reverse.bam.partially_cleaved_long.bam.readslist
- output mitoBAM depth file for current class: /lustre/bio_running/GTEx_Long_Project/analysis/GTC5/GTC5.genome.chrM.reverse.bam.partially_cleaved_long.bam.depth.txt
9019
   9019 16	chrM
16569 /lustre/bio_running/GTEx_Long_Project/analysis/GTC5/GTC5.genome.chrM.reverse.bam.partially_cleaved_long.bam.depth.txt


######################################################################################################
######################################################################################################
######################################################################################################
GTA2 Total Processed samples: 18/73
Shape of df-reads for current sample: (14812, 16)
Unique number of reads: 14812

,Chr,ChrStart,ChrEnd,read_id,MAPQ,strand,read_length,alignment_length,reference_length,polyA_length,sample,overlapping_gene_ids,overlapping_gene_names,n_overlapping_gene_ids,chrM_primary_class,new_class
1722,chrM,189,397,4c87e690-ea7e-4f7b-8e34-3f2a14c358c4,60,-,254.0,219,208,43,GTA2,7S,7S,1,complete_gene,fully_cleaved
1723,chrM,189,397,c96a40b7-1dce-43ab-8cfa-de81563e3dc4,60,-,219.0,210,208,37,GTA2,7S,7S,1,complete_gene,fully_cleaved

CHECKING number of reads:
Starting mito-BAM filepath: /lustre/bio_running/GTEx_Long_Project/analysis/GTA2/GTA2.genome.chrM.reverse.bam

#####
Elaborating class: fully_cleaved

sample  new_class
GTA2    fully_cleaved    1042
dtype: int64

(1042, 16)
Number of reads for current class: 1042
- output mitoBAM for current class: /lustre/bio_running/GTEx_Long_Project/analysis/GTA2/GTA2.genome.chrM.reverse.bam.fully_cleaved.bam
- output mitoBAM readslist for current class: /lustre/bio_running/GTEx_Long_Project/analysis/GTA2/GTA2.genome.chrM.reverse.bam.fully_cleaved.bam.readslist
- output mitoBAM depth file for current class: /lustre/bio_running/GTEx_Long_Project/analysis/GTA2/GTA2.genome.chrM.reverse.bam.fully_cleaved.bam.depth.txt
1042
   1042 16	chrM
16569 /lustre/bio_running/GTEx_Long_Project/analysis/GTA2/GTA2.genome.chrM.reverse.bam.fully_cleaved.bam.depth.txt

#####
Elaborating class: partially_cleaved_short

sample  new_class
GTA2    partially_cleaved_short    5272
dtype: int64

(5272, 16)
Number of reads for current class: 5272
- output mitoBAM for current class: /lustre/bio_running/GTEx_Long_Project/analysis/GTA2/GTA2.genome.chrM.reverse.bam.partially_cleaved_short.bam
- output mitoBAM readslist for current class: /lustre/bio_running/GTEx_Long_Project/analysis/GTA2/GTA2.genome.chrM.reverse.bam.partially_cleaved_short.bam.readslist
- output mitoBAM depth file for current class: /lustre/bio_running/GTEx_Long_Project/analysis/GTA2/GTA2.genome.chrM.reverse.bam.partially_cleaved_short.bam.depth.txt
5272
   5272 16	chrM
16569 /lustre/bio_running/GTEx_Long_Project/analysis/GTA2/GTA2.genome.chrM.reverse.bam.partially_cleaved_short.bam.depth.txt

#####
Elaborating class: partially_cleaved_long

sample  new_class
GTA2    partially_cleaved_long    8498
dtype: int64

(8498, 16)
Number of reads for current class: 8498
- output mitoBAM for current class: /lustre/bio_running/GTEx_Long_Project/analysis/GTA2/GTA2.genome.chrM.reverse.bam.partially_cleaved_long.bam
- output mitoBAM readslist for current class: /lustre/bio_running/GTEx_Long_Project/analysis/GTA2/GTA2.genome.chrM.reverse.bam.partially_cleaved_long.bam.readslist
- output mitoBAM depth file for current class: /lustre/bio_running/GTEx_Long_Project/analysis/GTA2/GTA2.genome.chrM.reverse.bam.partially_cleaved_long.bam.depth.txt
8498
   8498 16	chrM
16569 /lustre/bio_running/GTEx_Long_Project/analysis/GTA2/GTA2.genome.chrM.reverse.bam.partially_cleaved_long.bam.depth.txt


######################################################################################################
######################################################################################################
######################################################################################################
GTD8 Total Processed samples: 19/73
Shape of df-reads for current sample: (13324, 16)
Unique number of reads: 13324

,Chr,ChrStart,ChrEnd,read_id,MAPQ,strand,read_length,alignment_length,reference_length,polyA_length,sample,overlapping_gene_ids,overlapping_gene_names,n_overlapping_gene_ids,chrM_primary_class,new_class
26576,chrM,189,396,8c253ad5-628c-4cba-abe9-4a365b1fc642,60,-,217.0,208,207,34,GTD8,7S,7S,1,complete_gene,fully_cleaved
26577,chrM,189,400,f6baadc1-cb6b-46b1-b419-30801a11cf8e,60,-,243.0,214,211,28,GTD8,7S,7S,1,complete_gene,fully_cleaved

CHECKING number of reads:
Starting mito-BAM filepath: /lustre/bio_running/GTEx_Long_Project/analysis/GTD8/GTD8.genome.chrM.reverse.bam

#####
Elaborating class: fully_cleaved

sample  new_class
GTD8    fully_cleaved    516
dtype: int64

(516, 16)
Number of reads for current class: 516
- output mitoBAM for current class: /lustre/bio_running/GTEx_Long_Project/analysis/GTD8/GTD8.genome.chrM.reverse.bam.fully_cleaved.bam
- output mitoBAM readslist for current class: /lustre/bio_running/GTEx_Long_Project/analysis/GTD8/GTD8.genome.chrM.reverse.bam.fully_cleaved.bam.readslist
- output mitoBAM depth file for current class: /lustre/bio_running/GTEx_Long_Project/analysis/GTD8/GTD8.genome.chrM.reverse.bam.fully_cleaved.bam.depth.txt
516
    516 16	chrM
16569 /lustre/bio_running/GTEx_Long_Project/analysis/GTD8/GTD8.genome.chrM.reverse.bam.fully_cleaved.bam.depth.txt

#####
Elaborating class: partially_cleaved_short

sample  new_class
GTD8    partially_cleaved_short    7005
dtype: int64

(7005, 16)
Number of reads for current class: 7005
- output mitoBAM for current class: /lustre/bio_running/GTEx_Long_Project/analysis/GTD8/GTD8.genome.chrM.reverse.bam.partially_cleaved_short.bam
- output mitoBAM readslist for current class: /lustre/bio_running/GTEx_Long_Project/analysis/GTD8/GTD8.genome.chrM.reverse.bam.partially_cleaved_short.bam.readslist
- output mitoBAM depth file for current class: /lustre/bio_running/GTEx_Long_Project/analysis/GTD8/GTD8.genome.chrM.reverse.bam.partially_cleaved_short.bam.depth.txt
7005
   7005 16	chrM
16569 /lustre/bio_running/GTEx_Long_Project/analysis/GTD8/GTD8.genome.chrM.reverse.bam.partially_cleaved_short.bam.depth.txt

#####
Elaborating class: partially_cleaved_long

sample  new_class
GTD8    partially_cleaved_long    5803
dtype: int64

(5803, 16)
Number of reads for current class: 5803
- output mitoBAM for current class: /lustre/bio_running/GTEx_Long_Project/analysis/GTD8/GTD8.genome.chrM.reverse.bam.partially_cleaved_long.bam
- output mitoBAM readslist for current class: /lustre/bio_running/GTEx_Long_Project/analysis/GTD8/GTD8.genome.chrM.reverse.bam.partially_cleaved_long.bam.readslist
- output mitoBAM depth file for current class: /lustre/bio_running/GTEx_Long_Project/analysis/GTD8/GTD8.genome.chrM.reverse.bam.partially_cleaved_long.bam.depth.txt
5803
   5803 16	chrM
16569 /lustre/bio_running/GTEx_Long_Project/analysis/GTD8/GTD8.genome.chrM.reverse.bam.partially_cleaved_long.bam.depth.txt


######################################################################################################
######################################################################################################
######################################################################################################
GTF2 Total Processed samples: 20/73
Shape of df-reads for current sample: (13320, 16)
Unique number of reads: 13320

,Chr,ChrStart,ChrEnd,read_id,MAPQ,strand,read_length,alignment_length,reference_length,polyA_length,sample,overlapping_gene_ids,overlapping_gene_names,n_overlapping_gene_ids,chrM_primary_class,new_class
33251,chrM,189,392,c1b59b9b-7e68-40f6-b116-0f1dc39a572e,60,-,213.0,203,203,36,GTF2,7S,7S,1,complete_gene,fully_cleaved
33252,chrM,189,397,b60d23d9-5362-4a87-9399-791c1a63e56f,60,-,219.0,211,208,34,GTF2,7S,7S,1,complete_gene,fully_cleaved

CHECKING number of reads:
Starting mito-BAM filepath: /lustre/bio_running/GTEx_Long_Project/analysis/GTF2/GTF2.genome.chrM.reverse.bam

#####
Elaborating class: fully_cleaved

sample  new_class
GTF2    fully_cleaved    1061
dtype: int64

(1061, 16)
Number of reads for current class: 1061
- output mitoBAM for current class: /lustre/bio_running/GTEx_Long_Project/analysis/GTF2/GTF2.genome.chrM.reverse.bam.fully_cleaved.bam
- output mitoBAM readslist for current class: /lustre/bio_running/GTEx_Long_Project/analysis/GTF2/GTF2.genome.chrM.reverse.bam.fully_cleaved.bam.readslist
- output mitoBAM depth file for current class: /lustre/bio_running/GTEx_Long_Project/analysis/GTF2/GTF2.genome.chrM.reverse.bam.fully_cleaved.bam.depth.txt
1061
   1061 16	chrM
16569 /lustre/bio_running/GTEx_Long_Project/analysis/GTF2/GTF2.genome.chrM.reverse.bam.fully_cleaved.bam.depth.txt

#####
Elaborating class: partially_cleaved_short

sample  new_class
GTF2    partially_cleaved_short    6680
dtype: int64

(6680, 16)
Number of reads for current class: 6680
- output mitoBAM for current class: /lustre/bio_running/GTEx_Long_Project/analysis/GTF2/GTF2.genome.chrM.reverse.bam.partially_cleaved_short.bam
- output mitoBAM readslist for current class: /lustre/bio_running/GTEx_Long_Project/analysis/GTF2/GTF2.genome.chrM.reverse.bam.partially_cleaved_short.bam.readslist
- output mitoBAM depth file for current class: /lustre/bio_running/GTEx_Long_Project/analysis/GTF2/GTF2.genome.chrM.reverse.bam.partially_cleaved_short.bam.depth.txt
6680
   6680 16	chrM
16569 /lustre/bio_running/GTEx_Long_Project/analysis/GTF2/GTF2.genome.chrM.reverse.bam.partially_cleaved_short.bam.depth.txt

#####
Elaborating class: partially_cleaved_long

sample  new_class
GTF2    partially_cleaved_long    5579
dtype: int64

(5579, 16)
Number of reads for current class: 5579
- output mitoBAM for current class: /lustre/bio_running/GTEx_Long_Project/analysis/GTF2/GTF2.genome.chrM.reverse.bam.partially_cleaved_long.bam
- output mitoBAM readslist for current class: /lustre/bio_running/GTEx_Long_Project/analysis/GTF2/GTF2.genome.chrM.reverse.bam.partially_cleaved_long.bam.readslist
- output mitoBAM depth file for current class: /lustre/bio_running/GTEx_Long_Project/analysis/GTF2/GTF2.genome.chrM.reverse.bam.partially_cleaved_long.bam.depth.txt
5579
   5579 16	chrM
16569 /lustre/bio_running/GTEx_Long_Project/analysis/GTF2/GTF2.genome.chrM.reverse.bam.partially_cleaved_long.bam.depth.txt


######################################################################################################
######################################################################################################
######################################################################################################
GTD4 Total Processed samples: 21/73
Shape of df-reads for current sample: (12983, 16)
Unique number of reads: 12983

,Chr,ChrStart,ChrEnd,read_id,MAPQ,strand,read_length,alignment_length,reference_length,polyA_length,sample,overlapping_gene_ids,overlapping_gene_names,n_overlapping_gene_ids,chrM_primary_class,new_class
20853,chrM,189,397,ea414628-6bd4-4843-9e51-77a67231f66c,60,-,213.0,209,208,27,GTD4,7S,7S,1,complete_gene,fully_cleaved
20854,chrM,189,397,a11843de-3b5f-463d-8099-8d4908d1c5e5,60,-,210.0,207,208,44,GTD4,7S,7S,1,complete_gene,fully_cleaved

CHECKING number of reads:
Starting mito-BAM filepath: /lustre/bio_running/GTEx_Long_Project/analysis/GTD4/GTD4.genome.chrM.reverse.bam

#####
Elaborating class: fully_cleaved

sample  new_class
GTD4    fully_cleaved    1924
dtype: int64

(1924, 16)
Number of reads for current class: 1924
- output mitoBAM for current class: /lustre/bio_running/GTEx_Long_Project/analysis/GTD4/GTD4.genome.chrM.reverse.bam.fully_cleaved.bam
- output mitoBAM readslist for current class: /lustre/bio_running/GTEx_Long_Project/analysis/GTD4/GTD4.genome.chrM.reverse.bam.fully_cleaved.bam.readslist
- output mitoBAM depth file for current class: /lustre/bio_running/GTEx_Long_Project/analysis/GTD4/GTD4.genome.chrM.reverse.bam.fully_cleaved.bam.depth.txt
1924
   1924 16	chrM
16569 /lustre/bio_running/GTEx_Long_Project/analysis/GTD4/GTD4.genome.chrM.reverse.bam.fully_cleaved.bam.depth.txt

#####
Elaborating class: partially_cleaved_short

sample  new_class
GTD4    partially_cleaved_short    5505
dtype: int64

(5505, 16)
Number of reads for current class: 5505
- output mitoBAM for current class: /lustre/bio_running/GTEx_Long_Project/analysis/GTD4/GTD4.genome.chrM.reverse.bam.partially_cleaved_short.bam
- output mitoBAM readslist for current class: /lustre/bio_running/GTEx_Long_Project/analysis/GTD4/GTD4.genome.chrM.reverse.bam.partially_cleaved_short.bam.readslist
- output mitoBAM depth file for current class: /lustre/bio_running/GTEx_Long_Project/analysis/GTD4/GTD4.genome.chrM.reverse.bam.partially_cleaved_short.bam.depth.txt
5505
   5505 16	chrM
16569 /lustre/bio_running/GTEx_Long_Project/analysis/GTD4/GTD4.genome.chrM.reverse.bam.partially_cleaved_short.bam.depth.txt

#####
Elaborating class: partially_cleaved_long

sample  new_class
GTD4    partially_cleaved_long    5554
dtype: int64

(5554, 16)
Number of reads for current class: 5554
- output mitoBAM for current class: /lustre/bio_running/GTEx_Long_Project/analysis/GTD4/GTD4.genome.chrM.reverse.bam.partially_cleaved_long.bam
- output mitoBAM readslist for current class: /lustre/bio_running/GTEx_Long_Project/analysis/GTD4/GTD4.genome.chrM.reverse.bam.partially_cleaved_long.bam.readslist
- output mitoBAM depth file for current class: /lustre/bio_running/GTEx_Long_Project/analysis/GTD4/GTD4.genome.chrM.reverse.bam.partially_cleaved_long.bam.depth.txt
5554
   5554 16	chrM
16569 /lustre/bio_running/GTEx_Long_Project/analysis/GTD4/GTD4.genome.chrM.reverse.bam.partially_cleaved_long.bam.depth.txt


######################################################################################################
######################################################################################################
######################################################################################################
GTG4 Total Processed samples: 22/73
Shape of df-reads for current sample: (11691, 16)
Unique number of reads: 11691

,Chr,ChrStart,ChrEnd,read_id,MAPQ,strand,read_length,alignment_length,reference_length,polyA_length,sample,overlapping_gene_ids,overlapping_gene_names,n_overlapping_gene_ids,chrM_primary_class,new_class
40023,chrM,189,397,7ee601bb-aeba-4e48-aa92-ef043e333d4f,60,-,228.0,215,208,0,GTG4,7S,7S,1,complete_gene,fully_cleaved
40024,chrM,189,397,c4a6d86f-f4a4-4f64-99a0-fefe2cd6bb18,60,-,226.0,209,208,30,GTG4,7S,7S,1,complete_gene,fully_cleaved

CHECKING number of reads:
Starting mito-BAM filepath: /lustre/bio_running/GTEx_Long_Project/analysis/GTG4/GTG4.genome.chrM.reverse.bam

#####
Elaborating class: fully_cleaved

sample  new_class
GTG4    fully_cleaved    345
dtype: int64

(345, 16)
Number of reads for current class: 345
- output mitoBAM for current class: /lustre/bio_running/GTEx_Long_Project/analysis/GTG4/GTG4.genome.chrM.reverse.bam.fully_cleaved.bam
- output mitoBAM readslist for current class: /lustre/bio_running/GTEx_Long_Project/analysis/GTG4/GTG4.genome.chrM.reverse.bam.fully_cleaved.bam.readslist
- output mitoBAM depth file for current class: /lustre/bio_running/GTEx_Long_Project/analysis/GTG4/GTG4.genome.chrM.reverse.bam.fully_cleaved.bam.depth.txt
345
    345 16	chrM
16569 /lustre/bio_running/GTEx_Long_Project/analysis/GTG4/GTG4.genome.chrM.reverse.bam.fully_cleaved.bam.depth.txt

#####
Elaborating class: partially_cleaved_short

sample  new_class
GTG4    partially_cleaved_short    6132
dtype: int64

(6132, 16)
Number of reads for current class: 6132
- output mitoBAM for current class: /lustre/bio_running/GTEx_Long_Project/analysis/GTG4/GTG4.genome.chrM.reverse.bam.partially_cleaved_short.bam
- output mitoBAM readslist for current class: /lustre/bio_running/GTEx_Long_Project/analysis/GTG4/GTG4.genome.chrM.reverse.bam.partially_cleaved_short.bam.readslist
- output mitoBAM depth file for current class: /lustre/bio_running/GTEx_Long_Project/analysis/GTG4/GTG4.genome.chrM.reverse.bam.partially_cleaved_short.bam.depth.txt
6132
   6132 16	chrM
16569 /lustre/bio_running/GTEx_Long_Project/analysis/GTG4/GTG4.genome.chrM.reverse.bam.partially_cleaved_short.bam.depth.txt

#####
Elaborating class: partially_cleaved_long

sample  new_class
GTG4    partially_cleaved_long    5214
dtype: int64

(5214, 16)
Number of reads for current class: 5214
- output mitoBAM for current class: /lustre/bio_running/GTEx_Long_Project/analysis/GTG4/GTG4.genome.chrM.reverse.bam.partially_cleaved_long.bam
- output mitoBAM readslist for current class: /lustre/bio_running/GTEx_Long_Project/analysis/GTG4/GTG4.genome.chrM.reverse.bam.partially_cleaved_long.bam.readslist
- output mitoBAM depth file for current class: /lustre/bio_running/GTEx_Long_Project/analysis/GTG4/GTG4.genome.chrM.reverse.bam.partially_cleaved_long.bam.depth.txt
5214
   5214 16	chrM
16569 /lustre/bio_running/GTEx_Long_Project/analysis/GTG4/GTG4.genome.chrM.reverse.bam.partially_cleaved_long.bam.depth.txt


######################################################################################################
######################################################################################################
######################################################################################################
GTF8 Total Processed samples: 23/73
Shape of df-reads for current sample: (11006, 16)
Unique number of reads: 11006

,Chr,ChrStart,ChrEnd,read_id,MAPQ,strand,read_length,alignment_length,reference_length,polyA_length,sample,overlapping_gene_ids,overlapping_gene_names,n_overlapping_gene_ids,chrM_primary_class,new_class
37828,chrM,189,397,af176047-1312-43ff-9d0f-e2e6d450890b,60,-,224.0,211,208,55,GTF8,7S,7S,1,complete_gene,fully_cleaved
37829,chrM,189,397,24d6eead-b7b8-443a-a76e-a8bcb427b6ba,60,-,224.0,209,208,37,GTF8,7S,7S,1,complete_gene,fully_cleaved

CHECKING number of reads:
Starting mito-BAM filepath: /lustre/bio_running/GTEx_Long_Project/analysis/GTF8/GTF8.genome.chrM.reverse.bam

#####
Elaborating class: fully_cleaved

sample  new_class
GTF8    fully_cleaved    593
dtype: int64

(593, 16)
Number of reads for current class: 593
- output mitoBAM for current class: /lustre/bio_running/GTEx_Long_Project/analysis/GTF8/GTF8.genome.chrM.reverse.bam.fully_cleaved.bam
- output mitoBAM readslist for current class: /lustre/bio_running/GTEx_Long_Project/analysis/GTF8/GTF8.genome.chrM.reverse.bam.fully_cleaved.bam.readslist
- output mitoBAM depth file for current class: /lustre/bio_running/GTEx_Long_Project/analysis/GTF8/GTF8.genome.chrM.reverse.bam.fully_cleaved.bam.depth.txt
593
    593 16	chrM
16569 /lustre/bio_running/GTEx_Long_Project/analysis/GTF8/GTF8.genome.chrM.reverse.bam.fully_cleaved.bam.depth.txt

#####
Elaborating class: partially_cleaved_short

sample  new_class
GTF8    partially_cleaved_short    5510
dtype: int64

(5510, 16)
Number of reads for current class: 5510
- output mitoBAM for current class: /lustre/bio_running/GTEx_Long_Project/analysis/GTF8/GTF8.genome.chrM.reverse.bam.partially_cleaved_short.bam
- output mitoBAM readslist for current class: /lustre/bio_running/GTEx_Long_Project/analysis/GTF8/GTF8.genome.chrM.reverse.bam.partially_cleaved_short.bam.readslist
- output mitoBAM depth file for current class: /lustre/bio_running/GTEx_Long_Project/analysis/GTF8/GTF8.genome.chrM.reverse.bam.partially_cleaved_short.bam.depth.txt
5510
   5510 16	chrM
16569 /lustre/bio_running/GTEx_Long_Project/analysis/GTF8/GTF8.genome.chrM.reverse.bam.partially_cleaved_short.bam.depth.txt

#####
Elaborating class: partially_cleaved_long

sample  new_class
GTF8    partially_cleaved_long    4903
dtype: int64

(4903, 16)
Number of reads for current class: 4903
- output mitoBAM for current class: /lustre/bio_running/GTEx_Long_Project/analysis/GTF8/GTF8.genome.chrM.reverse.bam.partially_cleaved_long.bam
- output mitoBAM readslist for current class: /lustre/bio_running/GTEx_Long_Project/analysis/GTF8/GTF8.genome.chrM.reverse.bam.partially_cleaved_long.bam.readslist
- output mitoBAM depth file for current class: /lustre/bio_running/GTEx_Long_Project/analysis/GTF8/GTF8.genome.chrM.reverse.bam.partially_cleaved_long.bam.depth.txt
4903
   4903 16	chrM
16569 /lustre/bio_running/GTEx_Long_Project/analysis/GTF8/GTF8.genome.chrM.reverse.bam.partially_cleaved_long.bam.depth.txt


######################################################################################################
######################################################################################################
######################################################################################################
GTH8 Total Processed samples: 24/73
Shape of df-reads for current sample: (10590, 16)
Unique number of reads: 10590

,Chr,ChrStart,ChrEnd,read_id,MAPQ,strand,read_length,alignment_length,reference_length,polyA_length,sample,overlapping_gene_ids,overlapping_gene_names,n_overlapping_gene_ids,chrM_primary_class,new_class
52157,chrM,189,397,3dbf2355-da15-4671-a01b-43ac1174c6ed,60,-,253.0,214,208,29,GTH8,7S,7S,1,complete_gene,fully_cleaved
52158,chrM,189,394,03449da0-c781-4153-89d4-9623051cf967,60,-,228.0,204,205,22,GTH8,7S,7S,1,complete_gene,fully_cleaved

CHECKING number of reads:
Starting mito-BAM filepath: /lustre/bio_running/GTEx_Long_Project/analysis/GTH8/GTH8.genome.chrM.reverse.bam

#####
Elaborating class: fully_cleaved

sample  new_class
GTH8    fully_cleaved    1129
dtype: int64

(1129, 16)
Number of reads for current class: 1129
- output mitoBAM for current class: /lustre/bio_running/GTEx_Long_Project/analysis/GTH8/GTH8.genome.chrM.reverse.bam.fully_cleaved.bam
- output mitoBAM readslist for current class: /lustre/bio_running/GTEx_Long_Project/analysis/GTH8/GTH8.genome.chrM.reverse.bam.fully_cleaved.bam.readslist
- output mitoBAM depth file for current class: /lustre/bio_running/GTEx_Long_Project/analysis/GTH8/GTH8.genome.chrM.reverse.bam.fully_cleaved.bam.depth.txt
1129
   1129 16	chrM
16569 /lustre/bio_running/GTEx_Long_Project/analysis/GTH8/GTH8.genome.chrM.reverse.bam.fully_cleaved.bam.depth.txt

#####
Elaborating class: partially_cleaved_short

sample  new_class
GTH8    partially_cleaved_short    5638
dtype: int64

(5638, 16)
Number of reads for current class: 5638
- output mitoBAM for current class: /lustre/bio_running/GTEx_Long_Project/analysis/GTH8/GTH8.genome.chrM.reverse.bam.partially_cleaved_short.bam
- output mitoBAM readslist for current class: /lustre/bio_running/GTEx_Long_Project/analysis/GTH8/GTH8.genome.chrM.reverse.bam.partially_cleaved_short.bam.readslist
- output mitoBAM depth file for current class: /lustre/bio_running/GTEx_Long_Project/analysis/GTH8/GTH8.genome.chrM.reverse.bam.partially_cleaved_short.bam.depth.txt
5638
   5638 16	chrM
16569 /lustre/bio_running/GTEx_Long_Project/analysis/GTH8/GTH8.genome.chrM.reverse.bam.partially_cleaved_short.bam.depth.txt

#####
Elaborating class: partially_cleaved_long

sample  new_class
GTH8    partially_cleaved_long    3823
dtype: int64

(3823, 16)
Number of reads for current class: 3823
- output mitoBAM for current class: /lustre/bio_running/GTEx_Long_Project/analysis/GTH8/GTH8.genome.chrM.reverse.bam.partially_cleaved_long.bam
- output mitoBAM readslist for current class: /lustre/bio_running/GTEx_Long_Project/analysis/GTH8/GTH8.genome.chrM.reverse.bam.partially_cleaved_long.bam.readslist
- output mitoBAM depth file for current class: /lustre/bio_running/GTEx_Long_Project/analysis/GTH8/GTH8.genome.chrM.reverse.bam.partially_cleaved_long.bam.depth.txt
3823
   3823 16	chrM
16569 /lustre/bio_running/GTEx_Long_Project/analysis/GTH8/GTH8.genome.chrM.reverse.bam.partially_cleaved_long.bam.depth.txt


######################################################################################################
######################################################################################################
######################################################################################################
GTB7 Total Processed samples: 25/73
Shape of df-reads for current sample: (9523, 16)
Unique number of reads: 9523

,Chr,ChrStart,ChrEnd,read_id,MAPQ,strand,read_length,alignment_length,reference_length,polyA_length,sample,overlapping_gene_ids,overlapping_gene_names,n_overlapping_gene_ids,chrM_primary_class,new_class
11284,chrM,189,397,eccf66cc-7f61-474c-a478-4358a98ea879,60,-,261.0,215,208,46,GTB7,7S,7S,1,complete_gene,fully_cleaved
11285,chrM,189,397,49133bab-9147-4c9a-9154-c3f56ef94ac8,60,-,221.0,212,208,27,GTB7,7S,7S,1,complete_gene,fully_cleaved

CHECKING number of reads:
Starting mito-BAM filepath: /lustre/bio_running/GTEx_Long_Project/analysis/GTB7/GTB7.genome.chrM.reverse.bam

#####
Elaborating class: fully_cleaved

sample  new_class
GTB7    fully_cleaved    342
dtype: int64

(342, 16)
Number of reads for current class: 342
- output mitoBAM for current class: /lustre/bio_running/GTEx_Long_Project/analysis/GTB7/GTB7.genome.chrM.reverse.bam.fully_cleaved.bam
- output mitoBAM readslist for current class: /lustre/bio_running/GTEx_Long_Project/analysis/GTB7/GTB7.genome.chrM.reverse.bam.fully_cleaved.bam.readslist
- output mitoBAM depth file for current class: /lustre/bio_running/GTEx_Long_Project/analysis/GTB7/GTB7.genome.chrM.reverse.bam.fully_cleaved.bam.depth.txt
342
    342 16	chrM
16569 /lustre/bio_running/GTEx_Long_Project/analysis/GTB7/GTB7.genome.chrM.reverse.bam.fully_cleaved.bam.depth.txt

#####
Elaborating class: partially_cleaved_short

sample  new_class
GTB7    partially_cleaved_short    3444
dtype: int64

(3444, 16)
Number of reads for current class: 3444
- output mitoBAM for current class: /lustre/bio_running/GTEx_Long_Project/analysis/GTB7/GTB7.genome.chrM.reverse.bam.partially_cleaved_short.bam
- output mitoBAM readslist for current class: /lustre/bio_running/GTEx_Long_Project/analysis/GTB7/GTB7.genome.chrM.reverse.bam.partially_cleaved_short.bam.readslist
- output mitoBAM depth file for current class: /lustre/bio_running/GTEx_Long_Project/analysis/GTB7/GTB7.genome.chrM.reverse.bam.partially_cleaved_short.bam.depth.txt
3444
   3444 16	chrM
16569 /lustre/bio_running/GTEx_Long_Project/analysis/GTB7/GTB7.genome.chrM.reverse.bam.partially_cleaved_short.bam.depth.txt

#####
Elaborating class: partially_cleaved_long

sample  new_class
GTB7    partially_cleaved_long    5737
dtype: int64

(5737, 16)
Number of reads for current class: 5737
- output mitoBAM for current class: /lustre/bio_running/GTEx_Long_Project/analysis/GTB7/GTB7.genome.chrM.reverse.bam.partially_cleaved_long.bam
- output mitoBAM readslist for current class: /lustre/bio_running/GTEx_Long_Project/analysis/GTB7/GTB7.genome.chrM.reverse.bam.partially_cleaved_long.bam.readslist
- output mitoBAM depth file for current class: /lustre/bio_running/GTEx_Long_Project/analysis/GTB7/GTB7.genome.chrM.reverse.bam.partially_cleaved_long.bam.depth.txt
5737
   5737 16	chrM
16569 /lustre/bio_running/GTEx_Long_Project/analysis/GTB7/GTB7.genome.chrM.reverse.bam.partially_cleaved_long.bam.depth.txt


######################################################################################################
######################################################################################################
######################################################################################################
GTD6 Total Processed samples: 26/73
Shape of df-reads for current sample: (8423, 16)
Unique number of reads: 8423

,Chr,ChrStart,ChrEnd,read_id,MAPQ,strand,read_length,alignment_length,reference_length,polyA_length,sample,overlapping_gene_ids,overlapping_gene_names,n_overlapping_gene_ids,chrM_primary_class,new_class
23555,chrM,189,395,2cd0ccf2-585d-4c51-800c-9d19f1d87dd7,60,-,218.0,208,206,40,GTD6,7S,7S,1,complete_gene,fully_cleaved
23556,chrM,189,394,bcfa1ad1-66b2-442a-937a-484fd160f594,60,-,213.0,206,205,26,GTD6,7S,7S,1,complete_gene,fully_cleaved

CHECKING number of reads:
Starting mito-BAM filepath: /lustre/bio_running/GTEx_Long_Project/analysis/GTD6/GTD6.genome.chrM.reverse.bam

#####
Elaborating class: fully_cleaved

sample  new_class
GTD6    fully_cleaved    1630
dtype: int64

(1630, 16)
Number of reads for current class: 1630
- output mitoBAM for current class: /lustre/bio_running/GTEx_Long_Project/analysis/GTD6/GTD6.genome.chrM.reverse.bam.fully_cleaved.bam
- output mitoBAM readslist for current class: /lustre/bio_running/GTEx_Long_Project/analysis/GTD6/GTD6.genome.chrM.reverse.bam.fully_cleaved.bam.readslist
- output mitoBAM depth file for current class: /lustre/bio_running/GTEx_Long_Project/analysis/GTD6/GTD6.genome.chrM.reverse.bam.fully_cleaved.bam.depth.txt
1630
   1630 16	chrM
16569 /lustre/bio_running/GTEx_Long_Project/analysis/GTD6/GTD6.genome.chrM.reverse.bam.fully_cleaved.bam.depth.txt

#####
Elaborating class: partially_cleaved_short

sample  new_class
GTD6    partially_cleaved_short    2911
dtype: int64

(2911, 16)
Number of reads for current class: 2911
- output mitoBAM for current class: /lustre/bio_running/GTEx_Long_Project/analysis/GTD6/GTD6.genome.chrM.reverse.bam.partially_cleaved_short.bam
- output mitoBAM readslist for current class: /lustre/bio_running/GTEx_Long_Project/analysis/GTD6/GTD6.genome.chrM.reverse.bam.partially_cleaved_short.bam.readslist
- output mitoBAM depth file for current class: /lustre/bio_running/GTEx_Long_Project/analysis/GTD6/GTD6.genome.chrM.reverse.bam.partially_cleaved_short.bam.depth.txt
2911
   2911 16	chrM
16569 /lustre/bio_running/GTEx_Long_Project/analysis/GTD6/GTD6.genome.chrM.reverse.bam.partially_cleaved_short.bam.depth.txt

#####
Elaborating class: partially_cleaved_long

sample  new_class
GTD6    partially_cleaved_long    3882
dtype: int64

(3882, 16)
Number of reads for current class: 3882
- output mitoBAM for current class: /lustre/bio_running/GTEx_Long_Project/analysis/GTD6/GTD6.genome.chrM.reverse.bam.partially_cleaved_long.bam
- output mitoBAM readslist for current class: /lustre/bio_running/GTEx_Long_Project/analysis/GTD6/GTD6.genome.chrM.reverse.bam.partially_cleaved_long.bam.readslist
- output mitoBAM depth file for current class: /lustre/bio_running/GTEx_Long_Project/analysis/GTD6/GTD6.genome.chrM.reverse.bam.partially_cleaved_long.bam.depth.txt
3882
   3882 16	chrM
16569 /lustre/bio_running/GTEx_Long_Project/analysis/GTD6/GTD6.genome.chrM.reverse.bam.partially_cleaved_long.bam.depth.txt


######################################################################################################
######################################################################################################
######################################################################################################
GTF5 Total Processed samples: 27/73
Shape of df-reads for current sample: (7568, 16)
Unique number of reads: 7568

,Chr,ChrStart,ChrEnd,read_id,MAPQ,strand,read_length,alignment_length,reference_length,polyA_length,sample,overlapping_gene_ids,overlapping_gene_names,n_overlapping_gene_ids,chrM_primary_class,new_class
36716,chrM,189,397,e428080a-1260-4c4f-932b-74af2867a61e,60,-,241.0,205,208,56,GTF5,7S,7S,1,complete_gene,fully_cleaved
36717,chrM,189,397,b0d30b43-f1dc-4261-8194-edfcee134b52,60,-,241.0,206,208,36,GTF5,7S,7S,1,complete_gene,fully_cleaved

CHECKING number of reads:
Starting mito-BAM filepath: /lustre/bio_running/GTEx_Long_Project/analysis/GTF5/GTF5.genome.chrM.reverse.bam

#####
Elaborating class: fully_cleaved

sample  new_class
GTF5    fully_cleaved    1028
dtype: int64

(1028, 16)
Number of reads for current class: 1028
- output mitoBAM for current class: /lustre/bio_running/GTEx_Long_Project/analysis/GTF5/GTF5.genome.chrM.reverse.bam.fully_cleaved.bam
- output mitoBAM readslist for current class: /lustre/bio_running/GTEx_Long_Project/analysis/GTF5/GTF5.genome.chrM.reverse.bam.fully_cleaved.bam.readslist
- output mitoBAM depth file for current class: /lustre/bio_running/GTEx_Long_Project/analysis/GTF5/GTF5.genome.chrM.reverse.bam.fully_cleaved.bam.depth.txt
1028
   1028 16	chrM
16569 /lustre/bio_running/GTEx_Long_Project/analysis/GTF5/GTF5.genome.chrM.reverse.bam.fully_cleaved.bam.depth.txt

#####
Elaborating class: partially_cleaved_short

sample  new_class
GTF5    partially_cleaved_short    3792
dtype: int64

(3792, 16)
Number of reads for current class: 3792
- output mitoBAM for current class: /lustre/bio_running/GTEx_Long_Project/analysis/GTF5/GTF5.genome.chrM.reverse.bam.partially_cleaved_short.bam
- output mitoBAM readslist for current class: /lustre/bio_running/GTEx_Long_Project/analysis/GTF5/GTF5.genome.chrM.reverse.bam.partially_cleaved_short.bam.readslist
- output mitoBAM depth file for current class: /lustre/bio_running/GTEx_Long_Project/analysis/GTF5/GTF5.genome.chrM.reverse.bam.partially_cleaved_short.bam.depth.txt
3792
   3792 16	chrM
16569 /lustre/bio_running/GTEx_Long_Project/analysis/GTF5/GTF5.genome.chrM.reverse.bam.partially_cleaved_short.bam.depth.txt

#####
Elaborating class: partially_cleaved_long

sample  new_class
GTF5    partially_cleaved_long    2748
dtype: int64

(2748, 16)
Number of reads for current class: 2748
- output mitoBAM for current class: /lustre/bio_running/GTEx_Long_Project/analysis/GTF5/GTF5.genome.chrM.reverse.bam.partially_cleaved_long.bam
- output mitoBAM readslist for current class: /lustre/bio_running/GTEx_Long_Project/analysis/GTF5/GTF5.genome.chrM.reverse.bam.partially_cleaved_long.bam.readslist
- output mitoBAM depth file for current class: /lustre/bio_running/GTEx_Long_Project/analysis/GTF5/GTF5.genome.chrM.reverse.bam.partially_cleaved_long.bam.depth.txt
2748
   2748 16	chrM
16569 /lustre/bio_running/GTEx_Long_Project/analysis/GTF5/GTF5.genome.chrM.reverse.bam.partially_cleaved_long.bam.depth.txt


######################################################################################################
######################################################################################################
######################################################################################################
GTG7 Total Processed samples: 28/73
Shape of df-reads for current sample: (7478, 16)
Unique number of reads: 7478

,Chr,ChrStart,ChrEnd,read_id,MAPQ,strand,read_length,alignment_length,reference_length,polyA_length,sample,overlapping_gene_ids,overlapping_gene_names,n_overlapping_gene_ids,chrM_primary_class,new_class
45537,chrM,189,397,1385b37f-4712-4fe6-bcd2-57e444511c3f,60,-,233.0,214,208,30,GTG7,7S,7S,1,complete_gene,fully_cleaved
45538,chrM,189,397,f68adeb8-80bc-41d2-b27f-9575392e4e23,60,-,219.0,210,208,25,GTG7,7S,7S,1,complete_gene,fully_cleaved

CHECKING number of reads:
Starting mito-BAM filepath: /lustre/bio_running/GTEx_Long_Project/analysis/GTG7/GTG7.genome.chrM.reverse.bam

#####
Elaborating class: fully_cleaved

sample  new_class
GTG7    fully_cleaved    923
dtype: int64

(923, 16)
Number of reads for current class: 923
- output mitoBAM for current class: /lustre/bio_running/GTEx_Long_Project/analysis/GTG7/GTG7.genome.chrM.reverse.bam.fully_cleaved.bam
- output mitoBAM readslist for current class: /lustre/bio_running/GTEx_Long_Project/analysis/GTG7/GTG7.genome.chrM.reverse.bam.fully_cleaved.bam.readslist
- output mitoBAM depth file for current class: /lustre/bio_running/GTEx_Long_Project/analysis/GTG7/GTG7.genome.chrM.reverse.bam.fully_cleaved.bam.depth.txt
923
    923 16	chrM
16569 /lustre/bio_running/GTEx_Long_Project/analysis/GTG7/GTG7.genome.chrM.reverse.bam.fully_cleaved.bam.depth.txt

#####
Elaborating class: partially_cleaved_short

sample  new_class
GTG7    partially_cleaved_short    3730
dtype: int64

(3730, 16)
Number of reads for current class: 3730
- output mitoBAM for current class: /lustre/bio_running/GTEx_Long_Project/analysis/GTG7/GTG7.genome.chrM.reverse.bam.partially_cleaved_short.bam
- output mitoBAM readslist for current class: /lustre/bio_running/GTEx_Long_Project/analysis/GTG7/GTG7.genome.chrM.reverse.bam.partially_cleaved_short.bam.readslist
- output mitoBAM depth file for current class: /lustre/bio_running/GTEx_Long_Project/analysis/GTG7/GTG7.genome.chrM.reverse.bam.partially_cleaved_short.bam.depth.txt
3730
   3730 16	chrM
16569 /lustre/bio_running/GTEx_Long_Project/analysis/GTG7/GTG7.genome.chrM.reverse.bam.partially_cleaved_short.bam.depth.txt

#####
Elaborating class: partially_cleaved_long

sample  new_class
GTG7    partially_cleaved_long    2825
dtype: int64

(2825, 16)
Number of reads for current class: 2825
- output mitoBAM for current class: /lustre/bio_running/GTEx_Long_Project/analysis/GTG7/GTG7.genome.chrM.reverse.bam.partially_cleaved_long.bam
- output mitoBAM readslist for current class: /lustre/bio_running/GTEx_Long_Project/analysis/GTG7/GTG7.genome.chrM.reverse.bam.partially_cleaved_long.bam.readslist
- output mitoBAM depth file for current class: /lustre/bio_running/GTEx_Long_Project/analysis/GTG7/GTG7.genome.chrM.reverse.bam.partially_cleaved_long.bam.depth.txt
2825
   2825 16	chrM
16569 /lustre/bio_running/GTEx_Long_Project/analysis/GTG7/GTG7.genome.chrM.reverse.bam.partially_cleaved_long.bam.depth.txt


######################################################################################################
######################################################################################################
######################################################################################################
GTG1 Total Processed samples: 29/73
Shape of df-reads for current sample: (7343, 16)
Unique number of reads: 7343

,Chr,ChrStart,ChrEnd,read_id,MAPQ,strand,read_length,alignment_length,reference_length,polyA_length,sample,overlapping_gene_ids,overlapping_gene_names,n_overlapping_gene_ids,chrM_primary_class,new_class
38458,chrM,189,396,b9000bbe-f49d-4d05-8884-92132ffe9aa3,60,-,219.0,206,207,32,GTG1,7S,7S,1,complete_gene,fully_cleaved
38459,chrM,189,397,1054b488-142d-49f3-8e75-c10049204820,60,-,222.0,210,208,49,GTG1,7S,7S,1,complete_gene,fully_cleaved

CHECKING number of reads:
Starting mito-BAM filepath: /lustre/bio_running/GTEx_Long_Project/analysis/GTG1/GTG1.genome.chrM.reverse.bam

#####
Elaborating class: fully_cleaved

sample  new_class
GTG1    fully_cleaved    666
dtype: int64

(666, 16)
Number of reads for current class: 666
- output mitoBAM for current class: /lustre/bio_running/GTEx_Long_Project/analysis/GTG1/GTG1.genome.chrM.reverse.bam.fully_cleaved.bam
- output mitoBAM readslist for current class: /lustre/bio_running/GTEx_Long_Project/analysis/GTG1/GTG1.genome.chrM.reverse.bam.fully_cleaved.bam.readslist
- output mitoBAM depth file for current class: /lustre/bio_running/GTEx_Long_Project/analysis/GTG1/GTG1.genome.chrM.reverse.bam.fully_cleaved.bam.depth.txt
666
    666 16	chrM
16569 /lustre/bio_running/GTEx_Long_Project/analysis/GTG1/GTG1.genome.chrM.reverse.bam.fully_cleaved.bam.depth.txt

#####
Elaborating class: partially_cleaved_short

sample  new_class
GTG1    partially_cleaved_short    3890
dtype: int64

(3890, 16)
Number of reads for current class: 3890
- output mitoBAM for current class: /lustre/bio_running/GTEx_Long_Project/analysis/GTG1/GTG1.genome.chrM.reverse.bam.partially_cleaved_short.bam
- output mitoBAM readslist for current class: /lustre/bio_running/GTEx_Long_Project/analysis/GTG1/GTG1.genome.chrM.reverse.bam.partially_cleaved_short.bam.readslist
- output mitoBAM depth file for current class: /lustre/bio_running/GTEx_Long_Project/analysis/GTG1/GTG1.genome.chrM.reverse.bam.partially_cleaved_short.bam.depth.txt
3890
   3890 16	chrM
16569 /lustre/bio_running/GTEx_Long_Project/analysis/GTG1/GTG1.genome.chrM.reverse.bam.partially_cleaved_short.bam.depth.txt

#####
Elaborating class: partially_cleaved_long

sample  new_class
GTG1    partially_cleaved_long    2787
dtype: int64

(2787, 16)
Number of reads for current class: 2787
- output mitoBAM for current class: /lustre/bio_running/GTEx_Long_Project/analysis/GTG1/GTG1.genome.chrM.reverse.bam.partially_cleaved_long.bam
- output mitoBAM readslist for current class: /lustre/bio_running/GTEx_Long_Project/analysis/GTG1/GTG1.genome.chrM.reverse.bam.partially_cleaved_long.bam.readslist
- output mitoBAM depth file for current class: /lustre/bio_running/GTEx_Long_Project/analysis/GTG1/GTG1.genome.chrM.reverse.bam.partially_cleaved_long.bam.depth.txt
2787
   2787 16	chrM
16569 /lustre/bio_running/GTEx_Long_Project/analysis/GTG1/GTG1.genome.chrM.reverse.bam.partially_cleaved_long.bam.depth.txt


######################################################################################################
######################################################################################################
######################################################################################################
GTG3 Total Processed samples: 30/73
Shape of df-reads for current sample: (6773, 16)
Unique number of reads: 6773

,Chr,ChrStart,ChrEnd,read_id,MAPQ,strand,read_length,alignment_length,reference_length,polyA_length,sample,overlapping_gene_ids,overlapping_gene_names,n_overlapping_gene_ids,chrM_primary_class,new_class
39429,chrM,189,397,760a4cdd-3073-401a-98cc-8c3ce871c46a,60,-,221.0,208,208,39,GTG3,7S,7S,1,complete_gene,fully_cleaved
39430,chrM,189,396,9ead9600-6705-4ce5-8309-52fa51ae0f58,60,-,210.0,208,207,37,GTG3,7S,7S,1,complete_gene,fully_cleaved

CHECKING number of reads:
Starting mito-BAM filepath: /lustre/bio_running/GTEx_Long_Project/analysis/GTG3/GTG3.genome.chrM.reverse.bam

#####
Elaborating class: fully_cleaved

sample  new_class
GTG3    fully_cleaved    594
dtype: int64

(594, 16)
Number of reads for current class: 594
- output mitoBAM for current class: /lustre/bio_running/GTEx_Long_Project/analysis/GTG3/GTG3.genome.chrM.reverse.bam.fully_cleaved.bam
- output mitoBAM readslist for current class: /lustre/bio_running/GTEx_Long_Project/analysis/GTG3/GTG3.genome.chrM.reverse.bam.fully_cleaved.bam.readslist
- output mitoBAM depth file for current class: /lustre/bio_running/GTEx_Long_Project/analysis/GTG3/GTG3.genome.chrM.reverse.bam.fully_cleaved.bam.depth.txt
594
    594 16	chrM
16569 /lustre/bio_running/GTEx_Long_Project/analysis/GTG3/GTG3.genome.chrM.reverse.bam.fully_cleaved.bam.depth.txt

#####
Elaborating class: partially_cleaved_short

sample  new_class
GTG3    partially_cleaved_short    4093
dtype: int64

(4093, 16)
Number of reads for current class: 4093
- output mitoBAM for current class: /lustre/bio_running/GTEx_Long_Project/analysis/GTG3/GTG3.genome.chrM.reverse.bam.partially_cleaved_short.bam
- output mitoBAM readslist for current class: /lustre/bio_running/GTEx_Long_Project/analysis/GTG3/GTG3.genome.chrM.reverse.bam.partially_cleaved_short.bam.readslist
- output mitoBAM depth file for current class: /lustre/bio_running/GTEx_Long_Project/analysis/GTG3/GTG3.genome.chrM.reverse.bam.partially_cleaved_short.bam.depth.txt
4093
   4093 16	chrM
16569 /lustre/bio_running/GTEx_Long_Project/analysis/GTG3/GTG3.genome.chrM.reverse.bam.partially_cleaved_short.bam.depth.txt

#####
Elaborating class: partially_cleaved_long

sample  new_class
GTG3    partially_cleaved_long    2086
dtype: int64

(2086, 16)
Number of reads for current class: 2086
- output mitoBAM for current class: /lustre/bio_running/GTEx_Long_Project/analysis/GTG3/GTG3.genome.chrM.reverse.bam.partially_cleaved_long.bam
- output mitoBAM readslist for current class: /lustre/bio_running/GTEx_Long_Project/analysis/GTG3/GTG3.genome.chrM.reverse.bam.partially_cleaved_long.bam.readslist
- output mitoBAM depth file for current class: /lustre/bio_running/GTEx_Long_Project/analysis/GTG3/GTG3.genome.chrM.reverse.bam.partially_cleaved_long.bam.depth.txt
2086
   2086 16	chrM
16569 /lustre/bio_running/GTEx_Long_Project/analysis/GTG3/GTG3.genome.chrM.reverse.bam.partially_cleaved_long.bam.depth.txt


######################################################################################################
######################################################################################################
######################################################################################################
GTF1 Total Processed samples: 31/73
Shape of df-reads for current sample: (6431, 16)
Unique number of reads: 6431

,Chr,ChrStart,ChrEnd,read_id,MAPQ,strand,read_length,alignment_length,reference_length,polyA_length,sample,overlapping_gene_ids,overlapping_gene_names,n_overlapping_gene_ids,chrM_primary_class,new_class
32510,chrM,189,397,75246ed9-8de9-4ab3-add1-0bbbdf8cae41,60,-,224.0,203,208,19,GTF1,7S,7S,1,complete_gene,fully_cleaved
32511,chrM,189,397,831a7d06-1947-4550-a96d-35c60434bd6f,60,-,232.0,209,208,25,GTF1,7S,7S,1,complete_gene,fully_cleaved

CHECKING number of reads:
Starting mito-BAM filepath: /lustre/bio_running/GTEx_Long_Project/analysis/GTF1/GTF1.genome.chrM.reverse.bam

#####
Elaborating class: fully_cleaved

sample  new_class
GTF1    fully_cleaved    741
dtype: int64

(741, 16)
Number of reads for current class: 741
- output mitoBAM for current class: /lustre/bio_running/GTEx_Long_Project/analysis/GTF1/GTF1.genome.chrM.reverse.bam.fully_cleaved.bam
- output mitoBAM readslist for current class: /lustre/bio_running/GTEx_Long_Project/analysis/GTF1/GTF1.genome.chrM.reverse.bam.fully_cleaved.bam.readslist
- output mitoBAM depth file for current class: /lustre/bio_running/GTEx_Long_Project/analysis/GTF1/GTF1.genome.chrM.reverse.bam.fully_cleaved.bam.depth.txt
741
    741 16	chrM
16569 /lustre/bio_running/GTEx_Long_Project/analysis/GTF1/GTF1.genome.chrM.reverse.bam.fully_cleaved.bam.depth.txt

#####
Elaborating class: partially_cleaved_short

sample  new_class
GTF1    partially_cleaved_short    4049
dtype: int64

(4049, 16)
Number of reads for current class: 4049
- output mitoBAM for current class: /lustre/bio_running/GTEx_Long_Project/analysis/GTF1/GTF1.genome.chrM.reverse.bam.partially_cleaved_short.bam
- output mitoBAM readslist for current class: /lustre/bio_running/GTEx_Long_Project/analysis/GTF1/GTF1.genome.chrM.reverse.bam.partially_cleaved_short.bam.readslist
- output mitoBAM depth file for current class: /lustre/bio_running/GTEx_Long_Project/analysis/GTF1/GTF1.genome.chrM.reverse.bam.partially_cleaved_short.bam.depth.txt
4049
   4049 16	chrM
16569 /lustre/bio_running/GTEx_Long_Project/analysis/GTF1/GTF1.genome.chrM.reverse.bam.partially_cleaved_short.bam.depth.txt

#####
Elaborating class: partially_cleaved_long

sample  new_class
GTF1    partially_cleaved_long    1641
dtype: int64

(1641, 16)
Number of reads for current class: 1641
- output mitoBAM for current class: /lustre/bio_running/GTEx_Long_Project/analysis/GTF1/GTF1.genome.chrM.reverse.bam.partially_cleaved_long.bam
- output mitoBAM readslist for current class: /lustre/bio_running/GTEx_Long_Project/analysis/GTF1/GTF1.genome.chrM.reverse.bam.partially_cleaved_long.bam.readslist
- output mitoBAM depth file for current class: /lustre/bio_running/GTEx_Long_Project/analysis/GTF1/GTF1.genome.chrM.reverse.bam.partially_cleaved_long.bam.depth.txt
1641
   1641 16	chrM
16569 /lustre/bio_running/GTEx_Long_Project/analysis/GTF1/GTF1.genome.chrM.reverse.bam.partially_cleaved_long.bam.depth.txt


######################################################################################################
######################################################################################################
######################################################################################################
GTA4 Total Processed samples: 32/73
Shape of df-reads for current sample: (6291, 16)
Unique number of reads: 6291

,Chr,ChrStart,ChrEnd,read_id,MAPQ,strand,read_length,alignment_length,reference_length,polyA_length,sample,overlapping_gene_ids,overlapping_gene_names,n_overlapping_gene_ids,chrM_primary_class,new_class
2804,chrM,189,397,e49caed2-6d02-4fde-b119-f1028a8b5efe,60,-,255.0,209,208,33,GTA4,7S,7S,1,complete_gene,fully_cleaved
2805,chrM,189,396,48e5261f-81c1-4159-aca1-ef741fae87f3,60,-,246.0,208,207,33,GTA4,7S,7S,1,complete_gene,fully_cleaved

CHECKING number of reads:
Starting mito-BAM filepath: /lustre/bio_running/GTEx_Long_Project/analysis/GTA4/GTA4.genome.chrM.reverse.bam

#####
Elaborating class: fully_cleaved

sample  new_class
GTA4    fully_cleaved    776
dtype: int64

(776, 16)
Number of reads for current class: 776
- output mitoBAM for current class: /lustre/bio_running/GTEx_Long_Project/analysis/GTA4/GTA4.genome.chrM.reverse.bam.fully_cleaved.bam
- output mitoBAM readslist for current class: /lustre/bio_running/GTEx_Long_Project/analysis/GTA4/GTA4.genome.chrM.reverse.bam.fully_cleaved.bam.readslist
- output mitoBAM depth file for current class: /lustre/bio_running/GTEx_Long_Project/analysis/GTA4/GTA4.genome.chrM.reverse.bam.fully_cleaved.bam.depth.txt
776
    776 16	chrM
16569 /lustre/bio_running/GTEx_Long_Project/analysis/GTA4/GTA4.genome.chrM.reverse.bam.fully_cleaved.bam.depth.txt

#####
Elaborating class: partially_cleaved_short

sample  new_class
GTA4    partially_cleaved_short    2201
dtype: int64

(2201, 16)
Number of reads for current class: 2201
- output mitoBAM for current class: /lustre/bio_running/GTEx_Long_Project/analysis/GTA4/GTA4.genome.chrM.reverse.bam.partially_cleaved_short.bam
- output mitoBAM readslist for current class: /lustre/bio_running/GTEx_Long_Project/analysis/GTA4/GTA4.genome.chrM.reverse.bam.partially_cleaved_short.bam.readslist
- output mitoBAM depth file for current class: /lustre/bio_running/GTEx_Long_Project/analysis/GTA4/GTA4.genome.chrM.reverse.bam.partially_cleaved_short.bam.depth.txt
2201
   2201 16	chrM
16569 /lustre/bio_running/GTEx_Long_Project/analysis/GTA4/GTA4.genome.chrM.reverse.bam.partially_cleaved_short.bam.depth.txt

#####
Elaborating class: partially_cleaved_long

sample  new_class
GTA4    partially_cleaved_long    3314
dtype: int64

(3314, 16)
Number of reads for current class: 3314
- output mitoBAM for current class: /lustre/bio_running/GTEx_Long_Project/analysis/GTA4/GTA4.genome.chrM.reverse.bam.partially_cleaved_long.bam
- output mitoBAM readslist for current class: /lustre/bio_running/GTEx_Long_Project/analysis/GTA4/GTA4.genome.chrM.reverse.bam.partially_cleaved_long.bam.readslist
- output mitoBAM depth file for current class: /lustre/bio_running/GTEx_Long_Project/analysis/GTA4/GTA4.genome.chrM.reverse.bam.partially_cleaved_long.bam.depth.txt
3314
   3314 16	chrM
16569 /lustre/bio_running/GTEx_Long_Project/analysis/GTA4/GTA4.genome.chrM.reverse.bam.partially_cleaved_long.bam.depth.txt


######################################################################################################
######################################################################################################
######################################################################################################
GTC3 Total Processed samples: 33/73
Shape of df-reads for current sample: (6118, 16)
Unique number of reads: 6118

,Chr,ChrStart,ChrEnd,read_id,MAPQ,strand,read_length,alignment_length,reference_length,polyA_length,sample,overlapping_gene_ids,overlapping_gene_names,n_overlapping_gene_ids,chrM_primary_class,new_class
13376,chrM,189,397,630db9b1-2faa-4f63-9a60-aab94f01bde3,60,-,223.0,213,208,50,GTC3,7S,7S,1,complete_gene,fully_cleaved
13377,chrM,189,395,9383c3c5-8b28-48d1-9a42-9a9d8c1e3e3a,60,-,218.0,204,206,37,GTC3,7S,7S,1,complete_gene,fully_cleaved

CHECKING number of reads:
Starting mito-BAM filepath: /lustre/bio_running/GTEx_Long_Project/analysis/GTC3/GTC3.genome.chrM.reverse.bam

#####
Elaborating class: fully_cleaved

sample  new_class
GTC3    fully_cleaved    410
dtype: int64

(410, 16)
Number of reads for current class: 410
- output mitoBAM for current class: /lustre/bio_running/GTEx_Long_Project/analysis/GTC3/GTC3.genome.chrM.reverse.bam.fully_cleaved.bam
- output mitoBAM readslist for current class: /lustre/bio_running/GTEx_Long_Project/analysis/GTC3/GTC3.genome.chrM.reverse.bam.fully_cleaved.bam.readslist
- output mitoBAM depth file for current class: /lustre/bio_running/GTEx_Long_Project/analysis/GTC3/GTC3.genome.chrM.reverse.bam.fully_cleaved.bam.depth.txt
410
    410 16	chrM
16569 /lustre/bio_running/GTEx_Long_Project/analysis/GTC3/GTC3.genome.chrM.reverse.bam.fully_cleaved.bam.depth.txt

#####
Elaborating class: partially_cleaved_short

sample  new_class
GTC3    partially_cleaved_short    2175
dtype: int64

(2175, 16)
Number of reads for current class: 2175
- output mitoBAM for current class: /lustre/bio_running/GTEx_Long_Project/analysis/GTC3/GTC3.genome.chrM.reverse.bam.partially_cleaved_short.bam
- output mitoBAM readslist for current class: /lustre/bio_running/GTEx_Long_Project/analysis/GTC3/GTC3.genome.chrM.reverse.bam.partially_cleaved_short.bam.readslist
- output mitoBAM depth file for current class: /lustre/bio_running/GTEx_Long_Project/analysis/GTC3/GTC3.genome.chrM.reverse.bam.partially_cleaved_short.bam.depth.txt
2175
   2175 16	chrM
16569 /lustre/bio_running/GTEx_Long_Project/analysis/GTC3/GTC3.genome.chrM.reverse.bam.partially_cleaved_short.bam.depth.txt

#####
Elaborating class: partially_cleaved_long

sample  new_class
GTC3    partially_cleaved_long    3533
dtype: int64

(3533, 16)
Number of reads for current class: 3533
- output mitoBAM for current class: /lustre/bio_running/GTEx_Long_Project/analysis/GTC3/GTC3.genome.chrM.reverse.bam.partially_cleaved_long.bam
- output mitoBAM readslist for current class: /lustre/bio_running/GTEx_Long_Project/analysis/GTC3/GTC3.genome.chrM.reverse.bam.partially_cleaved_long.bam.readslist
- output mitoBAM depth file for current class: /lustre/bio_running/GTEx_Long_Project/analysis/GTC3/GTC3.genome.chrM.reverse.bam.partially_cleaved_long.bam.depth.txt
3533
   3533 16	chrM
16569 /lustre/bio_running/GTEx_Long_Project/analysis/GTC3/GTC3.genome.chrM.reverse.bam.partially_cleaved_long.bam.depth.txt


######################################################################################################
######################################################################################################
######################################################################################################
GTB3 Total Processed samples: 34/73
Shape of df-reads for current sample: (5936, 16)
Unique number of reads: 5936

,Chr,ChrStart,ChrEnd,read_id,MAPQ,strand,read_length,alignment_length,reference_length,polyA_length,sample,overlapping_gene_ids,overlapping_gene_names,n_overlapping_gene_ids,chrM_primary_class,new_class
7971,chrM,189,391,ccf2c48b-b3d5-410c-a660-56f483f800ad,60,-,207.0,202,202,39,GTB3,7S,7S,1,complete_gene,fully_cleaved
7972,chrM,189,396,afa5dce5-3deb-447a-91fc-079e34d7ed65,60,-,211.0,206,207,37,GTB3,7S,7S,1,complete_gene,fully_cleaved

CHECKING number of reads:
Starting mito-BAM filepath: /lustre/bio_running/GTEx_Long_Project/analysis/GTB3/GTB3.genome.chrM.reverse.bam

#####
Elaborating class: fully_cleaved

sample  new_class
GTB3    fully_cleaved    1117
dtype: int64

(1117, 16)
Number of reads for current class: 1117
- output mitoBAM for current class: /lustre/bio_running/GTEx_Long_Project/analysis/GTB3/GTB3.genome.chrM.reverse.bam.fully_cleaved.bam
- output mitoBAM readslist for current class: /lustre/bio_running/GTEx_Long_Project/analysis/GTB3/GTB3.genome.chrM.reverse.bam.fully_cleaved.bam.readslist
- output mitoBAM depth file for current class: /lustre/bio_running/GTEx_Long_Project/analysis/GTB3/GTB3.genome.chrM.reverse.bam.fully_cleaved.bam.depth.txt
1117
   1117 16	chrM
16569 /lustre/bio_running/GTEx_Long_Project/analysis/GTB3/GTB3.genome.chrM.reverse.bam.fully_cleaved.bam.depth.txt

#####
Elaborating class: partially_cleaved_short

sample  new_class
GTB3    partially_cleaved_short    3759
dtype: int64

(3759, 16)
Number of reads for current class: 3759
- output mitoBAM for current class: /lustre/bio_running/GTEx_Long_Project/analysis/GTB3/GTB3.genome.chrM.reverse.bam.partially_cleaved_short.bam
- output mitoBAM readslist for current class: /lustre/bio_running/GTEx_Long_Project/analysis/GTB3/GTB3.genome.chrM.reverse.bam.partially_cleaved_short.bam.readslist
- output mitoBAM depth file for current class: /lustre/bio_running/GTEx_Long_Project/analysis/GTB3/GTB3.genome.chrM.reverse.bam.partially_cleaved_short.bam.depth.txt
3759
   3759 16	chrM
16569 /lustre/bio_running/GTEx_Long_Project/analysis/GTB3/GTB3.genome.chrM.reverse.bam.partially_cleaved_short.bam.depth.txt

#####
Elaborating class: partially_cleaved_long

sample  new_class
GTB3    partially_cleaved_long    1060
dtype: int64

(1060, 16)
Number of reads for current class: 1060
- output mitoBAM for current class: /lustre/bio_running/GTEx_Long_Project/analysis/GTB3/GTB3.genome.chrM.reverse.bam.partially_cleaved_long.bam
- output mitoBAM readslist for current class: /lustre/bio_running/GTEx_Long_Project/analysis/GTB3/GTB3.genome.chrM.reverse.bam.partially_cleaved_long.bam.readslist
- output mitoBAM depth file for current class: /lustre/bio_running/GTEx_Long_Project/analysis/GTB3/GTB3.genome.chrM.reverse.bam.partially_cleaved_long.bam.depth.txt
1060
   1060 16	chrM
16569 /lustre/bio_running/GTEx_Long_Project/analysis/GTB3/GTB3.genome.chrM.reverse.bam.partially_cleaved_long.bam.depth.txt


######################################################################################################
######################################################################################################
######################################################################################################
GTD5 Total Processed samples: 35/73
Shape of df-reads for current sample: (5865, 16)
Unique number of reads: 5865

,Chr,ChrStart,ChrEnd,read_id,MAPQ,strand,read_length,alignment_length,reference_length,polyA_length,sample,overlapping_gene_ids,overlapping_gene_names,n_overlapping_gene_ids,chrM_primary_class,new_class
22777,chrM,189,397,043ba47a-1eec-4391-ba68-15ae4e25a9a1,60,-,219.0,209,208,34,GTD5,7S,7S,1,complete_gene,fully_cleaved
22778,chrM,189,397,7c658881-5e3c-4b56-9b2c-83d77596fbd6,60,-,216.0,207,208,32,GTD5,7S,7S,1,complete_gene,fully_cleaved

CHECKING number of reads:
Starting mito-BAM filepath: /lustre/bio_running/GTEx_Long_Project/analysis/GTD5/GTD5.genome.chrM.reverse.bam

#####
Elaborating class: fully_cleaved

sample  new_class
GTD5    fully_cleaved    778
dtype: int64

(778, 16)
Number of reads for current class: 778
- output mitoBAM for current class: /lustre/bio_running/GTEx_Long_Project/analysis/GTD5/GTD5.genome.chrM.reverse.bam.fully_cleaved.bam
- output mitoBAM readslist for current class: /lustre/bio_running/GTEx_Long_Project/analysis/GTD5/GTD5.genome.chrM.reverse.bam.fully_cleaved.bam.readslist
- output mitoBAM depth file for current class: /lustre/bio_running/GTEx_Long_Project/analysis/GTD5/GTD5.genome.chrM.reverse.bam.fully_cleaved.bam.depth.txt
778
    778 16	chrM
16569 /lustre/bio_running/GTEx_Long_Project/analysis/GTD5/GTD5.genome.chrM.reverse.bam.fully_cleaved.bam.depth.txt

#####
Elaborating class: partially_cleaved_short

sample  new_class
GTD5    partially_cleaved_short    3483
dtype: int64

(3483, 16)
Number of reads for current class: 3483
- output mitoBAM for current class: /lustre/bio_running/GTEx_Long_Project/analysis/GTD5/GTD5.genome.chrM.reverse.bam.partially_cleaved_short.bam
- output mitoBAM readslist for current class: /lustre/bio_running/GTEx_Long_Project/analysis/GTD5/GTD5.genome.chrM.reverse.bam.partially_cleaved_short.bam.readslist
- output mitoBAM depth file for current class: /lustre/bio_running/GTEx_Long_Project/analysis/GTD5/GTD5.genome.chrM.reverse.bam.partially_cleaved_short.bam.depth.txt
3483
   3483 16	chrM
16569 /lustre/bio_running/GTEx_Long_Project/analysis/GTD5/GTD5.genome.chrM.reverse.bam.partially_cleaved_short.bam.depth.txt

#####
Elaborating class: partially_cleaved_long

sample  new_class
GTD5    partially_cleaved_long    1604
dtype: int64

(1604, 16)
Number of reads for current class: 1604
- output mitoBAM for current class: /lustre/bio_running/GTEx_Long_Project/analysis/GTD5/GTD5.genome.chrM.reverse.bam.partially_cleaved_long.bam
- output mitoBAM readslist for current class: /lustre/bio_running/GTEx_Long_Project/analysis/GTD5/GTD5.genome.chrM.reverse.bam.partially_cleaved_long.bam.readslist
- output mitoBAM depth file for current class: /lustre/bio_running/GTEx_Long_Project/analysis/GTD5/GTD5.genome.chrM.reverse.bam.partially_cleaved_long.bam.depth.txt
1604
   1604 16	chrM
16569 /lustre/bio_running/GTEx_Long_Project/analysis/GTD5/GTD5.genome.chrM.reverse.bam.partially_cleaved_long.bam.depth.txt


######################################################################################################
######################################################################################################
######################################################################################################
GTC2 Total Processed samples: 36/73
Shape of df-reads for current sample: (5578, 16)
Unique number of reads: 5578

,Chr,ChrStart,ChrEnd,read_id,MAPQ,strand,read_length,alignment_length,reference_length,polyA_length,sample,overlapping_gene_ids,overlapping_gene_names,n_overlapping_gene_ids,chrM_primary_class,new_class
12546,chrM,189,397,689fb629-fb62-4b79-9c4e-25518a13aa01,60,-,227.0,207,208,35,GTC2,7S,7S,1,complete_gene,fully_cleaved
12547,chrM,189,398,aca23f74-75f4-41ec-93df-6909c9a7728c,60,-,214.0,208,209,34,GTC2,7S,7S,1,complete_gene,fully_cleaved

CHECKING number of reads:
Starting mito-BAM filepath: /lustre/bio_running/GTEx_Long_Project/analysis/GTC2/GTC2.genome.chrM.reverse.bam

#####
Elaborating class: fully_cleaved

sample  new_class
GTC2    fully_cleaved    830
dtype: int64

(830, 16)
Number of reads for current class: 830
- output mitoBAM for current class: /lustre/bio_running/GTEx_Long_Project/analysis/GTC2/GTC2.genome.chrM.reverse.bam.fully_cleaved.bam
- output mitoBAM readslist for current class: /lustre/bio_running/GTEx_Long_Project/analysis/GTC2/GTC2.genome.chrM.reverse.bam.fully_cleaved.bam.readslist
- output mitoBAM depth file for current class: /lustre/bio_running/GTEx_Long_Project/analysis/GTC2/GTC2.genome.chrM.reverse.bam.fully_cleaved.bam.depth.txt
830
    830 16	chrM
16569 /lustre/bio_running/GTEx_Long_Project/analysis/GTC2/GTC2.genome.chrM.reverse.bam.fully_cleaved.bam.depth.txt

#####
Elaborating class: partially_cleaved_short

sample  new_class
GTC2    partially_cleaved_short    3523
dtype: int64

(3523, 16)
Number of reads for current class: 3523
- output mitoBAM for current class: /lustre/bio_running/GTEx_Long_Project/analysis/GTC2/GTC2.genome.chrM.reverse.bam.partially_cleaved_short.bam
- output mitoBAM readslist for current class: /lustre/bio_running/GTEx_Long_Project/analysis/GTC2/GTC2.genome.chrM.reverse.bam.partially_cleaved_short.bam.readslist
- output mitoBAM depth file for current class: /lustre/bio_running/GTEx_Long_Project/analysis/GTC2/GTC2.genome.chrM.reverse.bam.partially_cleaved_short.bam.depth.txt
3523
   3523 16	chrM
16569 /lustre/bio_running/GTEx_Long_Project/analysis/GTC2/GTC2.genome.chrM.reverse.bam.partially_cleaved_short.bam.depth.txt

#####
Elaborating class: partially_cleaved_long

sample  new_class
GTC2    partially_cleaved_long    1225
dtype: int64

(1225, 16)
Number of reads for current class: 1225
- output mitoBAM for current class: /lustre/bio_running/GTEx_Long_Project/analysis/GTC2/GTC2.genome.chrM.reverse.bam.partially_cleaved_long.bam
- output mitoBAM readslist for current class: /lustre/bio_running/GTEx_Long_Project/analysis/GTC2/GTC2.genome.chrM.reverse.bam.partially_cleaved_long.bam.readslist
- output mitoBAM depth file for current class: /lustre/bio_running/GTEx_Long_Project/analysis/GTC2/GTC2.genome.chrM.reverse.bam.partially_cleaved_long.bam.depth.txt
1225
   1225 16	chrM
16569 /lustre/bio_running/GTEx_Long_Project/analysis/GTC2/GTC2.genome.chrM.reverse.bam.partially_cleaved_long.bam.depth.txt


######################################################################################################
######################################################################################################
######################################################################################################
GTA10 Total Processed samples: 37/73
Shape of df-reads for current sample: (5053, 16)
Unique number of reads: 5053

,Chr,ChrStart,ChrEnd,read_id,MAPQ,strand,read_length,alignment_length,reference_length,polyA_length,sample,overlapping_gene_ids,overlapping_gene_names,n_overlapping_gene_ids,chrM_primary_class,new_class
1479,chrM,189,397,5b85100f-8e9a-463d-a791-89bed8b96a51,60,-,212.0,208,208,36,GTA10,7S,7S,1,complete_gene,fully_cleaved
1480,chrM,189,397,37179b9a-6072-42b2-adc2-b6df1cd9ccdc,60,-,244.0,210,208,48,GTA10,7S,7S,1,complete_gene,fully_cleaved

CHECKING number of reads:
Starting mito-BAM filepath: /lustre/bio_running/GTEx_Long_Project/analysis/GTA10/GTA10.genome.chrM.reverse.bam

#####
Elaborating class: fully_cleaved

sample  new_class
GTA10   fully_cleaved    243
dtype: int64

(243, 16)
Number of reads for current class: 243
- output mitoBAM for current class: /lustre/bio_running/GTEx_Long_Project/analysis/GTA10/GTA10.genome.chrM.reverse.bam.fully_cleaved.bam
- output mitoBAM readslist for current class: /lustre/bio_running/GTEx_Long_Project/analysis/GTA10/GTA10.genome.chrM.reverse.bam.fully_cleaved.bam.readslist
- output mitoBAM depth file for current class: /lustre/bio_running/GTEx_Long_Project/analysis/GTA10/GTA10.genome.chrM.reverse.bam.fully_cleaved.bam.depth.txt
243
    243 16	chrM
16569 /lustre/bio_running/GTEx_Long_Project/analysis/GTA10/GTA10.genome.chrM.reverse.bam.fully_cleaved.bam.depth.txt

#####
Elaborating class: partially_cleaved_short

sample  new_class
GTA10   partially_cleaved_short    2993
dtype: int64

(2993, 16)
Number of reads for current class: 2993
- output mitoBAM for current class: /lustre/bio_running/GTEx_Long_Project/analysis/GTA10/GTA10.genome.chrM.reverse.bam.partially_cleaved_short.bam
- output mitoBAM readslist for current class: /lustre/bio_running/GTEx_Long_Project/analysis/GTA10/GTA10.genome.chrM.reverse.bam.partially_cleaved_short.bam.readslist
- output mitoBAM depth file for current class: /lustre/bio_running/GTEx_Long_Project/analysis/GTA10/GTA10.genome.chrM.reverse.bam.partially_cleaved_short.bam.depth.txt
2993
   2993 16	chrM
16569 /lustre/bio_running/GTEx_Long_Project/analysis/GTA10/GTA10.genome.chrM.reverse.bam.partially_cleaved_short.bam.depth.txt

#####
Elaborating class: partially_cleaved_long

sample  new_class
GTA10   partially_cleaved_long    1817
dtype: int64

(1817, 16)
Number of reads for current class: 1817
- output mitoBAM for current class: /lustre/bio_running/GTEx_Long_Project/analysis/GTA10/GTA10.genome.chrM.reverse.bam.partially_cleaved_long.bam
- output mitoBAM readslist for current class: /lustre/bio_running/GTEx_Long_Project/analysis/GTA10/GTA10.genome.chrM.reverse.bam.partially_cleaved_long.bam.readslist
- output mitoBAM depth file for current class: /lustre/bio_running/GTEx_Long_Project/analysis/GTA10/GTA10.genome.chrM.reverse.bam.partially_cleaved_long.bam.depth.txt
1817
   1817 16	chrM
16569 /lustre/bio_running/GTEx_Long_Project/analysis/GTA10/GTA10.genome.chrM.reverse.bam.partially_cleaved_long.bam.depth.txt


######################################################################################################
######################################################################################################
######################################################################################################
GTG2 Total Processed samples: 38/73
Shape of df-reads for current sample: (5012, 16)
Unique number of reads: 5012

,Chr,ChrStart,ChrEnd,read_id,MAPQ,strand,read_length,alignment_length,reference_length,polyA_length,sample,overlapping_gene_ids,overlapping_gene_names,n_overlapping_gene_ids,chrM_primary_class,new_class
39124,chrM,189,392,c6bc012e-211c-43c7-8512-f14485f10362,60,-,217.0,205,203,48,GTG2,7S,7S,1,complete_gene,fully_cleaved
39125,chrM,189,397,ed5f9246-50c0-43c7-8718-2735a353e8f3,60,-,251.0,207,208,53,GTG2,7S,7S,1,complete_gene,fully_cleaved

CHECKING number of reads:
Starting mito-BAM filepath: /lustre/bio_running/GTEx_Long_Project/analysis/GTG2/GTG2.genome.chrM.reverse.bam

#####
Elaborating class: fully_cleaved

sample  new_class
GTG2    fully_cleaved    305
dtype: int64

(305, 16)
Number of reads for current class: 305
- output mitoBAM for current class: /lustre/bio_running/GTEx_Long_Project/analysis/GTG2/GTG2.genome.chrM.reverse.bam.fully_cleaved.bam
- output mitoBAM readslist for current class: /lustre/bio_running/GTEx_Long_Project/analysis/GTG2/GTG2.genome.chrM.reverse.bam.fully_cleaved.bam.readslist
- output mitoBAM depth file for current class: /lustre/bio_running/GTEx_Long_Project/analysis/GTG2/GTG2.genome.chrM.reverse.bam.fully_cleaved.bam.depth.txt
305
    305 16	chrM
16569 /lustre/bio_running/GTEx_Long_Project/analysis/GTG2/GTG2.genome.chrM.reverse.bam.fully_cleaved.bam.depth.txt

#####
Elaborating class: partially_cleaved_short

sample  new_class
GTG2    partially_cleaved_short    2202
dtype: int64

(2202, 16)
Number of reads for current class: 2202
- output mitoBAM for current class: /lustre/bio_running/GTEx_Long_Project/analysis/GTG2/GTG2.genome.chrM.reverse.bam.partially_cleaved_short.bam
- output mitoBAM readslist for current class: /lustre/bio_running/GTEx_Long_Project/analysis/GTG2/GTG2.genome.chrM.reverse.bam.partially_cleaved_short.bam.readslist
- output mitoBAM depth file for current class: /lustre/bio_running/GTEx_Long_Project/analysis/GTG2/GTG2.genome.chrM.reverse.bam.partially_cleaved_short.bam.depth.txt
2202
   2202 16	chrM
16569 /lustre/bio_running/GTEx_Long_Project/analysis/GTG2/GTG2.genome.chrM.reverse.bam.partially_cleaved_short.bam.depth.txt

#####
Elaborating class: partially_cleaved_long

sample  new_class
GTG2    partially_cleaved_long    2505
dtype: int64

(2505, 16)
Number of reads for current class: 2505
- output mitoBAM for current class: /lustre/bio_running/GTEx_Long_Project/analysis/GTG2/GTG2.genome.chrM.reverse.bam.partially_cleaved_long.bam
- output mitoBAM readslist for current class: /lustre/bio_running/GTEx_Long_Project/analysis/GTG2/GTG2.genome.chrM.reverse.bam.partially_cleaved_long.bam.readslist
- output mitoBAM depth file for current class: /lustre/bio_running/GTEx_Long_Project/analysis/GTG2/GTG2.genome.chrM.reverse.bam.partially_cleaved_long.bam.depth.txt
2505
   2505 16	chrM
16569 /lustre/bio_running/GTEx_Long_Project/analysis/GTG2/GTG2.genome.chrM.reverse.bam.partially_cleaved_long.bam.depth.txt


######################################################################################################
######################################################################################################
######################################################################################################
GTB2 Total Processed samples: 39/73
Shape of df-reads for current sample: (4533, 16)
Unique number of reads: 4533

,Chr,ChrStart,ChrEnd,read_id,MAPQ,strand,read_length,alignment_length,reference_length,polyA_length,sample,overlapping_gene_ids,overlapping_gene_names,n_overlapping_gene_ids,chrM_primary_class,new_class
7702,chrM,189,397,9189708b-a4b5-405e-8803-8398dea36658,60,-,220.0,211,208,49,GTB2,7S,7S,1,complete_gene,fully_cleaved
7703,chrM,189,396,9718b5cf-e462-4993-8e14-0d5e6455a638,60,-,219.0,206,207,44,GTB2,7S,7S,1,complete_gene,fully_cleaved

CHECKING number of reads:
Starting mito-BAM filepath: /lustre/bio_running/GTEx_Long_Project/analysis/GTB2/GTB2.genome.chrM.reverse.bam

#####
Elaborating class: fully_cleaved

sample  new_class
GTB2    fully_cleaved    269
dtype: int64

(269, 16)
Number of reads for current class: 269
- output mitoBAM for current class: /lustre/bio_running/GTEx_Long_Project/analysis/GTB2/GTB2.genome.chrM.reverse.bam.fully_cleaved.bam
- output mitoBAM readslist for current class: /lustre/bio_running/GTEx_Long_Project/analysis/GTB2/GTB2.genome.chrM.reverse.bam.fully_cleaved.bam.readslist
- output mitoBAM depth file for current class: /lustre/bio_running/GTEx_Long_Project/analysis/GTB2/GTB2.genome.chrM.reverse.bam.fully_cleaved.bam.depth.txt
269
    269 16	chrM
16569 /lustre/bio_running/GTEx_Long_Project/analysis/GTB2/GTB2.genome.chrM.reverse.bam.fully_cleaved.bam.depth.txt

#####
Elaborating class: partially_cleaved_short

sample  new_class
GTB2    partially_cleaved_short    1536
dtype: int64

(1536, 16)
Number of reads for current class: 1536
- output mitoBAM for current class: /lustre/bio_running/GTEx_Long_Project/analysis/GTB2/GTB2.genome.chrM.reverse.bam.partially_cleaved_short.bam
- output mitoBAM readslist for current class: /lustre/bio_running/GTEx_Long_Project/analysis/GTB2/GTB2.genome.chrM.reverse.bam.partially_cleaved_short.bam.readslist
- output mitoBAM depth file for current class: /lustre/bio_running/GTEx_Long_Project/analysis/GTB2/GTB2.genome.chrM.reverse.bam.partially_cleaved_short.bam.depth.txt
1536
   1536 16	chrM
16569 /lustre/bio_running/GTEx_Long_Project/analysis/GTB2/GTB2.genome.chrM.reverse.bam.partially_cleaved_short.bam.depth.txt

#####
Elaborating class: partially_cleaved_long

sample  new_class
GTB2    partially_cleaved_long    2728
dtype: int64

(2728, 16)
Number of reads for current class: 2728
- output mitoBAM for current class: /lustre/bio_running/GTEx_Long_Project/analysis/GTB2/GTB2.genome.chrM.reverse.bam.partially_cleaved_long.bam
- output mitoBAM readslist for current class: /lustre/bio_running/GTEx_Long_Project/analysis/GTB2/GTB2.genome.chrM.reverse.bam.partially_cleaved_long.bam.readslist
- output mitoBAM depth file for current class: /lustre/bio_running/GTEx_Long_Project/analysis/GTB2/GTB2.genome.chrM.reverse.bam.partially_cleaved_long.bam.depth.txt
2728
   2728 16	chrM
16569 /lustre/bio_running/GTEx_Long_Project/analysis/GTB2/GTB2.genome.chrM.reverse.bam.partially_cleaved_long.bam.depth.txt


######################################################################################################
######################################################################################################
######################################################################################################
GTE9 Total Processed samples: 40/73
Shape of df-reads for current sample: (3540, 16)
Unique number of reads: 3540

,Chr,ChrStart,ChrEnd,read_id,MAPQ,strand,read_length,alignment_length,reference_length,polyA_length,sample,overlapping_gene_ids,overlapping_gene_names,n_overlapping_gene_ids,chrM_primary_class,new_class
32266,chrM,189,390,ee0b1b54-2e38-4459-b07c-186c034f946e,60,-,214.0,201,201,46,GTE9,7S,7S,1,complete_gene,fully_cleaved
32267,chrM,189,390,60b318fe-0201-4ee8-8f58-10455fda9dde,60,-,218.0,202,201,53,GTE9,7S,7S,1,complete_gene,fully_cleaved

CHECKING number of reads:
Starting mito-BAM filepath: /lustre/bio_running/GTEx_Long_Project/analysis/GTE9/GTE9.genome.chrM.reverse.bam

#####
Elaborating class: fully_cleaved

sample  new_class
GTE9    fully_cleaved    244
dtype: int64

(244, 16)
Number of reads for current class: 244
- output mitoBAM for current class: /lustre/bio_running/GTEx_Long_Project/analysis/GTE9/GTE9.genome.chrM.reverse.bam.fully_cleaved.bam
- output mitoBAM readslist for current class: /lustre/bio_running/GTEx_Long_Project/analysis/GTE9/GTE9.genome.chrM.reverse.bam.fully_cleaved.bam.readslist
- output mitoBAM depth file for current class: /lustre/bio_running/GTEx_Long_Project/analysis/GTE9/GTE9.genome.chrM.reverse.bam.fully_cleaved.bam.depth.txt
244
    244 16	chrM
16569 /lustre/bio_running/GTEx_Long_Project/analysis/GTE9/GTE9.genome.chrM.reverse.bam.fully_cleaved.bam.depth.txt

#####
Elaborating class: partially_cleaved_short

sample  new_class
GTE9    partially_cleaved_short    1198
dtype: int64

(1198, 16)
Number of reads for current class: 1198
- output mitoBAM for current class: /lustre/bio_running/GTEx_Long_Project/analysis/GTE9/GTE9.genome.chrM.reverse.bam.partially_cleaved_short.bam
- output mitoBAM readslist for current class: /lustre/bio_running/GTEx_Long_Project/analysis/GTE9/GTE9.genome.chrM.reverse.bam.partially_cleaved_short.bam.readslist
- output mitoBAM depth file for current class: /lustre/bio_running/GTEx_Long_Project/analysis/GTE9/GTE9.genome.chrM.reverse.bam.partially_cleaved_short.bam.depth.txt
1198
   1198 16	chrM
16569 /lustre/bio_running/GTEx_Long_Project/analysis/GTE9/GTE9.genome.chrM.reverse.bam.partially_cleaved_short.bam.depth.txt

#####
Elaborating class: partially_cleaved_long

sample  new_class
GTE9    partially_cleaved_long    2098
dtype: int64

(2098, 16)
Number of reads for current class: 2098
- output mitoBAM for current class: /lustre/bio_running/GTEx_Long_Project/analysis/GTE9/GTE9.genome.chrM.reverse.bam.partially_cleaved_long.bam
- output mitoBAM readslist for current class: /lustre/bio_running/GTEx_Long_Project/analysis/GTE9/GTE9.genome.chrM.reverse.bam.partially_cleaved_long.bam.readslist
- output mitoBAM depth file for current class: /lustre/bio_running/GTEx_Long_Project/analysis/GTE9/GTE9.genome.chrM.reverse.bam.partially_cleaved_long.bam.depth.txt
2098
   2098 16	chrM
16569 /lustre/bio_running/GTEx_Long_Project/analysis/GTE9/GTE9.genome.chrM.reverse.bam.partially_cleaved_long.bam.depth.txt


######################################################################################################
######################################################################################################
######################################################################################################
GTH3 Total Processed samples: 41/73
Shape of df-reads for current sample: (3535, 16)
Unique number of reads: 3535

,Chr,ChrStart,ChrEnd,read_id,MAPQ,strand,read_length,alignment_length,reference_length,polyA_length,sample,overlapping_gene_ids,overlapping_gene_names,n_overlapping_gene_ids,chrM_primary_class,new_class
48756,chrM,189,397,441ecf22-98e5-4302-a018-c0b1c728bed0,60,-,215.0,208,208,49,GTH3,7S,7S,1,complete_gene,fully_cleaved
48757,chrM,189,397,77988c07-7a60-4c8f-a006-6c649436e88f,60,-,210.0,205,208,27,GTH3,7S,7S,1,complete_gene,fully_cleaved

CHECKING number of reads:
Starting mito-BAM filepath: /lustre/bio_running/GTEx_Long_Project/analysis/GTH3/GTH3.genome.chrM.reverse.bam

#####
Elaborating class: fully_cleaved

sample  new_class
GTH3    fully_cleaved    214
dtype: int64

(214, 16)
Number of reads for current class: 214
- output mitoBAM for current class: /lustre/bio_running/GTEx_Long_Project/analysis/GTH3/GTH3.genome.chrM.reverse.bam.fully_cleaved.bam
- output mitoBAM readslist for current class: /lustre/bio_running/GTEx_Long_Project/analysis/GTH3/GTH3.genome.chrM.reverse.bam.fully_cleaved.bam.readslist
- output mitoBAM depth file for current class: /lustre/bio_running/GTEx_Long_Project/analysis/GTH3/GTH3.genome.chrM.reverse.bam.fully_cleaved.bam.depth.txt
214
    214 16	chrM
16569 /lustre/bio_running/GTEx_Long_Project/analysis/GTH3/GTH3.genome.chrM.reverse.bam.fully_cleaved.bam.depth.txt

#####
Elaborating class: partially_cleaved_short

sample  new_class
GTH3    partially_cleaved_short    2099
dtype: int64

(2099, 16)
Number of reads for current class: 2099
- output mitoBAM for current class: /lustre/bio_running/GTEx_Long_Project/analysis/GTH3/GTH3.genome.chrM.reverse.bam.partially_cleaved_short.bam
- output mitoBAM readslist for current class: /lustre/bio_running/GTEx_Long_Project/analysis/GTH3/GTH3.genome.chrM.reverse.bam.partially_cleaved_short.bam.readslist
- output mitoBAM depth file for current class: /lustre/bio_running/GTEx_Long_Project/analysis/GTH3/GTH3.genome.chrM.reverse.bam.partially_cleaved_short.bam.depth.txt
2099
   2099 16	chrM
16569 /lustre/bio_running/GTEx_Long_Project/analysis/GTH3/GTH3.genome.chrM.reverse.bam.partially_cleaved_short.bam.depth.txt

#####
Elaborating class: partially_cleaved_long

sample  new_class
GTH3    partially_cleaved_long    1222
dtype: int64

(1222, 16)
Number of reads for current class: 1222
- output mitoBAM for current class: /lustre/bio_running/GTEx_Long_Project/analysis/GTH3/GTH3.genome.chrM.reverse.bam.partially_cleaved_long.bam
- output mitoBAM readslist for current class: /lustre/bio_running/GTEx_Long_Project/analysis/GTH3/GTH3.genome.chrM.reverse.bam.partially_cleaved_long.bam.readslist
- output mitoBAM depth file for current class: /lustre/bio_running/GTEx_Long_Project/analysis/GTH3/GTH3.genome.chrM.reverse.bam.partially_cleaved_long.bam.depth.txt
1222
   1222 16	chrM
16569 /lustre/bio_running/GTEx_Long_Project/analysis/GTH3/GTH3.genome.chrM.reverse.bam.partially_cleaved_long.bam.depth.txt


######################################################################################################
######################################################################################################
######################################################################################################
GTF3 Total Processed samples: 42/73
Shape of df-reads for current sample: (3372, 16)
Unique number of reads: 3372

,Chr,ChrStart,ChrEnd,read_id,MAPQ,strand,read_length,alignment_length,reference_length,polyA_length,sample,overlapping_gene_ids,overlapping_gene_names,n_overlapping_gene_ids,chrM_primary_class,new_class
34312,chrM,189,394,cdf35f4a-2218-48e6-88f7-d49fd64be532,60,-,217.0,202,205,44,GTF3,7S,7S,1,complete_gene,fully_cleaved
34313,chrM,189,396,1161e8bd-43ce-4f1c-b9e5-9ff2477d43d3,60,-,217.0,208,207,40,GTF3,7S,7S,1,complete_gene,fully_cleaved

CHECKING number of reads:
Starting mito-BAM filepath: /lustre/bio_running/GTEx_Long_Project/analysis/GTF3/GTF3.genome.chrM.reverse.bam

#####
Elaborating class: fully_cleaved

sample  new_class
GTF3    fully_cleaved    277
dtype: int64

(277, 16)
Number of reads for current class: 277
- output mitoBAM for current class: /lustre/bio_running/GTEx_Long_Project/analysis/GTF3/GTF3.genome.chrM.reverse.bam.fully_cleaved.bam
- output mitoBAM readslist for current class: /lustre/bio_running/GTEx_Long_Project/analysis/GTF3/GTF3.genome.chrM.reverse.bam.fully_cleaved.bam.readslist
- output mitoBAM depth file for current class: /lustre/bio_running/GTEx_Long_Project/analysis/GTF3/GTF3.genome.chrM.reverse.bam.fully_cleaved.bam.depth.txt
277
    277 16	chrM
16569 /lustre/bio_running/GTEx_Long_Project/analysis/GTF3/GTF3.genome.chrM.reverse.bam.fully_cleaved.bam.depth.txt

#####
Elaborating class: partially_cleaved_short

sample  new_class
GTF3    partially_cleaved_short    1332
dtype: int64

(1332, 16)
Number of reads for current class: 1332
- output mitoBAM for current class: /lustre/bio_running/GTEx_Long_Project/analysis/GTF3/GTF3.genome.chrM.reverse.bam.partially_cleaved_short.bam
- output mitoBAM readslist for current class: /lustre/bio_running/GTEx_Long_Project/analysis/GTF3/GTF3.genome.chrM.reverse.bam.partially_cleaved_short.bam.readslist
- output mitoBAM depth file for current class: /lustre/bio_running/GTEx_Long_Project/analysis/GTF3/GTF3.genome.chrM.reverse.bam.partially_cleaved_short.bam.depth.txt
1332
   1332 16	chrM
16569 /lustre/bio_running/GTEx_Long_Project/analysis/GTF3/GTF3.genome.chrM.reverse.bam.partially_cleaved_short.bam.depth.txt

#####
Elaborating class: partially_cleaved_long

sample  new_class
GTF3    partially_cleaved_long    1763
dtype: int64

(1763, 16)
Number of reads for current class: 1763
- output mitoBAM for current class: /lustre/bio_running/GTEx_Long_Project/analysis/GTF3/GTF3.genome.chrM.reverse.bam.partially_cleaved_long.bam
- output mitoBAM readslist for current class: /lustre/bio_running/GTEx_Long_Project/analysis/GTF3/GTF3.genome.chrM.reverse.bam.partially_cleaved_long.bam.readslist
- output mitoBAM depth file for current class: /lustre/bio_running/GTEx_Long_Project/analysis/GTF3/GTF3.genome.chrM.reverse.bam.partially_cleaved_long.bam.depth.txt
1763
   1763 16	chrM
16569 /lustre/bio_running/GTEx_Long_Project/analysis/GTF3/GTF3.genome.chrM.reverse.bam.partially_cleaved_long.bam.depth.txt


######################################################################################################
######################################################################################################
######################################################################################################
GTC1 Total Processed samples: 43/73
Shape of df-reads for current sample: (3293, 16)
Unique number of reads: 3293

,Chr,ChrStart,ChrEnd,read_id,MAPQ,strand,read_length,alignment_length,reference_length,polyA_length,sample,overlapping_gene_ids,overlapping_gene_names,n_overlapping_gene_ids,chrM_primary_class,new_class
12067,chrM,189,397,691135c2-9520-446f-a926-bd94588223c7,60,-,218.0,210,208,38,GTC1,7S,7S,1,complete_gene,fully_cleaved
12068,chrM,189,397,86fda94d-8476-454d-b4c2-b6139bd19738,60,-,240.0,212,208,24,GTC1,7S,7S,1,complete_gene,fully_cleaved

CHECKING number of reads:
Starting mito-BAM filepath: /lustre/bio_running/GTEx_Long_Project/analysis/GTC1/GTC1.genome.chrM.reverse.bam

#####
Elaborating class: fully_cleaved

sample  new_class
GTC1    fully_cleaved    479
dtype: int64

(479, 16)
Number of reads for current class: 479
- output mitoBAM for current class: /lustre/bio_running/GTEx_Long_Project/analysis/GTC1/GTC1.genome.chrM.reverse.bam.fully_cleaved.bam
- output mitoBAM readslist for current class: /lustre/bio_running/GTEx_Long_Project/analysis/GTC1/GTC1.genome.chrM.reverse.bam.fully_cleaved.bam.readslist
- output mitoBAM depth file for current class: /lustre/bio_running/GTEx_Long_Project/analysis/GTC1/GTC1.genome.chrM.reverse.bam.fully_cleaved.bam.depth.txt
479
    479 16	chrM
16569 /lustre/bio_running/GTEx_Long_Project/analysis/GTC1/GTC1.genome.chrM.reverse.bam.fully_cleaved.bam.depth.txt

#####
Elaborating class: partially_cleaved_short

sample  new_class
GTC1    partially_cleaved_short    1927
dtype: int64

(1927, 16)
Number of reads for current class: 1927
- output mitoBAM for current class: /lustre/bio_running/GTEx_Long_Project/analysis/GTC1/GTC1.genome.chrM.reverse.bam.partially_cleaved_short.bam
- output mitoBAM readslist for current class: /lustre/bio_running/GTEx_Long_Project/analysis/GTC1/GTC1.genome.chrM.reverse.bam.partially_cleaved_short.bam.readslist
- output mitoBAM depth file for current class: /lustre/bio_running/GTEx_Long_Project/analysis/GTC1/GTC1.genome.chrM.reverse.bam.partially_cleaved_short.bam.depth.txt
1927
   1927 16	chrM
16569 /lustre/bio_running/GTEx_Long_Project/analysis/GTC1/GTC1.genome.chrM.reverse.bam.partially_cleaved_short.bam.depth.txt

#####
Elaborating class: partially_cleaved_long

sample  new_class
GTC1    partially_cleaved_long    887
dtype: int64

(887, 16)
Number of reads for current class: 887
- output mitoBAM for current class: /lustre/bio_running/GTEx_Long_Project/analysis/GTC1/GTC1.genome.chrM.reverse.bam.partially_cleaved_long.bam
- output mitoBAM readslist for current class: /lustre/bio_running/GTEx_Long_Project/analysis/GTC1/GTC1.genome.chrM.reverse.bam.partially_cleaved_long.bam.readslist
- output mitoBAM depth file for current class: /lustre/bio_running/GTEx_Long_Project/analysis/GTC1/GTC1.genome.chrM.reverse.bam.partially_cleaved_long.bam.depth.txt
887
    887 16	chrM
16569 /lustre/bio_running/GTEx_Long_Project/analysis/GTC1/GTC1.genome.chrM.reverse.bam.partially_cleaved_long.bam.depth.txt


######################################################################################################
######################################################################################################
######################################################################################################
GTE6 Total Processed samples: 44/73
Shape of df-reads for current sample: (3094, 16)
Unique number of reads: 3094

,Chr,ChrStart,ChrEnd,read_id,MAPQ,strand,read_length,alignment_length,reference_length,polyA_length,sample,overlapping_gene_ids,overlapping_gene_names,n_overlapping_gene_ids,chrM_primary_class,new_class
31635,chrM,189,397,93e258ab-acc0-41bb-a0bb-a63b328db66f,60,-,239.0,212,208,27,GTE6,7S,7S,1,complete_gene,fully_cleaved
31636,chrM,189,393,a7644013-22d6-4a91-a56e-a247a30bcda0,60,-,211.0,202,204,33,GTE6,7S,7S,1,complete_gene,fully_cleaved

CHECKING number of reads:
Starting mito-BAM filepath: /lustre/bio_running/GTEx_Long_Project/analysis/GTE6/GTE6.genome.chrM.reverse.bam

#####
Elaborating class: fully_cleaved

sample  new_class
GTE6    fully_cleaved    185
dtype: int64

(185, 16)
Number of reads for current class: 185
- output mitoBAM for current class: /lustre/bio_running/GTEx_Long_Project/analysis/GTE6/GTE6.genome.chrM.reverse.bam.fully_cleaved.bam
- output mitoBAM readslist for current class: /lustre/bio_running/GTEx_Long_Project/analysis/GTE6/GTE6.genome.chrM.reverse.bam.fully_cleaved.bam.readslist
- output mitoBAM depth file for current class: /lustre/bio_running/GTEx_Long_Project/analysis/GTE6/GTE6.genome.chrM.reverse.bam.fully_cleaved.bam.depth.txt
185
    185 16	chrM
16569 /lustre/bio_running/GTEx_Long_Project/analysis/GTE6/GTE6.genome.chrM.reverse.bam.fully_cleaved.bam.depth.txt

#####
Elaborating class: partially_cleaved_short

sample  new_class
GTE6    partially_cleaved_short    1572
dtype: int64

(1572, 16)
Number of reads for current class: 1572
- output mitoBAM for current class: /lustre/bio_running/GTEx_Long_Project/analysis/GTE6/GTE6.genome.chrM.reverse.bam.partially_cleaved_short.bam
- output mitoBAM readslist for current class: /lustre/bio_running/GTEx_Long_Project/analysis/GTE6/GTE6.genome.chrM.reverse.bam.partially_cleaved_short.bam.readslist
- output mitoBAM depth file for current class: /lustre/bio_running/GTEx_Long_Project/analysis/GTE6/GTE6.genome.chrM.reverse.bam.partially_cleaved_short.bam.depth.txt
1572
   1572 16	chrM
16569 /lustre/bio_running/GTEx_Long_Project/analysis/GTE6/GTE6.genome.chrM.reverse.bam.partially_cleaved_short.bam.depth.txt

#####
Elaborating class: partially_cleaved_long

sample  new_class
GTE6    partially_cleaved_long    1337
dtype: int64

(1337, 16)
Number of reads for current class: 1337
- output mitoBAM for current class: /lustre/bio_running/GTEx_Long_Project/analysis/GTE6/GTE6.genome.chrM.reverse.bam.partially_cleaved_long.bam
- output mitoBAM readslist for current class: /lustre/bio_running/GTEx_Long_Project/analysis/GTE6/GTE6.genome.chrM.reverse.bam.partially_cleaved_long.bam.readslist
- output mitoBAM depth file for current class: /lustre/bio_running/GTEx_Long_Project/analysis/GTE6/GTE6.genome.chrM.reverse.bam.partially_cleaved_long.bam.depth.txt
1337
   1337 16	chrM
16569 /lustre/bio_running/GTEx_Long_Project/analysis/GTE6/GTE6.genome.chrM.reverse.bam.partially_cleaved_long.bam.depth.txt


######################################################################################################
######################################################################################################
######################################################################################################
GTH9 Total Processed samples: 45/73
Shape of df-reads for current sample: (2993, 16)
Unique number of reads: 2993

,Chr,ChrStart,ChrEnd,read_id,MAPQ,strand,read_length,alignment_length,reference_length,polyA_length,sample,overlapping_gene_ids,overlapping_gene_names,n_overlapping_gene_ids,chrM_primary_class,new_class
53286,chrM,189,397,7349423d-8916-4085-b305-04bfe42891e7,60,-,224.0,210,208,0,GTH9,7S,7S,1,complete_gene,fully_cleaved
53287,chrM,189,397,d00db725-bde7-4374-aced-b7a8b08a2615,60,-,215.0,209,208,36,GTH9,7S,7S,1,complete_gene,fully_cleaved

CHECKING number of reads:
Starting mito-BAM filepath: /lustre/bio_running/GTEx_Long_Project/analysis/GTH9/GTH9.genome.chrM.reverse.bam

#####
Elaborating class: fully_cleaved

sample  new_class
GTH9    fully_cleaved    266
dtype: int64

(266, 16)
Number of reads for current class: 266
- output mitoBAM for current class: /lustre/bio_running/GTEx_Long_Project/analysis/GTH9/GTH9.genome.chrM.reverse.bam.fully_cleaved.bam
- output mitoBAM readslist for current class: /lustre/bio_running/GTEx_Long_Project/analysis/GTH9/GTH9.genome.chrM.reverse.bam.fully_cleaved.bam.readslist
- output mitoBAM depth file for current class: /lustre/bio_running/GTEx_Long_Project/analysis/GTH9/GTH9.genome.chrM.reverse.bam.fully_cleaved.bam.depth.txt
266
    266 16	chrM
16569 /lustre/bio_running/GTEx_Long_Project/analysis/GTH9/GTH9.genome.chrM.reverse.bam.fully_cleaved.bam.depth.txt

#####
Elaborating class: partially_cleaved_short

sample  new_class
GTH9    partially_cleaved_short    1568
dtype: int64

(1568, 16)
Number of reads for current class: 1568
- output mitoBAM for current class: /lustre/bio_running/GTEx_Long_Project/analysis/GTH9/GTH9.genome.chrM.reverse.bam.partially_cleaved_short.bam
- output mitoBAM readslist for current class: /lustre/bio_running/GTEx_Long_Project/analysis/GTH9/GTH9.genome.chrM.reverse.bam.partially_cleaved_short.bam.readslist
- output mitoBAM depth file for current class: /lustre/bio_running/GTEx_Long_Project/analysis/GTH9/GTH9.genome.chrM.reverse.bam.partially_cleaved_short.bam.depth.txt
1568
   1568 16	chrM
16569 /lustre/bio_running/GTEx_Long_Project/analysis/GTH9/GTH9.genome.chrM.reverse.bam.partially_cleaved_short.bam.depth.txt

#####
Elaborating class: partially_cleaved_long

sample  new_class
GTH9    partially_cleaved_long    1159
dtype: int64

(1159, 16)
Number of reads for current class: 1159
- output mitoBAM for current class: /lustre/bio_running/GTEx_Long_Project/analysis/GTH9/GTH9.genome.chrM.reverse.bam.partially_cleaved_long.bam
- output mitoBAM readslist for current class: /lustre/bio_running/GTEx_Long_Project/analysis/GTH9/GTH9.genome.chrM.reverse.bam.partially_cleaved_long.bam.readslist
- output mitoBAM depth file for current class: /lustre/bio_running/GTEx_Long_Project/analysis/GTH9/GTH9.genome.chrM.reverse.bam.partially_cleaved_long.bam.depth.txt
1159
   1159 16	chrM
16569 /lustre/bio_running/GTEx_Long_Project/analysis/GTH9/GTH9.genome.chrM.reverse.bam.partially_cleaved_long.bam.depth.txt


######################################################################################################
######################################################################################################
######################################################################################################
GTE3 Total Processed samples: 46/73
Shape of df-reads for current sample: (2991, 16)
Unique number of reads: 2991

,Chr,ChrStart,ChrEnd,read_id,MAPQ,strand,read_length,alignment_length,reference_length,polyA_length,sample,overlapping_gene_ids,overlapping_gene_names,n_overlapping_gene_ids,chrM_primary_class,new_class
31345,chrM,189,398,e11d5b35-11d3-406e-8f10-3cc0d3ae0253,60,-,220.0,210,209,24,GTE3,7S,7S,1,complete_gene,fully_cleaved
31346,chrM,189,397,0b0b0e3b-92c7-4159-932d-ec33ce4e759a,60,-,224.0,211,208,21,GTE3,7S,7S,1,complete_gene,fully_cleaved

CHECKING number of reads:
Starting mito-BAM filepath: /lustre/bio_running/GTEx_Long_Project/analysis/GTE3/GTE3.genome.chrM.reverse.bam

#####
Elaborating class: fully_cleaved

sample  new_class
GTE3    fully_cleaved    142
dtype: int64

(142, 16)
Number of reads for current class: 142
- output mitoBAM for current class: /lustre/bio_running/GTEx_Long_Project/analysis/GTE3/GTE3.genome.chrM.reverse.bam.fully_cleaved.bam
- output mitoBAM readslist for current class: /lustre/bio_running/GTEx_Long_Project/analysis/GTE3/GTE3.genome.chrM.reverse.bam.fully_cleaved.bam.readslist
- output mitoBAM depth file for current class: /lustre/bio_running/GTEx_Long_Project/analysis/GTE3/GTE3.genome.chrM.reverse.bam.fully_cleaved.bam.depth.txt
142
    142 16	chrM
16569 /lustre/bio_running/GTEx_Long_Project/analysis/GTE3/GTE3.genome.chrM.reverse.bam.fully_cleaved.bam.depth.txt

#####
Elaborating class: partially_cleaved_short

sample  new_class
GTE3    partially_cleaved_short    1343
dtype: int64

(1343, 16)
Number of reads for current class: 1343
- output mitoBAM for current class: /lustre/bio_running/GTEx_Long_Project/analysis/GTE3/GTE3.genome.chrM.reverse.bam.partially_cleaved_short.bam
- output mitoBAM readslist for current class: /lustre/bio_running/GTEx_Long_Project/analysis/GTE3/GTE3.genome.chrM.reverse.bam.partially_cleaved_short.bam.readslist
- output mitoBAM depth file for current class: /lustre/bio_running/GTEx_Long_Project/analysis/GTE3/GTE3.genome.chrM.reverse.bam.partially_cleaved_short.bam.depth.txt
1343
   1343 16	chrM
16569 /lustre/bio_running/GTEx_Long_Project/analysis/GTE3/GTE3.genome.chrM.reverse.bam.partially_cleaved_short.bam.depth.txt

#####
Elaborating class: partially_cleaved_long

sample  new_class
GTE3    partially_cleaved_long    1506
dtype: int64

(1506, 16)
Number of reads for current class: 1506
- output mitoBAM for current class: /lustre/bio_running/GTEx_Long_Project/analysis/GTE3/GTE3.genome.chrM.reverse.bam.partially_cleaved_long.bam
- output mitoBAM readslist for current class: /lustre/bio_running/GTEx_Long_Project/analysis/GTE3/GTE3.genome.chrM.reverse.bam.partially_cleaved_long.bam.readslist
- output mitoBAM depth file for current class: /lustre/bio_running/GTEx_Long_Project/analysis/GTE3/GTE3.genome.chrM.reverse.bam.partially_cleaved_long.bam.depth.txt
1506
   1506 16	chrM
16569 /lustre/bio_running/GTEx_Long_Project/analysis/GTE3/GTE3.genome.chrM.reverse.bam.partially_cleaved_long.bam.depth.txt


######################################################################################################
######################################################################################################
######################################################################################################
GTB5 Total Processed samples: 47/73
Shape of df-reads for current sample: (2929, 16)
Unique number of reads: 2929

,Chr,ChrStart,ChrEnd,read_id,MAPQ,strand,read_length,alignment_length,reference_length,polyA_length,sample,overlapping_gene_ids,overlapping_gene_names,n_overlapping_gene_ids,chrM_primary_class,new_class
10442,chrM,189,397,23decb38-3e72-4403-a5ae-29362a41ac68,60,-,223.0,210,208,57,GTB5,7S,7S,1,complete_gene,fully_cleaved
10443,chrM,189,397,a1734c44-ac73-43da-92a4-57ac39082d6e,60,-,237.0,209,208,24,GTB5,7S,7S,1,complete_gene,fully_cleaved

CHECKING number of reads:
Starting mito-BAM filepath: /lustre/bio_running/GTEx_Long_Project/analysis/GTB5/GTB5.genome.chrM.reverse.bam

#####
Elaborating class: fully_cleaved

sample  new_class
GTB5    fully_cleaved    145
dtype: int64

(145, 16)
Number of reads for current class: 145
- output mitoBAM for current class: /lustre/bio_running/GTEx_Long_Project/analysis/GTB5/GTB5.genome.chrM.reverse.bam.fully_cleaved.bam
- output mitoBAM readslist for current class: /lustre/bio_running/GTEx_Long_Project/analysis/GTB5/GTB5.genome.chrM.reverse.bam.fully_cleaved.bam.readslist
- output mitoBAM depth file for current class: /lustre/bio_running/GTEx_Long_Project/analysis/GTB5/GTB5.genome.chrM.reverse.bam.fully_cleaved.bam.depth.txt
145
    145 16	chrM
16569 /lustre/bio_running/GTEx_Long_Project/analysis/GTB5/GTB5.genome.chrM.reverse.bam.fully_cleaved.bam.depth.txt

#####
Elaborating class: partially_cleaved_short

sample  new_class
GTB5    partially_cleaved_short    1384
dtype: int64

(1384, 16)
Number of reads for current class: 1384
- output mitoBAM for current class: /lustre/bio_running/GTEx_Long_Project/analysis/GTB5/GTB5.genome.chrM.reverse.bam.partially_cleaved_short.bam
- output mitoBAM readslist for current class: /lustre/bio_running/GTEx_Long_Project/analysis/GTB5/GTB5.genome.chrM.reverse.bam.partially_cleaved_short.bam.readslist
- output mitoBAM depth file for current class: /lustre/bio_running/GTEx_Long_Project/analysis/GTB5/GTB5.genome.chrM.reverse.bam.partially_cleaved_short.bam.depth.txt
1384
   1384 16	chrM
16569 /lustre/bio_running/GTEx_Long_Project/analysis/GTB5/GTB5.genome.chrM.reverse.bam.partially_cleaved_short.bam.depth.txt

#####
Elaborating class: partially_cleaved_long

sample  new_class
GTB5    partially_cleaved_long    1400
dtype: int64

(1400, 16)
Number of reads for current class: 1400
- output mitoBAM for current class: /lustre/bio_running/GTEx_Long_Project/analysis/GTB5/GTB5.genome.chrM.reverse.bam.partially_cleaved_long.bam
- output mitoBAM readslist for current class: /lustre/bio_running/GTEx_Long_Project/analysis/GTB5/GTB5.genome.chrM.reverse.bam.partially_cleaved_long.bam.readslist
- output mitoBAM depth file for current class: /lustre/bio_running/GTEx_Long_Project/analysis/GTB5/GTB5.genome.chrM.reverse.bam.partially_cleaved_long.bam.depth.txt
1400
   1400 16	chrM
16569 /lustre/bio_running/GTEx_Long_Project/analysis/GTB5/GTB5.genome.chrM.reverse.bam.partially_cleaved_long.bam.depth.txt


######################################################################################################
######################################################################################################
######################################################################################################
GTG8 Total Processed samples: 48/73
Shape of df-reads for current sample: (2831, 16)
Unique number of reads: 2831

,Chr,ChrStart,ChrEnd,read_id,MAPQ,strand,read_length,alignment_length,reference_length,polyA_length,sample,overlapping_gene_ids,overlapping_gene_names,n_overlapping_gene_ids,chrM_primary_class,new_class
46460,chrM,189,397,3459435c-33d0-4e5d-96b3-bcde879d7e72,60,-,239.0,212,208,20,GTG8,7S,7S,1,complete_gene,fully_cleaved
46461,chrM,189,397,6108bd99-6c47-4bd7-8639-00e7ea764aaa,60,-,220.0,211,208,44,GTG8,7S,7S,1,complete_gene,fully_cleaved

CHECKING number of reads:
Starting mito-BAM filepath: /lustre/bio_running/GTEx_Long_Project/analysis/GTG8/GTG8.genome.chrM.reverse.bam

#####
Elaborating class: fully_cleaved

sample  new_class
GTG8    fully_cleaved    133
dtype: int64

(133, 16)
Number of reads for current class: 133
- output mitoBAM for current class: /lustre/bio_running/GTEx_Long_Project/analysis/GTG8/GTG8.genome.chrM.reverse.bam.fully_cleaved.bam
- output mitoBAM readslist for current class: /lustre/bio_running/GTEx_Long_Project/analysis/GTG8/GTG8.genome.chrM.reverse.bam.fully_cleaved.bam.readslist
- output mitoBAM depth file for current class: /lustre/bio_running/GTEx_Long_Project/analysis/GTG8/GTG8.genome.chrM.reverse.bam.fully_cleaved.bam.depth.txt
133
    133 16	chrM
16569 /lustre/bio_running/GTEx_Long_Project/analysis/GTG8/GTG8.genome.chrM.reverse.bam.fully_cleaved.bam.depth.txt

#####
Elaborating class: partially_cleaved_short

sample  new_class
GTG8    partially_cleaved_short    1432
dtype: int64

(1432, 16)
Number of reads for current class: 1432
- output mitoBAM for current class: /lustre/bio_running/GTEx_Long_Project/analysis/GTG8/GTG8.genome.chrM.reverse.bam.partially_cleaved_short.bam
- output mitoBAM readslist for current class: /lustre/bio_running/GTEx_Long_Project/analysis/GTG8/GTG8.genome.chrM.reverse.bam.partially_cleaved_short.bam.readslist
- output mitoBAM depth file for current class: /lustre/bio_running/GTEx_Long_Project/analysis/GTG8/GTG8.genome.chrM.reverse.bam.partially_cleaved_short.bam.depth.txt
1432
   1432 16	chrM
16569 /lustre/bio_running/GTEx_Long_Project/analysis/GTG8/GTG8.genome.chrM.reverse.bam.partially_cleaved_short.bam.depth.txt

#####
Elaborating class: partially_cleaved_long

sample  new_class
GTG8    partially_cleaved_long    1266
dtype: int64

(1266, 16)
Number of reads for current class: 1266
- output mitoBAM for current class: /lustre/bio_running/GTEx_Long_Project/analysis/GTG8/GTG8.genome.chrM.reverse.bam.partially_cleaved_long.bam
- output mitoBAM readslist for current class: /lustre/bio_running/GTEx_Long_Project/analysis/GTG8/GTG8.genome.chrM.reverse.bam.partially_cleaved_long.bam.readslist
- output mitoBAM depth file for current class: /lustre/bio_running/GTEx_Long_Project/analysis/GTG8/GTG8.genome.chrM.reverse.bam.partially_cleaved_long.bam.depth.txt
1266
   1266 16	chrM
16569 /lustre/bio_running/GTEx_Long_Project/analysis/GTG8/GTG8.genome.chrM.reverse.bam.partially_cleaved_long.bam.depth.txt


######################################################################################################
######################################################################################################
######################################################################################################
GTH1 Total Processed samples: 49/73
Shape of df-reads for current sample: (2827, 16)
Unique number of reads: 2827

,Chr,ChrStart,ChrEnd,read_id,MAPQ,strand,read_length,alignment_length,reference_length,polyA_length,sample,overlapping_gene_ids,overlapping_gene_names,n_overlapping_gene_ids,chrM_primary_class,new_class
47758,chrM,189,397,d49a6eb6-a055-484a-b563-8abb2b7a9fa3,60,-,215.0,212,208,35,GTH1,7S,7S,1,complete_gene,fully_cleaved
47759,chrM,189,394,5ae52597-4dd5-4162-b671-dfebba4a6014,60,-,223.0,207,205,38,GTH1,7S,7S,1,complete_gene,fully_cleaved

CHECKING number of reads:
Starting mito-BAM filepath: /lustre/bio_running/GTEx_Long_Project/analysis/GTH1/GTH1.genome.chrM.reverse.bam

#####
Elaborating class: fully_cleaved

sample  new_class
GTH1    fully_cleaved    120
dtype: int64

(120, 16)
Number of reads for current class: 120
- output mitoBAM for current class: /lustre/bio_running/GTEx_Long_Project/analysis/GTH1/GTH1.genome.chrM.reverse.bam.fully_cleaved.bam
- output mitoBAM readslist for current class: /lustre/bio_running/GTEx_Long_Project/analysis/GTH1/GTH1.genome.chrM.reverse.bam.fully_cleaved.bam.readslist
- output mitoBAM depth file for current class: /lustre/bio_running/GTEx_Long_Project/analysis/GTH1/GTH1.genome.chrM.reverse.bam.fully_cleaved.bam.depth.txt
120
    120 16	chrM
16569 /lustre/bio_running/GTEx_Long_Project/analysis/GTH1/GTH1.genome.chrM.reverse.bam.fully_cleaved.bam.depth.txt

#####
Elaborating class: partially_cleaved_short

sample  new_class
GTH1    partially_cleaved_short    829
dtype: int64

(829, 16)
Number of reads for current class: 829
- output mitoBAM for current class: /lustre/bio_running/GTEx_Long_Project/analysis/GTH1/GTH1.genome.chrM.reverse.bam.partially_cleaved_short.bam
- output mitoBAM readslist for current class: /lustre/bio_running/GTEx_Long_Project/analysis/GTH1/GTH1.genome.chrM.reverse.bam.partially_cleaved_short.bam.readslist
- output mitoBAM depth file for current class: /lustre/bio_running/GTEx_Long_Project/analysis/GTH1/GTH1.genome.chrM.reverse.bam.partially_cleaved_short.bam.depth.txt
829
    829 16	chrM
16569 /lustre/bio_running/GTEx_Long_Project/analysis/GTH1/GTH1.genome.chrM.reverse.bam.partially_cleaved_short.bam.depth.txt

#####
Elaborating class: partially_cleaved_long

sample  new_class
GTH1    partially_cleaved_long    1878
dtype: int64

(1878, 16)
Number of reads for current class: 1878
- output mitoBAM for current class: /lustre/bio_running/GTEx_Long_Project/analysis/GTH1/GTH1.genome.chrM.reverse.bam.partially_cleaved_long.bam
- output mitoBAM readslist for current class: /lustre/bio_running/GTEx_Long_Project/analysis/GTH1/GTH1.genome.chrM.reverse.bam.partially_cleaved_long.bam.readslist
- output mitoBAM depth file for current class: /lustre/bio_running/GTEx_Long_Project/analysis/GTH1/GTH1.genome.chrM.reverse.bam.partially_cleaved_long.bam.depth.txt
1878
   1878 16	chrM
16569 /lustre/bio_running/GTEx_Long_Project/analysis/GTH1/GTH1.genome.chrM.reverse.bam.partially_cleaved_long.bam.depth.txt


######################################################################################################
######################################################################################################
######################################################################################################
GTA5 Total Processed samples: 50/73
Shape of df-reads for current sample: (2822, 16)
Unique number of reads: 2822

,Chr,ChrStart,ChrEnd,read_id,MAPQ,strand,read_length,alignment_length,reference_length,polyA_length,sample,overlapping_gene_ids,overlapping_gene_names,n_overlapping_gene_ids,chrM_primary_class,new_class
3580,chrM,189,397,7bf7c5a6-edfa-4c65-8661-89b1808fa465,60,-,217.0,209,208,23,GTA5,7S,7S,1,complete_gene,fully_cleaved
3581,chrM,189,397,cfa51207-efe7-4f66-8a8c-51235b6623da,60,-,213.0,209,208,41,GTA5,7S,7S,1,complete_gene,fully_cleaved

CHECKING number of reads:
Starting mito-BAM filepath: /lustre/bio_running/GTEx_Long_Project/analysis/GTA5/GTA5.genome.chrM.reverse.bam

#####
Elaborating class: fully_cleaved

sample  new_class
GTA5    fully_cleaved    134
dtype: int64

(134, 16)
Number of reads for current class: 134
- output mitoBAM for current class: /lustre/bio_running/GTEx_Long_Project/analysis/GTA5/GTA5.genome.chrM.reverse.bam.fully_cleaved.bam
- output mitoBAM readslist for current class: /lustre/bio_running/GTEx_Long_Project/analysis/GTA5/GTA5.genome.chrM.reverse.bam.fully_cleaved.bam.readslist
- output mitoBAM depth file for current class: /lustre/bio_running/GTEx_Long_Project/analysis/GTA5/GTA5.genome.chrM.reverse.bam.fully_cleaved.bam.depth.txt
134
    134 16	chrM
16569 /lustre/bio_running/GTEx_Long_Project/analysis/GTA5/GTA5.genome.chrM.reverse.bam.fully_cleaved.bam.depth.txt

#####
Elaborating class: partially_cleaved_short

sample  new_class
GTA5    partially_cleaved_short    1152
dtype: int64

(1152, 16)
Number of reads for current class: 1152
- output mitoBAM for current class: /lustre/bio_running/GTEx_Long_Project/analysis/GTA5/GTA5.genome.chrM.reverse.bam.partially_cleaved_short.bam
- output mitoBAM readslist for current class: /lustre/bio_running/GTEx_Long_Project/analysis/GTA5/GTA5.genome.chrM.reverse.bam.partially_cleaved_short.bam.readslist
- output mitoBAM depth file for current class: /lustre/bio_running/GTEx_Long_Project/analysis/GTA5/GTA5.genome.chrM.reverse.bam.partially_cleaved_short.bam.depth.txt
1152
   1152 16	chrM
16569 /lustre/bio_running/GTEx_Long_Project/analysis/GTA5/GTA5.genome.chrM.reverse.bam.partially_cleaved_short.bam.depth.txt

#####
Elaborating class: partially_cleaved_long

sample  new_class
GTA5    partially_cleaved_long    1536
dtype: int64

(1536, 16)
Number of reads for current class: 1536
- output mitoBAM for current class: /lustre/bio_running/GTEx_Long_Project/analysis/GTA5/GTA5.genome.chrM.reverse.bam.partially_cleaved_long.bam
- output mitoBAM readslist for current class: /lustre/bio_running/GTEx_Long_Project/analysis/GTA5/GTA5.genome.chrM.reverse.bam.partially_cleaved_long.bam.readslist
- output mitoBAM depth file for current class: /lustre/bio_running/GTEx_Long_Project/analysis/GTA5/GTA5.genome.chrM.reverse.bam.partially_cleaved_long.bam.depth.txt
1536
   1536 16	chrM
16569 /lustre/bio_running/GTEx_Long_Project/analysis/GTA5/GTA5.genome.chrM.reverse.bam.partially_cleaved_long.bam.depth.txt


######################################################################################################
######################################################################################################
######################################################################################################
GTE7 Total Processed samples: 51/73
Shape of df-reads for current sample: (2751, 16)
Unique number of reads: 2751

,Chr,ChrStart,ChrEnd,read_id,MAPQ,strand,read_length,alignment_length,reference_length,polyA_length,sample,overlapping_gene_ids,overlapping_gene_names,n_overlapping_gene_ids,chrM_primary_class,new_class
31820,chrM,189,395,e1fc3efa-a4f1-4e38-8ec8-d1e7008a706c,60,-,299.0,206,206,0,GTE7,7S,7S,1,complete_gene,fully_cleaved
31821,chrM,189,389,92387628-9795-4f79-90ae-af5be05bac1d,60,-,217.0,201,200,20,GTE7,7S,7S,1,complete_gene,fully_cleaved

CHECKING number of reads:
Starting mito-BAM filepath: /lustre/bio_running/GTEx_Long_Project/analysis/GTE7/GTE7.genome.chrM.reverse.bam

#####
Elaborating class: fully_cleaved

sample  new_class
GTE7    fully_cleaved    346
dtype: int64

(346, 16)
Number of reads for current class: 346
- output mitoBAM for current class: /lustre/bio_running/GTEx_Long_Project/analysis/GTE7/GTE7.genome.chrM.reverse.bam.fully_cleaved.bam
- output mitoBAM readslist for current class: /lustre/bio_running/GTEx_Long_Project/analysis/GTE7/GTE7.genome.chrM.reverse.bam.fully_cleaved.bam.readslist
- output mitoBAM depth file for current class: /lustre/bio_running/GTEx_Long_Project/analysis/GTE7/GTE7.genome.chrM.reverse.bam.fully_cleaved.bam.depth.txt
346
    346 16	chrM
16569 /lustre/bio_running/GTEx_Long_Project/analysis/GTE7/GTE7.genome.chrM.reverse.bam.fully_cleaved.bam.depth.txt

#####
Elaborating class: partially_cleaved_short

sample  new_class
GTE7    partially_cleaved_short    1857
dtype: int64

(1857, 16)
Number of reads for current class: 1857
- output mitoBAM for current class: /lustre/bio_running/GTEx_Long_Project/analysis/GTE7/GTE7.genome.chrM.reverse.bam.partially_cleaved_short.bam
- output mitoBAM readslist for current class: /lustre/bio_running/GTEx_Long_Project/analysis/GTE7/GTE7.genome.chrM.reverse.bam.partially_cleaved_short.bam.readslist
- output mitoBAM depth file for current class: /lustre/bio_running/GTEx_Long_Project/analysis/GTE7/GTE7.genome.chrM.reverse.bam.partially_cleaved_short.bam.depth.txt
1857
   1857 16	chrM
16569 /lustre/bio_running/GTEx_Long_Project/analysis/GTE7/GTE7.genome.chrM.reverse.bam.partially_cleaved_short.bam.depth.txt

#####
Elaborating class: partially_cleaved_long

sample  new_class
GTE7    partially_cleaved_long    548
dtype: int64

(548, 16)
Number of reads for current class: 548
- output mitoBAM for current class: /lustre/bio_running/GTEx_Long_Project/analysis/GTE7/GTE7.genome.chrM.reverse.bam.partially_cleaved_long.bam
- output mitoBAM readslist for current class: /lustre/bio_running/GTEx_Long_Project/analysis/GTE7/GTE7.genome.chrM.reverse.bam.partially_cleaved_long.bam.readslist
- output mitoBAM depth file for current class: /lustre/bio_running/GTEx_Long_Project/analysis/GTE7/GTE7.genome.chrM.reverse.bam.partially_cleaved_long.bam.depth.txt
548
    548 16	chrM
16569 /lustre/bio_running/GTEx_Long_Project/analysis/GTE7/GTE7.genome.chrM.reverse.bam.partially_cleaved_long.bam.depth.txt


######################################################################################################
######################################################################################################
######################################################################################################
GTB8 Total Processed samples: 52/73
Shape of df-reads for current sample: (2731, 16)
Unique number of reads: 2731

,Chr,ChrStart,ChrEnd,read_id,MAPQ,strand,read_length,alignment_length,reference_length,polyA_length,sample,overlapping_gene_ids,overlapping_gene_names,n_overlapping_gene_ids,chrM_primary_class,new_class
11626,chrM,189,400,823d25f7-7a4c-47d7-ab99-58e1c89a6c2b,60,-,211.0,209,211,46,GTB8,7S,7S,1,complete_gene,fully_cleaved
11627,chrM,189,398,ebc9a2c2-d612-4335-bd8c-28d6794abcf5,60,-,214.0,203,209,13,GTB8,7S,7S,1,complete_gene,fully_cleaved

CHECKING number of reads:
Starting mito-BAM filepath: /lustre/bio_running/GTEx_Long_Project/analysis/GTB8/GTB8.genome.chrM.reverse.bam

#####
Elaborating class: fully_cleaved

sample  new_class
GTB8    fully_cleaved    384
dtype: int64

(384, 16)
Number of reads for current class: 384
- output mitoBAM for current class: /lustre/bio_running/GTEx_Long_Project/analysis/GTB8/GTB8.genome.chrM.reverse.bam.fully_cleaved.bam
- output mitoBAM readslist for current class: /lustre/bio_running/GTEx_Long_Project/analysis/GTB8/GTB8.genome.chrM.reverse.bam.fully_cleaved.bam.readslist
- output mitoBAM depth file for current class: /lustre/bio_running/GTEx_Long_Project/analysis/GTB8/GTB8.genome.chrM.reverse.bam.fully_cleaved.bam.depth.txt
384
    384 16	chrM
16569 /lustre/bio_running/GTEx_Long_Project/analysis/GTB8/GTB8.genome.chrM.reverse.bam.fully_cleaved.bam.depth.txt

#####
Elaborating class: partially_cleaved_short

sample  new_class
GTB8    partially_cleaved_short    1597
dtype: int64

(1597, 16)
Number of reads for current class: 1597
- output mitoBAM for current class: /lustre/bio_running/GTEx_Long_Project/analysis/GTB8/GTB8.genome.chrM.reverse.bam.partially_cleaved_short.bam
- output mitoBAM readslist for current class: /lustre/bio_running/GTEx_Long_Project/analysis/GTB8/GTB8.genome.chrM.reverse.bam.partially_cleaved_short.bam.readslist
- output mitoBAM depth file for current class: /lustre/bio_running/GTEx_Long_Project/analysis/GTB8/GTB8.genome.chrM.reverse.bam.partially_cleaved_short.bam.depth.txt
1597
   1597 16	chrM
16569 /lustre/bio_running/GTEx_Long_Project/analysis/GTB8/GTB8.genome.chrM.reverse.bam.partially_cleaved_short.bam.depth.txt

#####
Elaborating class: partially_cleaved_long

sample  new_class
GTB8    partially_cleaved_long    750
dtype: int64

(750, 16)
Number of reads for current class: 750
- output mitoBAM for current class: /lustre/bio_running/GTEx_Long_Project/analysis/GTB8/GTB8.genome.chrM.reverse.bam.partially_cleaved_long.bam
- output mitoBAM readslist for current class: /lustre/bio_running/GTEx_Long_Project/analysis/GTB8/GTB8.genome.chrM.reverse.bam.partially_cleaved_long.bam.readslist
- output mitoBAM depth file for current class: /lustre/bio_running/GTEx_Long_Project/analysis/GTB8/GTB8.genome.chrM.reverse.bam.partially_cleaved_long.bam.depth.txt
750
    750 16	chrM
16569 /lustre/bio_running/GTEx_Long_Project/analysis/GTB8/GTB8.genome.chrM.reverse.bam.partially_cleaved_long.bam.depth.txt


######################################################################################################
######################################################################################################
######################################################################################################
GTG6 Total Processed samples: 53/73
Shape of df-reads for current sample: (2694, 16)
Unique number of reads: 2694

,Chr,ChrStart,ChrEnd,read_id,MAPQ,strand,read_length,alignment_length,reference_length,polyA_length,sample,overlapping_gene_ids,overlapping_gene_names,n_overlapping_gene_ids,chrM_primary_class,new_class
45179,chrM,189,386,d50ad7ae-e139-47ed-8790-a48150ae3cf6,60,-,204.0,195,197,43,GTG6,7S,7S,1,complete_gene,fully_cleaved
45180,chrM,189,397,5e299c2c-1beb-4e72-8a53-f41c03e92df9,60,-,219.0,209,208,40,GTG6,7S,7S,1,complete_gene,fully_cleaved

CHECKING number of reads:
Starting mito-BAM filepath: /lustre/bio_running/GTEx_Long_Project/analysis/GTG6/GTG6.genome.chrM.reverse.bam

#####
Elaborating class: fully_cleaved

sample  new_class
GTG6    fully_cleaved    358
dtype: int64

(358, 16)
Number of reads for current class: 358
- output mitoBAM for current class: /lustre/bio_running/GTEx_Long_Project/analysis/GTG6/GTG6.genome.chrM.reverse.bam.fully_cleaved.bam
- output mitoBAM readslist for current class: /lustre/bio_running/GTEx_Long_Project/analysis/GTG6/GTG6.genome.chrM.reverse.bam.fully_cleaved.bam.readslist
- output mitoBAM depth file for current class: /lustre/bio_running/GTEx_Long_Project/analysis/GTG6/GTG6.genome.chrM.reverse.bam.fully_cleaved.bam.depth.txt
358
    358 16	chrM
16569 /lustre/bio_running/GTEx_Long_Project/analysis/GTG6/GTG6.genome.chrM.reverse.bam.fully_cleaved.bam.depth.txt

#####
Elaborating class: partially_cleaved_short

sample  new_class
GTG6    partially_cleaved_short    1576
dtype: int64

(1576, 16)
Number of reads for current class: 1576
- output mitoBAM for current class: /lustre/bio_running/GTEx_Long_Project/analysis/GTG6/GTG6.genome.chrM.reverse.bam.partially_cleaved_short.bam
- output mitoBAM readslist for current class: /lustre/bio_running/GTEx_Long_Project/analysis/GTG6/GTG6.genome.chrM.reverse.bam.partially_cleaved_short.bam.readslist
- output mitoBAM depth file for current class: /lustre/bio_running/GTEx_Long_Project/analysis/GTG6/GTG6.genome.chrM.reverse.bam.partially_cleaved_short.bam.depth.txt
1576
   1576 16	chrM
16569 /lustre/bio_running/GTEx_Long_Project/analysis/GTG6/GTG6.genome.chrM.reverse.bam.partially_cleaved_short.bam.depth.txt

#####
Elaborating class: partially_cleaved_long

sample  new_class
GTG6    partially_cleaved_long    760
dtype: int64

(760, 16)
Number of reads for current class: 760
- output mitoBAM for current class: /lustre/bio_running/GTEx_Long_Project/analysis/GTG6/GTG6.genome.chrM.reverse.bam.partially_cleaved_long.bam
- output mitoBAM readslist for current class: /lustre/bio_running/GTEx_Long_Project/analysis/GTG6/GTG6.genome.chrM.reverse.bam.partially_cleaved_long.bam.readslist
- output mitoBAM depth file for current class: /lustre/bio_running/GTEx_Long_Project/analysis/GTG6/GTG6.genome.chrM.reverse.bam.partially_cleaved_long.bam.depth.txt
760
    760 16	chrM
16569 /lustre/bio_running/GTEx_Long_Project/analysis/GTG6/GTG6.genome.chrM.reverse.bam.partially_cleaved_long.bam.depth.txt


######################################################################################################
######################################################################################################
######################################################################################################
GTC4 Total Processed samples: 54/73
Shape of df-reads for current sample: (2683, 16)
Unique number of reads: 2683

,Chr,ChrStart,ChrEnd,read_id,MAPQ,strand,read_length,alignment_length,reference_length,polyA_length,sample,overlapping_gene_ids,overlapping_gene_names,n_overlapping_gene_ids,chrM_primary_class,new_class
13786,chrM,189,388,0a247149-6ca9-4de2-bdc8-6b8ac1048d5b,60,-,210.0,200,199,27,GTC4,7S,7S,1,complete_gene,fully_cleaved
13787,chrM,189,396,6d6d07a3-cdab-47b1-bf16-055af50834ed,60,-,219.0,206,207,34,GTC4,7S,7S,1,complete_gene,fully_cleaved

CHECKING number of reads:
Starting mito-BAM filepath: /lustre/bio_running/GTEx_Long_Project/analysis/GTC4/GTC4.genome.chrM.reverse.bam

#####
Elaborating class: fully_cleaved

sample  new_class
GTC4    fully_cleaved    112
dtype: int64

(112, 16)
Number of reads for current class: 112
- output mitoBAM for current class: /lustre/bio_running/GTEx_Long_Project/analysis/GTC4/GTC4.genome.chrM.reverse.bam.fully_cleaved.bam
- output mitoBAM readslist for current class: /lustre/bio_running/GTEx_Long_Project/analysis/GTC4/GTC4.genome.chrM.reverse.bam.fully_cleaved.bam.readslist
- output mitoBAM depth file for current class: /lustre/bio_running/GTEx_Long_Project/analysis/GTC4/GTC4.genome.chrM.reverse.bam.fully_cleaved.bam.depth.txt
112
    112 16	chrM
16569 /lustre/bio_running/GTEx_Long_Project/analysis/GTC4/GTC4.genome.chrM.reverse.bam.fully_cleaved.bam.depth.txt

#####
Elaborating class: partially_cleaved_short

sample  new_class
GTC4    partially_cleaved_short    1031
dtype: int64

(1031, 16)
Number of reads for current class: 1031
- output mitoBAM for current class: /lustre/bio_running/GTEx_Long_Project/analysis/GTC4/GTC4.genome.chrM.reverse.bam.partially_cleaved_short.bam
- output mitoBAM readslist for current class: /lustre/bio_running/GTEx_Long_Project/analysis/GTC4/GTC4.genome.chrM.reverse.bam.partially_cleaved_short.bam.readslist
- output mitoBAM depth file for current class: /lustre/bio_running/GTEx_Long_Project/analysis/GTC4/GTC4.genome.chrM.reverse.bam.partially_cleaved_short.bam.depth.txt
1031
   1031 16	chrM
16569 /lustre/bio_running/GTEx_Long_Project/analysis/GTC4/GTC4.genome.chrM.reverse.bam.partially_cleaved_short.bam.depth.txt

#####
Elaborating class: partially_cleaved_long

sample  new_class
GTC4    partially_cleaved_long    1540
dtype: int64

(1540, 16)
Number of reads for current class: 1540
- output mitoBAM for current class: /lustre/bio_running/GTEx_Long_Project/analysis/GTC4/GTC4.genome.chrM.reverse.bam.partially_cleaved_long.bam
- output mitoBAM readslist for current class: /lustre/bio_running/GTEx_Long_Project/analysis/GTC4/GTC4.genome.chrM.reverse.bam.partially_cleaved_long.bam.readslist
- output mitoBAM depth file for current class: /lustre/bio_running/GTEx_Long_Project/analysis/GTC4/GTC4.genome.chrM.reverse.bam.partially_cleaved_long.bam.depth.txt
1540
   1540 16	chrM
16569 /lustre/bio_running/GTEx_Long_Project/analysis/GTC4/GTC4.genome.chrM.reverse.bam.partially_cleaved_long.bam.depth.txt


######################################################################################################
######################################################################################################
######################################################################################################
GTA7 Total Processed samples: 55/73
Shape of df-reads for current sample: (2620, 16)
Unique number of reads: 2620

,Chr,ChrStart,ChrEnd,read_id,MAPQ,strand,read_length,alignment_length,reference_length,polyA_length,sample,overlapping_gene_ids,overlapping_gene_names,n_overlapping_gene_ids,chrM_primary_class,new_class
3794,chrM,189,394,a766913f-d5f9-4c89-b8b7-cda3c626f1f0,60,-,202.0,183,205,43,GTA7,7S,7S,1,complete_gene,fully_cleaved
3795,chrM,189,397,668385a2-2981-407c-b16c-d5923cdec983,60,-,216.0,207,208,30,GTA7,7S,7S,1,complete_gene,fully_cleaved

CHECKING number of reads:
Starting mito-BAM filepath: /lustre/bio_running/GTEx_Long_Project/analysis/GTA7/GTA7.genome.chrM.reverse.bam

#####
Elaborating class: fully_cleaved

sample  new_class
GTA7    fully_cleaved    105
dtype: int64

(105, 16)
Number of reads for current class: 105
- output mitoBAM for current class: /lustre/bio_running/GTEx_Long_Project/analysis/GTA7/GTA7.genome.chrM.reverse.bam.fully_cleaved.bam
- output mitoBAM readslist for current class: /lustre/bio_running/GTEx_Long_Project/analysis/GTA7/GTA7.genome.chrM.reverse.bam.fully_cleaved.bam.readslist
- output mitoBAM depth file for current class: /lustre/bio_running/GTEx_Long_Project/analysis/GTA7/GTA7.genome.chrM.reverse.bam.fully_cleaved.bam.depth.txt
105
    105 16	chrM
16569 /lustre/bio_running/GTEx_Long_Project/analysis/GTA7/GTA7.genome.chrM.reverse.bam.fully_cleaved.bam.depth.txt

#####
Elaborating class: partially_cleaved_short

sample  new_class
GTA7    partially_cleaved_short    1077
dtype: int64

(1077, 16)
Number of reads for current class: 1077
- output mitoBAM for current class: /lustre/bio_running/GTEx_Long_Project/analysis/GTA7/GTA7.genome.chrM.reverse.bam.partially_cleaved_short.bam
- output mitoBAM readslist for current class: /lustre/bio_running/GTEx_Long_Project/analysis/GTA7/GTA7.genome.chrM.reverse.bam.partially_cleaved_short.bam.readslist
- output mitoBAM depth file for current class: /lustre/bio_running/GTEx_Long_Project/analysis/GTA7/GTA7.genome.chrM.reverse.bam.partially_cleaved_short.bam.depth.txt
1077
   1077 16	chrM
16569 /lustre/bio_running/GTEx_Long_Project/analysis/GTA7/GTA7.genome.chrM.reverse.bam.partially_cleaved_short.bam.depth.txt

#####
Elaborating class: partially_cleaved_long

sample  new_class
GTA7    partially_cleaved_long    1438
dtype: int64

(1438, 16)
Number of reads for current class: 1438
- output mitoBAM for current class: /lustre/bio_running/GTEx_Long_Project/analysis/GTA7/GTA7.genome.chrM.reverse.bam.partially_cleaved_long.bam
- output mitoBAM readslist for current class: /lustre/bio_running/GTEx_Long_Project/analysis/GTA7/GTA7.genome.chrM.reverse.bam.partially_cleaved_long.bam.readslist
- output mitoBAM depth file for current class: /lustre/bio_running/GTEx_Long_Project/analysis/GTA7/GTA7.genome.chrM.reverse.bam.partially_cleaved_long.bam.depth.txt
1438
   1438 16	chrM
16569 /lustre/bio_running/GTEx_Long_Project/analysis/GTA7/GTA7.genome.chrM.reverse.bam.partially_cleaved_long.bam.depth.txt


######################################################################################################
######################################################################################################
######################################################################################################
GTC7 Total Processed samples: 56/73
Shape of df-reads for current sample: (2618, 16)
Unique number of reads: 2618

,Chr,ChrStart,ChrEnd,read_id,MAPQ,strand,read_length,alignment_length,reference_length,polyA_length,sample,overlapping_gene_ids,overlapping_gene_names,n_overlapping_gene_ids,chrM_primary_class,new_class
14692,chrM,189,395,e6cde0f1-9a61-4dcf-ba98-b30e6438f063,60,-,217.0,206,206,23,GTC7,7S,7S,1,complete_gene,fully_cleaved
14693,chrM,189,397,69dbe0d2-0e03-42f9-b032-099dff9cbf79,60,-,218.0,210,208,13,GTC7,7S,7S,1,complete_gene,fully_cleaved

CHECKING number of reads:
Starting mito-BAM filepath: /lustre/bio_running/GTEx_Long_Project/analysis/GTC7/GTC7.genome.chrM.reverse.bam

#####
Elaborating class: fully_cleaved

sample  new_class
GTC7    fully_cleaved    561
dtype: int64

(561, 16)
Number of reads for current class: 561
- output mitoBAM for current class: /lustre/bio_running/GTEx_Long_Project/analysis/GTC7/GTC7.genome.chrM.reverse.bam.fully_cleaved.bam
- output mitoBAM readslist for current class: /lustre/bio_running/GTEx_Long_Project/analysis/GTC7/GTC7.genome.chrM.reverse.bam.fully_cleaved.bam.readslist
- output mitoBAM depth file for current class: /lustre/bio_running/GTEx_Long_Project/analysis/GTC7/GTC7.genome.chrM.reverse.bam.fully_cleaved.bam.depth.txt
561
    561 16	chrM
16569 /lustre/bio_running/GTEx_Long_Project/analysis/GTC7/GTC7.genome.chrM.reverse.bam.fully_cleaved.bam.depth.txt

#####
Elaborating class: partially_cleaved_short

sample  new_class
GTC7    partially_cleaved_short    1429
dtype: int64

(1429, 16)
Number of reads for current class: 1429
- output mitoBAM for current class: /lustre/bio_running/GTEx_Long_Project/analysis/GTC7/GTC7.genome.chrM.reverse.bam.partially_cleaved_short.bam
- output mitoBAM readslist for current class: /lustre/bio_running/GTEx_Long_Project/analysis/GTC7/GTC7.genome.chrM.reverse.bam.partially_cleaved_short.bam.readslist
- output mitoBAM depth file for current class: /lustre/bio_running/GTEx_Long_Project/analysis/GTC7/GTC7.genome.chrM.reverse.bam.partially_cleaved_short.bam.depth.txt
1429
   1429 16	chrM
16569 /lustre/bio_running/GTEx_Long_Project/analysis/GTC7/GTC7.genome.chrM.reverse.bam.partially_cleaved_short.bam.depth.txt

#####
Elaborating class: partially_cleaved_long

sample  new_class
GTC7    partially_cleaved_long    628
dtype: int64

(628, 16)
Number of reads for current class: 628
- output mitoBAM for current class: /lustre/bio_running/GTEx_Long_Project/analysis/GTC7/GTC7.genome.chrM.reverse.bam.partially_cleaved_long.bam
- output mitoBAM readslist for current class: /lustre/bio_running/GTEx_Long_Project/analysis/GTC7/GTC7.genome.chrM.reverse.bam.partially_cleaved_long.bam.readslist
- output mitoBAM depth file for current class: /lustre/bio_running/GTEx_Long_Project/analysis/GTC7/GTC7.genome.chrM.reverse.bam.partially_cleaved_long.bam.depth.txt
628
    628 16	chrM
16569 /lustre/bio_running/GTEx_Long_Project/analysis/GTC7/GTC7.genome.chrM.reverse.bam.partially_cleaved_long.bam.depth.txt


######################################################################################################
######################################################################################################
######################################################################################################
GTC6 Total Processed samples: 57/73
Shape of df-reads for current sample: (2173, 16)
Unique number of reads: 2173

,Chr,ChrStart,ChrEnd,read_id,MAPQ,strand,read_length,alignment_length,reference_length,polyA_length,sample,overlapping_gene_ids,overlapping_gene_names,n_overlapping_gene_ids,chrM_primary_class,new_class
14556,chrM,189,395,dc46d63d-cd78-4d34-879c-806d750da717,60,-,220.0,209,206,35,GTC6,7S,7S,1,complete_gene,fully_cleaved
14557,chrM,189,397,ca338d35-8cbb-4da1-b694-8b851520ab3c,60,-,213.0,209,208,40,GTC6,7S,7S,1,complete_gene,fully_cleaved

CHECKING number of reads:
Starting mito-BAM filepath: /lustre/bio_running/GTEx_Long_Project/analysis/GTC6/GTC6.genome.chrM.reverse.bam

#####
Elaborating class: fully_cleaved

sample  new_class
GTC6    fully_cleaved    136
dtype: int64

(136, 16)
Number of reads for current class: 136
- output mitoBAM for current class: /lustre/bio_running/GTEx_Long_Project/analysis/GTC6/GTC6.genome.chrM.reverse.bam.fully_cleaved.bam
- output mitoBAM readslist for current class: /lustre/bio_running/GTEx_Long_Project/analysis/GTC6/GTC6.genome.chrM.reverse.bam.fully_cleaved.bam.readslist
- output mitoBAM depth file for current class: /lustre/bio_running/GTEx_Long_Project/analysis/GTC6/GTC6.genome.chrM.reverse.bam.fully_cleaved.bam.depth.txt
136
    136 16	chrM
16569 /lustre/bio_running/GTEx_Long_Project/analysis/GTC6/GTC6.genome.chrM.reverse.bam.fully_cleaved.bam.depth.txt

#####
Elaborating class: partially_cleaved_short

sample  new_class
GTC6    partially_cleaved_short    1191
dtype: int64

(1191, 16)
Number of reads for current class: 1191
- output mitoBAM for current class: /lustre/bio_running/GTEx_Long_Project/analysis/GTC6/GTC6.genome.chrM.reverse.bam.partially_cleaved_short.bam
- output mitoBAM readslist for current class: /lustre/bio_running/GTEx_Long_Project/analysis/GTC6/GTC6.genome.chrM.reverse.bam.partially_cleaved_short.bam.readslist
- output mitoBAM depth file for current class: /lustre/bio_running/GTEx_Long_Project/analysis/GTC6/GTC6.genome.chrM.reverse.bam.partially_cleaved_short.bam.depth.txt
1191
   1191 16	chrM
16569 /lustre/bio_running/GTEx_Long_Project/analysis/GTC6/GTC6.genome.chrM.reverse.bam.partially_cleaved_short.bam.depth.txt

#####
Elaborating class: partially_cleaved_long

sample  new_class
GTC6    partially_cleaved_long    846
dtype: int64

(846, 16)
Number of reads for current class: 846
- output mitoBAM for current class: /lustre/bio_running/GTEx_Long_Project/analysis/GTC6/GTC6.genome.chrM.reverse.bam.partially_cleaved_long.bam
- output mitoBAM readslist for current class: /lustre/bio_running/GTEx_Long_Project/analysis/GTC6/GTC6.genome.chrM.reverse.bam.partially_cleaved_long.bam.readslist
- output mitoBAM depth file for current class: /lustre/bio_running/GTEx_Long_Project/analysis/GTC6/GTC6.genome.chrM.reverse.bam.partially_cleaved_long.bam.depth.txt
846
    846 16	chrM
16569 /lustre/bio_running/GTEx_Long_Project/analysis/GTC6/GTC6.genome.chrM.reverse.bam.partially_cleaved_long.bam.depth.txt


######################################################################################################
######################################################################################################
######################################################################################################
GTE4 Total Processed samples: 58/73
Shape of df-reads for current sample: (1890, 16)
Unique number of reads: 1890

,Chr,ChrStart,ChrEnd,read_id,MAPQ,strand,read_length,alignment_length,reference_length,polyA_length,sample,overlapping_gene_ids,overlapping_gene_names,n_overlapping_gene_ids,chrM_primary_class,new_class
31487,chrM,189,397,8169942e-d89f-4abd-9bcf-756393d1911a,60,-,223.0,209,208,35,GTE4,7S,7S,1,complete_gene,fully_cleaved
31488,chrM,189,397,4eeca86d-9159-405b-98a8-f0d66eec763e,60,-,220.0,210,208,39,GTE4,7S,7S,1,complete_gene,fully_cleaved

CHECKING number of reads:
Starting mito-BAM filepath: /lustre/bio_running/GTEx_Long_Project/analysis/GTE4/GTE4.genome.chrM.reverse.bam

#####
Elaborating class: fully_cleaved

sample  new_class
GTE4    fully_cleaved    104
dtype: int64

(104, 16)
Number of reads for current class: 104
- output mitoBAM for current class: /lustre/bio_running/GTEx_Long_Project/analysis/GTE4/GTE4.genome.chrM.reverse.bam.fully_cleaved.bam
- output mitoBAM readslist for current class: /lustre/bio_running/GTEx_Long_Project/analysis/GTE4/GTE4.genome.chrM.reverse.bam.fully_cleaved.bam.readslist
- output mitoBAM depth file for current class: /lustre/bio_running/GTEx_Long_Project/analysis/GTE4/GTE4.genome.chrM.reverse.bam.fully_cleaved.bam.depth.txt
104
    104 16	chrM
16569 /lustre/bio_running/GTEx_Long_Project/analysis/GTE4/GTE4.genome.chrM.reverse.bam.fully_cleaved.bam.depth.txt

#####
Elaborating class: partially_cleaved_short

sample  new_class
GTE4    partially_cleaved_short    1033
dtype: int64

(1033, 16)
Number of reads for current class: 1033
- output mitoBAM for current class: /lustre/bio_running/GTEx_Long_Project/analysis/GTE4/GTE4.genome.chrM.reverse.bam.partially_cleaved_short.bam
- output mitoBAM readslist for current class: /lustre/bio_running/GTEx_Long_Project/analysis/GTE4/GTE4.genome.chrM.reverse.bam.partially_cleaved_short.bam.readslist
- output mitoBAM depth file for current class: /lustre/bio_running/GTEx_Long_Project/analysis/GTE4/GTE4.genome.chrM.reverse.bam.partially_cleaved_short.bam.depth.txt
1033
   1033 16	chrM
16569 /lustre/bio_running/GTEx_Long_Project/analysis/GTE4/GTE4.genome.chrM.reverse.bam.partially_cleaved_short.bam.depth.txt

#####
Elaborating class: partially_cleaved_long

sample  new_class
GTE4    partially_cleaved_long    753
dtype: int64

(753, 16)
Number of reads for current class: 753
- output mitoBAM for current class: /lustre/bio_running/GTEx_Long_Project/analysis/GTE4/GTE4.genome.chrM.reverse.bam.partially_cleaved_long.bam
- output mitoBAM readslist for current class: /lustre/bio_running/GTEx_Long_Project/analysis/GTE4/GTE4.genome.chrM.reverse.bam.partially_cleaved_long.bam.readslist
- output mitoBAM depth file for current class: /lustre/bio_running/GTEx_Long_Project/analysis/GTE4/GTE4.genome.chrM.reverse.bam.partially_cleaved_long.bam.depth.txt
753
    753 16	chrM
16569 /lustre/bio_running/GTEx_Long_Project/analysis/GTE4/GTE4.genome.chrM.reverse.bam.partially_cleaved_long.bam.depth.txt


######################################################################################################
######################################################################################################
######################################################################################################
GTA8 Total Processed samples: 59/73
Shape of df-reads for current sample: (1826, 16)
Unique number of reads: 1826

,Chr,ChrStart,ChrEnd,read_id,MAPQ,strand,read_length,alignment_length,reference_length,polyA_length,sample,overlapping_gene_ids,overlapping_gene_names,n_overlapping_gene_ids,chrM_primary_class,new_class
3899,chrM,189,397,e578d321-4b3f-44d6-9b9b-f388005c2384,60,-,212.0,209,208,43,GTA8,7S,7S,1,complete_gene,fully_cleaved
3900,chrM,189,397,72855b6c-59eb-4177-8c49-2aadd998c341,60,-,215.0,207,208,34,GTA8,7S,7S,1,complete_gene,fully_cleaved

CHECKING number of reads:
Starting mito-BAM filepath: /lustre/bio_running/GTEx_Long_Project/analysis/GTA8/GTA8.genome.chrM.reverse.bam

#####
Elaborating class: fully_cleaved

sample  new_class
GTA8    fully_cleaved    160
dtype: int64

(160, 16)
Number of reads for current class: 160
- output mitoBAM for current class: /lustre/bio_running/GTEx_Long_Project/analysis/GTA8/GTA8.genome.chrM.reverse.bam.fully_cleaved.bam
- output mitoBAM readslist for current class: /lustre/bio_running/GTEx_Long_Project/analysis/GTA8/GTA8.genome.chrM.reverse.bam.fully_cleaved.bam.readslist
- output mitoBAM depth file for current class: /lustre/bio_running/GTEx_Long_Project/analysis/GTA8/GTA8.genome.chrM.reverse.bam.fully_cleaved.bam.depth.txt
160
    160 16	chrM
16569 /lustre/bio_running/GTEx_Long_Project/analysis/GTA8/GTA8.genome.chrM.reverse.bam.fully_cleaved.bam.depth.txt

#####
Elaborating class: partially_cleaved_short

sample  new_class
GTA8    partially_cleaved_short    1000
dtype: int64

(1000, 16)
Number of reads for current class: 1000
- output mitoBAM for current class: /lustre/bio_running/GTEx_Long_Project/analysis/GTA8/GTA8.genome.chrM.reverse.bam.partially_cleaved_short.bam
- output mitoBAM readslist for current class: /lustre/bio_running/GTEx_Long_Project/analysis/GTA8/GTA8.genome.chrM.reverse.bam.partially_cleaved_short.bam.readslist
- output mitoBAM depth file for current class: /lustre/bio_running/GTEx_Long_Project/analysis/GTA8/GTA8.genome.chrM.reverse.bam.partially_cleaved_short.bam.depth.txt
1000
   1000 16	chrM
16569 /lustre/bio_running/GTEx_Long_Project/analysis/GTA8/GTA8.genome.chrM.reverse.bam.partially_cleaved_short.bam.depth.txt

#####
Elaborating class: partially_cleaved_long

sample  new_class
GTA8    partially_cleaved_long    666
dtype: int64

(666, 16)
Number of reads for current class: 666
- output mitoBAM for current class: /lustre/bio_running/GTEx_Long_Project/analysis/GTA8/GTA8.genome.chrM.reverse.bam.partially_cleaved_long.bam
- output mitoBAM readslist for current class: /lustre/bio_running/GTEx_Long_Project/analysis/GTA8/GTA8.genome.chrM.reverse.bam.partially_cleaved_long.bam.readslist
- output mitoBAM depth file for current class: /lustre/bio_running/GTEx_Long_Project/analysis/GTA8/GTA8.genome.chrM.reverse.bam.partially_cleaved_long.bam.depth.txt
666
    666 16	chrM
16569 /lustre/bio_running/GTEx_Long_Project/analysis/GTA8/GTA8.genome.chrM.reverse.bam.partially_cleaved_long.bam.depth.txt


######################################################################################################
######################################################################################################
######################################################################################################
GTA6 Total Processed samples: 60/73
Shape of df-reads for current sample: (1790, 16)
Unique number of reads: 1790

,Chr,ChrStart,ChrEnd,read_id,MAPQ,strand,read_length,alignment_length,reference_length,polyA_length,sample,overlapping_gene_ids,overlapping_gene_names,n_overlapping_gene_ids,chrM_primary_class,new_class
3714,chrM,189,389,4d74cdcb-bf31-41e9-9cc0-d12b0d2b1540,60,-,210.0,204,200,29,GTA6,7S,7S,1,complete_gene,fully_cleaved
3715,chrM,189,397,3375cc69-3745-4f42-91fc-fd90dae996ea,60,-,231.0,210,208,29,GTA6,7S,7S,1,complete_gene,fully_cleaved

CHECKING number of reads:
Starting mito-BAM filepath: /lustre/bio_running/GTEx_Long_Project/analysis/GTA6/GTA6.genome.chrM.reverse.bam

#####
Elaborating class: fully_cleaved

sample  new_class
GTA6    fully_cleaved    80
dtype: int64

(80, 16)
Number of reads for current class: 80
- output mitoBAM for current class: /lustre/bio_running/GTEx_Long_Project/analysis/GTA6/GTA6.genome.chrM.reverse.bam.fully_cleaved.bam
- output mitoBAM readslist for current class: /lustre/bio_running/GTEx_Long_Project/analysis/GTA6/GTA6.genome.chrM.reverse.bam.fully_cleaved.bam.readslist
- output mitoBAM depth file for current class: /lustre/bio_running/GTEx_Long_Project/analysis/GTA6/GTA6.genome.chrM.reverse.bam.fully_cleaved.bam.depth.txt
80
     80 16	chrM
16569 /lustre/bio_running/GTEx_Long_Project/analysis/GTA6/GTA6.genome.chrM.reverse.bam.fully_cleaved.bam.depth.txt

#####
Elaborating class: partially_cleaved_short

sample  new_class
GTA6    partially_cleaved_short    947
dtype: int64

(947, 16)
Number of reads for current class: 947
- output mitoBAM for current class: /lustre/bio_running/GTEx_Long_Project/analysis/GTA6/GTA6.genome.chrM.reverse.bam.partially_cleaved_short.bam
- output mitoBAM readslist for current class: /lustre/bio_running/GTEx_Long_Project/analysis/GTA6/GTA6.genome.chrM.reverse.bam.partially_cleaved_short.bam.readslist
- output mitoBAM depth file for current class: /lustre/bio_running/GTEx_Long_Project/analysis/GTA6/GTA6.genome.chrM.reverse.bam.partially_cleaved_short.bam.depth.txt
947
    947 16	chrM
16569 /lustre/bio_running/GTEx_Long_Project/analysis/GTA6/GTA6.genome.chrM.reverse.bam.partially_cleaved_short.bam.depth.txt

#####
Elaborating class: partially_cleaved_long

sample  new_class
GTA6    partially_cleaved_long    763
dtype: int64

(763, 16)
Number of reads for current class: 763
- output mitoBAM for current class: /lustre/bio_running/GTEx_Long_Project/analysis/GTA6/GTA6.genome.chrM.reverse.bam.partially_cleaved_long.bam
- output mitoBAM readslist for current class: /lustre/bio_running/GTEx_Long_Project/analysis/GTA6/GTA6.genome.chrM.reverse.bam.partially_cleaved_long.bam.readslist
- output mitoBAM depth file for current class: /lustre/bio_running/GTEx_Long_Project/analysis/GTA6/GTA6.genome.chrM.reverse.bam.partially_cleaved_long.bam.depth.txt
763
    763 16	chrM
16569 /lustre/bio_running/GTEx_Long_Project/analysis/GTA6/GTA6.genome.chrM.reverse.bam.partially_cleaved_long.bam.depth.txt


######################################################################################################
######################################################################################################
######################################################################################################
GTE8 Total Processed samples: 61/73
Shape of df-reads for current sample: (1294, 16)
Unique number of reads: 1294

,Chr,ChrStart,ChrEnd,read_id,MAPQ,strand,read_length,alignment_length,reference_length,polyA_length,sample,overlapping_gene_ids,overlapping_gene_names,n_overlapping_gene_ids,chrM_primary_class,new_class
32166,chrM,189,397,ce4848e9-c35c-4ad6-8fef-2c538f0ce9f5,60,-,215.0,206,208,29,GTE8,7S,7S,1,complete_gene,fully_cleaved
32167,chrM,189,393,063f4f51-2317-4fc1-98d7-49047654d70b,60,-,267.0,216,204,35,GTE8,7S,7S,1,complete_gene,fully_cleaved

CHECKING number of reads:
Starting mito-BAM filepath: /lustre/bio_running/GTEx_Long_Project/analysis/GTE8/GTE8.genome.chrM.reverse.bam

#####
Elaborating class: fully_cleaved

sample  new_class
GTE8    fully_cleaved    100
dtype: int64

(100, 16)
Number of reads for current class: 100
- output mitoBAM for current class: /lustre/bio_running/GTEx_Long_Project/analysis/GTE8/GTE8.genome.chrM.reverse.bam.fully_cleaved.bam
- output mitoBAM readslist for current class: /lustre/bio_running/GTEx_Long_Project/analysis/GTE8/GTE8.genome.chrM.reverse.bam.fully_cleaved.bam.readslist
- output mitoBAM depth file for current class: /lustre/bio_running/GTEx_Long_Project/analysis/GTE8/GTE8.genome.chrM.reverse.bam.fully_cleaved.bam.depth.txt
100
    100 16	chrM
16569 /lustre/bio_running/GTEx_Long_Project/analysis/GTE8/GTE8.genome.chrM.reverse.bam.fully_cleaved.bam.depth.txt

#####
Elaborating class: partially_cleaved_short

sample  new_class
GTE8    partially_cleaved_short    893
dtype: int64

(893, 16)
Number of reads for current class: 893
- output mitoBAM for current class: /lustre/bio_running/GTEx_Long_Project/analysis/GTE8/GTE8.genome.chrM.reverse.bam.partially_cleaved_short.bam
- output mitoBAM readslist for current class: /lustre/bio_running/GTEx_Long_Project/analysis/GTE8/GTE8.genome.chrM.reverse.bam.partially_cleaved_short.bam.readslist
- output mitoBAM depth file for current class: /lustre/bio_running/GTEx_Long_Project/analysis/GTE8/GTE8.genome.chrM.reverse.bam.partially_cleaved_short.bam.depth.txt
893
    893 16	chrM
16569 /lustre/bio_running/GTEx_Long_Project/analysis/GTE8/GTE8.genome.chrM.reverse.bam.partially_cleaved_short.bam.depth.txt

#####
Elaborating class: partially_cleaved_long

sample  new_class
GTE8    partially_cleaved_long    301
dtype: int64

(301, 16)
Number of reads for current class: 301
- output mitoBAM for current class: /lustre/bio_running/GTEx_Long_Project/analysis/GTE8/GTE8.genome.chrM.reverse.bam.partially_cleaved_long.bam
- output mitoBAM readslist for current class: /lustre/bio_running/GTEx_Long_Project/analysis/GTE8/GTE8.genome.chrM.reverse.bam.partially_cleaved_long.bam.readslist
- output mitoBAM depth file for current class: /lustre/bio_running/GTEx_Long_Project/analysis/GTE8/GTE8.genome.chrM.reverse.bam.partially_cleaved_long.bam.depth.txt
301
    301 16	chrM
16569 /lustre/bio_running/GTEx_Long_Project/analysis/GTE8/GTE8.genome.chrM.reverse.bam.partially_cleaved_long.bam.depth.txt


######################################################################################################
######################################################################################################
######################################################################################################
GTE1 Total Processed samples: 62/73
Shape of df-reads for current sample: (1184, 16)
Unique number of reads: 1184

,Chr,ChrStart,ChrEnd,read_id,MAPQ,strand,read_length,alignment_length,reference_length,polyA_length,sample,overlapping_gene_ids,overlapping_gene_names,n_overlapping_gene_ids,chrM_primary_class,new_class
28624,chrM,189,397,72b9d4f3-27b8-4c08-b030-53a267750cda,60,-,222.0,209,208,32,GTE1,7S,7S,1,complete_gene,fully_cleaved
28625,chrM,189,396,52c0f465-cda1-41c1-817a-9a71ad964f5e,60,-,214.0,210,207,38,GTE1,7S,7S,1,complete_gene,fully_cleaved

CHECKING number of reads:
Starting mito-BAM filepath: /lustre/bio_running/GTEx_Long_Project/analysis/GTE1/GTE1.genome.chrM.reverse.bam

#####
Elaborating class: fully_cleaved

sample  new_class
GTE1    fully_cleaved    40
dtype: int64

(40, 16)
Number of reads for current class: 40
- output mitoBAM for current class: /lustre/bio_running/GTEx_Long_Project/analysis/GTE1/GTE1.genome.chrM.reverse.bam.fully_cleaved.bam
- output mitoBAM readslist for current class: /lustre/bio_running/GTEx_Long_Project/analysis/GTE1/GTE1.genome.chrM.reverse.bam.fully_cleaved.bam.readslist
- output mitoBAM depth file for current class: /lustre/bio_running/GTEx_Long_Project/analysis/GTE1/GTE1.genome.chrM.reverse.bam.fully_cleaved.bam.depth.txt
40
     40 16	chrM
16569 /lustre/bio_running/GTEx_Long_Project/analysis/GTE1/GTE1.genome.chrM.reverse.bam.fully_cleaved.bam.depth.txt

#####
Elaborating class: partially_cleaved_short

sample  new_class
GTE1    partially_cleaved_short    458
dtype: int64

(458, 16)
Number of reads for current class: 458
- output mitoBAM for current class: /lustre/bio_running/GTEx_Long_Project/analysis/GTE1/GTE1.genome.chrM.reverse.bam.partially_cleaved_short.bam
- output mitoBAM readslist for current class: /lustre/bio_running/GTEx_Long_Project/analysis/GTE1/GTE1.genome.chrM.reverse.bam.partially_cleaved_short.bam.readslist
- output mitoBAM depth file for current class: /lustre/bio_running/GTEx_Long_Project/analysis/GTE1/GTE1.genome.chrM.reverse.bam.partially_cleaved_short.bam.depth.txt
458
    458 16	chrM
16569 /lustre/bio_running/GTEx_Long_Project/analysis/GTE1/GTE1.genome.chrM.reverse.bam.partially_cleaved_short.bam.depth.txt

#####
Elaborating class: partially_cleaved_long

sample  new_class
GTE1    partially_cleaved_long    686
dtype: int64

(686, 16)
Number of reads for current class: 686
- output mitoBAM for current class: /lustre/bio_running/GTEx_Long_Project/analysis/GTE1/GTE1.genome.chrM.reverse.bam.partially_cleaved_long.bam
- output mitoBAM readslist for current class: /lustre/bio_running/GTEx_Long_Project/analysis/GTE1/GTE1.genome.chrM.reverse.bam.partially_cleaved_long.bam.readslist
- output mitoBAM depth file for current class: /lustre/bio_running/GTEx_Long_Project/analysis/GTE1/GTE1.genome.chrM.reverse.bam.partially_cleaved_long.bam.depth.txt
686
    686 16	chrM
16569 /lustre/bio_running/GTEx_Long_Project/analysis/GTE1/GTE1.genome.chrM.reverse.bam.partially_cleaved_long.bam.depth.txt


######################################################################################################
######################################################################################################
######################################################################################################
GTH4 Total Processed samples: 63/73
Shape of df-reads for current sample: (1176, 16)
Unique number of reads: 1176

,Chr,ChrStart,ChrEnd,read_id,MAPQ,strand,read_length,alignment_length,reference_length,polyA_length,sample,overlapping_gene_ids,overlapping_gene_names,n_overlapping_gene_ids,chrM_primary_class,new_class
48970,chrM,189,396,ec2012b8-27cc-46fc-9346-6159409e9f3b,60,-,221.0,209,207,45,GTH4,7S,7S,1,complete_gene,fully_cleaved
48971,chrM,189,397,1d453fe6-69cb-4b8b-b937-c48348cf56fc,60,-,209.0,206,208,29,GTH4,7S,7S,1,complete_gene,fully_cleaved

CHECKING number of reads:
Starting mito-BAM filepath: /lustre/bio_running/GTEx_Long_Project/analysis/GTH4/GTH4.genome.chrM.reverse.bam

#####
Elaborating class: fully_cleaved

sample  new_class
GTH4    fully_cleaved    71
dtype: int64

(71, 16)
Number of reads for current class: 71
- output mitoBAM for current class: /lustre/bio_running/GTEx_Long_Project/analysis/GTH4/GTH4.genome.chrM.reverse.bam.fully_cleaved.bam
- output mitoBAM readslist for current class: /lustre/bio_running/GTEx_Long_Project/analysis/GTH4/GTH4.genome.chrM.reverse.bam.fully_cleaved.bam.readslist
- output mitoBAM depth file for current class: /lustre/bio_running/GTEx_Long_Project/analysis/GTH4/GTH4.genome.chrM.reverse.bam.fully_cleaved.bam.depth.txt
71
     71 16	chrM
16569 /lustre/bio_running/GTEx_Long_Project/analysis/GTH4/GTH4.genome.chrM.reverse.bam.fully_cleaved.bam.depth.txt

#####
Elaborating class: partially_cleaved_short

sample  new_class
GTH4    partially_cleaved_short    618
dtype: int64

(618, 16)
Number of reads for current class: 618
- output mitoBAM for current class: /lustre/bio_running/GTEx_Long_Project/analysis/GTH4/GTH4.genome.chrM.reverse.bam.partially_cleaved_short.bam
- output mitoBAM readslist for current class: /lustre/bio_running/GTEx_Long_Project/analysis/GTH4/GTH4.genome.chrM.reverse.bam.partially_cleaved_short.bam.readslist
- output mitoBAM depth file for current class: /lustre/bio_running/GTEx_Long_Project/analysis/GTH4/GTH4.genome.chrM.reverse.bam.partially_cleaved_short.bam.depth.txt
618
    618 16	chrM
16569 /lustre/bio_running/GTEx_Long_Project/analysis/GTH4/GTH4.genome.chrM.reverse.bam.partially_cleaved_short.bam.depth.txt

#####
Elaborating class: partially_cleaved_long

sample  new_class
GTH4    partially_cleaved_long    487
dtype: int64

(487, 16)
Number of reads for current class: 487
- output mitoBAM for current class: /lustre/bio_running/GTEx_Long_Project/analysis/GTH4/GTH4.genome.chrM.reverse.bam.partially_cleaved_long.bam
- output mitoBAM readslist for current class: /lustre/bio_running/GTEx_Long_Project/analysis/GTH4/GTH4.genome.chrM.reverse.bam.partially_cleaved_long.bam.readslist
- output mitoBAM depth file for current class: /lustre/bio_running/GTEx_Long_Project/analysis/GTH4/GTH4.genome.chrM.reverse.bam.partially_cleaved_long.bam.depth.txt
487
    487 16	chrM
16569 /lustre/bio_running/GTEx_Long_Project/analysis/GTH4/GTH4.genome.chrM.reverse.bam.partially_cleaved_long.bam.depth.txt


######################################################################################################
######################################################################################################
######################################################################################################
GTE5 Total Processed samples: 64/73
Shape of df-reads for current sample: (1150, 16)
Unique number of reads: 1150

,Chr,ChrStart,ChrEnd,read_id,MAPQ,strand,read_length,alignment_length,reference_length,polyA_length,sample,overlapping_gene_ids,overlapping_gene_names,n_overlapping_gene_ids,chrM_primary_class,new_class
31591,chrM,189,397,7bdfe5df-4dce-4bd1-aacc-b0cf8d5441f3,60,-,216.0,206,208,35,GTE5,7S,7S,1,complete_gene,fully_cleaved
31592,chrM,189,398,3fbad211-e127-4ebd-bcc7-479a76a10aa8,60,-,230.0,210,209,70,GTE5,7S,7S,1,complete_gene,fully_cleaved

CHECKING number of reads:
Starting mito-BAM filepath: /lustre/bio_running/GTEx_Long_Project/analysis/GTE5/GTE5.genome.chrM.reverse.bam

#####
Elaborating class: fully_cleaved

sample  new_class
GTE5    fully_cleaved    44
dtype: int64

(44, 16)
Number of reads for current class: 44
- output mitoBAM for current class: /lustre/bio_running/GTEx_Long_Project/analysis/GTE5/GTE5.genome.chrM.reverse.bam.fully_cleaved.bam
- output mitoBAM readslist for current class: /lustre/bio_running/GTEx_Long_Project/analysis/GTE5/GTE5.genome.chrM.reverse.bam.fully_cleaved.bam.readslist
- output mitoBAM depth file for current class: /lustre/bio_running/GTEx_Long_Project/analysis/GTE5/GTE5.genome.chrM.reverse.bam.fully_cleaved.bam.depth.txt
44
     44 16	chrM
16569 /lustre/bio_running/GTEx_Long_Project/analysis/GTE5/GTE5.genome.chrM.reverse.bam.fully_cleaved.bam.depth.txt

#####
Elaborating class: partially_cleaved_short

sample  new_class
GTE5    partially_cleaved_short    452
dtype: int64

(452, 16)
Number of reads for current class: 452
- output mitoBAM for current class: /lustre/bio_running/GTEx_Long_Project/analysis/GTE5/GTE5.genome.chrM.reverse.bam.partially_cleaved_short.bam
- output mitoBAM readslist for current class: /lustre/bio_running/GTEx_Long_Project/analysis/GTE5/GTE5.genome.chrM.reverse.bam.partially_cleaved_short.bam.readslist
- output mitoBAM depth file for current class: /lustre/bio_running/GTEx_Long_Project/analysis/GTE5/GTE5.genome.chrM.reverse.bam.partially_cleaved_short.bam.depth.txt
452
    452 16	chrM
16569 /lustre/bio_running/GTEx_Long_Project/analysis/GTE5/GTE5.genome.chrM.reverse.bam.partially_cleaved_short.bam.depth.txt

#####
Elaborating class: partially_cleaved_long

sample  new_class
GTE5    partially_cleaved_long    654
dtype: int64

(654, 16)
Number of reads for current class: 654
- output mitoBAM for current class: /lustre/bio_running/GTEx_Long_Project/analysis/GTE5/GTE5.genome.chrM.reverse.bam.partially_cleaved_long.bam
- output mitoBAM readslist for current class: /lustre/bio_running/GTEx_Long_Project/analysis/GTE5/GTE5.genome.chrM.reverse.bam.partially_cleaved_long.bam.readslist
- output mitoBAM depth file for current class: /lustre/bio_running/GTEx_Long_Project/analysis/GTE5/GTE5.genome.chrM.reverse.bam.partially_cleaved_long.bam.depth.txt
654
    654 16	chrM
16569 /lustre/bio_running/GTEx_Long_Project/analysis/GTE5/GTE5.genome.chrM.reverse.bam.partially_cleaved_long.bam.depth.txt


######################################################################################################
######################################################################################################
######################################################################################################
GTD3 Total Processed samples: 65/73
Shape of df-reads for current sample: (1140, 16)
Unique number of reads: 1140

,Chr,ChrStart,ChrEnd,read_id,MAPQ,strand,read_length,alignment_length,reference_length,polyA_length,sample,overlapping_gene_ids,overlapping_gene_names,n_overlapping_gene_ids,chrM_primary_class,new_class
20784,chrM,189,397,f3dc57f7-e803-4941-b9ab-0e162157a6ca,60,-,220.0,207,208,31,GTD3,7S,7S,1,complete_gene,fully_cleaved
20785,chrM,189,397,b66744f1-1bf6-401e-bf7d-aae45d5fc635,60,-,217.0,209,208,31,GTD3,7S,7S,1,complete_gene,fully_cleaved

CHECKING number of reads:
Starting mito-BAM filepath: /lustre/bio_running/GTEx_Long_Project/analysis/GTD3/GTD3.genome.chrM.reverse.bam

#####
Elaborating class: fully_cleaved

sample  new_class
GTD3    fully_cleaved    69
dtype: int64

(69, 16)
Number of reads for current class: 69
- output mitoBAM for current class: /lustre/bio_running/GTEx_Long_Project/analysis/GTD3/GTD3.genome.chrM.reverse.bam.fully_cleaved.bam
- output mitoBAM readslist for current class: /lustre/bio_running/GTEx_Long_Project/analysis/GTD3/GTD3.genome.chrM.reverse.bam.fully_cleaved.bam.readslist
- output mitoBAM depth file for current class: /lustre/bio_running/GTEx_Long_Project/analysis/GTD3/GTD3.genome.chrM.reverse.bam.fully_cleaved.bam.depth.txt
69
     69 16	chrM
16569 /lustre/bio_running/GTEx_Long_Project/analysis/GTD3/GTD3.genome.chrM.reverse.bam.fully_cleaved.bam.depth.txt

#####
Elaborating class: partially_cleaved_short

sample  new_class
GTD3    partially_cleaved_short    549
dtype: int64

(549, 16)
Number of reads for current class: 549
- output mitoBAM for current class: /lustre/bio_running/GTEx_Long_Project/analysis/GTD3/GTD3.genome.chrM.reverse.bam.partially_cleaved_short.bam
- output mitoBAM readslist for current class: /lustre/bio_running/GTEx_Long_Project/analysis/GTD3/GTD3.genome.chrM.reverse.bam.partially_cleaved_short.bam.readslist
- output mitoBAM depth file for current class: /lustre/bio_running/GTEx_Long_Project/analysis/GTD3/GTD3.genome.chrM.reverse.bam.partially_cleaved_short.bam.depth.txt
549
    549 16	chrM
16569 /lustre/bio_running/GTEx_Long_Project/analysis/GTD3/GTD3.genome.chrM.reverse.bam.partially_cleaved_short.bam.depth.txt

#####
Elaborating class: partially_cleaved_long

sample  new_class
GTD3    partially_cleaved_long    522
dtype: int64

(522, 16)
Number of reads for current class: 522
- output mitoBAM for current class: /lustre/bio_running/GTEx_Long_Project/analysis/GTD3/GTD3.genome.chrM.reverse.bam.partially_cleaved_long.bam
- output mitoBAM readslist for current class: /lustre/bio_running/GTEx_Long_Project/analysis/GTD3/GTD3.genome.chrM.reverse.bam.partially_cleaved_long.bam.readslist
- output mitoBAM depth file for current class: /lustre/bio_running/GTEx_Long_Project/analysis/GTD3/GTD3.genome.chrM.reverse.bam.partially_cleaved_long.bam.depth.txt
522
    522 16	chrM
16569 /lustre/bio_running/GTEx_Long_Project/analysis/GTD3/GTD3.genome.chrM.reverse.bam.partially_cleaved_long.bam.depth.txt


######################################################################################################
######################################################################################################
######################################################################################################
GTF6 Total Processed samples: 66/73
Shape of df-reads for current sample: (1116, 16)
Unique number of reads: 1116

,Chr,ChrStart,ChrEnd,read_id,MAPQ,strand,read_length,alignment_length,reference_length,polyA_length,sample,overlapping_gene_ids,overlapping_gene_names,n_overlapping_gene_ids,chrM_primary_class,new_class
37744,chrM,189,392,ad4c2337-9253-4bbc-b475-6700133276b8,60,-,218.0,205,203,43,GTF6,7S,7S,1,complete_gene,fully_cleaved
37745,chrM,189,394,8183d774-8e77-4792-9544-f3d64076f355,60,-,217.0,205,205,44,GTF6,7S,7S,1,complete_gene,fully_cleaved

CHECKING number of reads:
Starting mito-BAM filepath: /lustre/bio_running/GTEx_Long_Project/analysis/GTF6/GTF6.genome.chrM.reverse.bam

#####
Elaborating class: fully_cleaved

sample  new_class
GTF6    fully_cleaved    59
dtype: int64

(59, 16)
Number of reads for current class: 59
- output mitoBAM for current class: /lustre/bio_running/GTEx_Long_Project/analysis/GTF6/GTF6.genome.chrM.reverse.bam.fully_cleaved.bam
- output mitoBAM readslist for current class: /lustre/bio_running/GTEx_Long_Project/analysis/GTF6/GTF6.genome.chrM.reverse.bam.fully_cleaved.bam.readslist
- output mitoBAM depth file for current class: /lustre/bio_running/GTEx_Long_Project/analysis/GTF6/GTF6.genome.chrM.reverse.bam.fully_cleaved.bam.depth.txt
59
     59 16	chrM
16569 /lustre/bio_running/GTEx_Long_Project/analysis/GTF6/GTF6.genome.chrM.reverse.bam.fully_cleaved.bam.depth.txt

#####
Elaborating class: partially_cleaved_short

sample  new_class
GTF6    partially_cleaved_short    537
dtype: int64

(537, 16)
Number of reads for current class: 537
- output mitoBAM for current class: /lustre/bio_running/GTEx_Long_Project/analysis/GTF6/GTF6.genome.chrM.reverse.bam.partially_cleaved_short.bam
- output mitoBAM readslist for current class: /lustre/bio_running/GTEx_Long_Project/analysis/GTF6/GTF6.genome.chrM.reverse.bam.partially_cleaved_short.bam.readslist
- output mitoBAM depth file for current class: /lustre/bio_running/GTEx_Long_Project/analysis/GTF6/GTF6.genome.chrM.reverse.bam.partially_cleaved_short.bam.depth.txt
537
    537 16	chrM
16569 /lustre/bio_running/GTEx_Long_Project/analysis/GTF6/GTF6.genome.chrM.reverse.bam.partially_cleaved_short.bam.depth.txt

#####
Elaborating class: partially_cleaved_long

sample  new_class
GTF6    partially_cleaved_long    520
dtype: int64

(520, 16)
Number of reads for current class: 520
- output mitoBAM for current class: /lustre/bio_running/GTEx_Long_Project/analysis/GTF6/GTF6.genome.chrM.reverse.bam.partially_cleaved_long.bam
- output mitoBAM readslist for current class: /lustre/bio_running/GTEx_Long_Project/analysis/GTF6/GTF6.genome.chrM.reverse.bam.partially_cleaved_long.bam.readslist
- output mitoBAM depth file for current class: /lustre/bio_running/GTEx_Long_Project/analysis/GTF6/GTF6.genome.chrM.reverse.bam.partially_cleaved_long.bam.depth.txt
520
    520 16	chrM
16569 /lustre/bio_running/GTEx_Long_Project/analysis/GTF6/GTF6.genome.chrM.reverse.bam.partially_cleaved_long.bam.depth.txt


######################################################################################################
######################################################################################################
######################################################################################################
GTD1 Total Processed samples: 67/73
Shape of df-reads for current sample: (1009, 16)
Unique number of reads: 1009

,Chr,ChrStart,ChrEnd,read_id,MAPQ,strand,read_length,alignment_length,reference_length,polyA_length,sample,overlapping_gene_ids,overlapping_gene_names,n_overlapping_gene_ids,chrM_primary_class,new_class
19312,chrM,189,397,81eef0e3-8dd2-4657-a8f5-b8b3a53758e6,60,-,210.0,205,208,36,GTD1,7S,7S,1,complete_gene,fully_cleaved
19313,chrM,189,396,37340f50-6574-4595-98f0-24c4d0c11634,60,-,217.0,208,207,30,GTD1,7S,7S,1,complete_gene,fully_cleaved

CHECKING number of reads:
Starting mito-BAM filepath: /lustre/bio_running/GTEx_Long_Project/analysis/GTD1/GTD1.genome.chrM.reverse.bam

#####
Elaborating class: fully_cleaved

sample  new_class
GTD1    fully_cleaved    27
dtype: int64

(27, 16)
Number of reads for current class: 27
- output mitoBAM for current class: /lustre/bio_running/GTEx_Long_Project/analysis/GTD1/GTD1.genome.chrM.reverse.bam.fully_cleaved.bam
- output mitoBAM readslist for current class: /lustre/bio_running/GTEx_Long_Project/analysis/GTD1/GTD1.genome.chrM.reverse.bam.fully_cleaved.bam.readslist
- output mitoBAM depth file for current class: /lustre/bio_running/GTEx_Long_Project/analysis/GTD1/GTD1.genome.chrM.reverse.bam.fully_cleaved.bam.depth.txt
27
     27 16	chrM
16569 /lustre/bio_running/GTEx_Long_Project/analysis/GTD1/GTD1.genome.chrM.reverse.bam.fully_cleaved.bam.depth.txt

#####
Elaborating class: partially_cleaved_short

sample  new_class
GTD1    partially_cleaved_short    465
dtype: int64

(465, 16)
Number of reads for current class: 465
- output mitoBAM for current class: /lustre/bio_running/GTEx_Long_Project/analysis/GTD1/GTD1.genome.chrM.reverse.bam.partially_cleaved_short.bam
- output mitoBAM readslist for current class: /lustre/bio_running/GTEx_Long_Project/analysis/GTD1/GTD1.genome.chrM.reverse.bam.partially_cleaved_short.bam.readslist
- output mitoBAM depth file for current class: /lustre/bio_running/GTEx_Long_Project/analysis/GTD1/GTD1.genome.chrM.reverse.bam.partially_cleaved_short.bam.depth.txt
465
    465 16	chrM
16569 /lustre/bio_running/GTEx_Long_Project/analysis/GTD1/GTD1.genome.chrM.reverse.bam.partially_cleaved_short.bam.depth.txt

#####
Elaborating class: partially_cleaved_long

sample  new_class
GTD1    partially_cleaved_long    517
dtype: int64

(517, 16)
Number of reads for current class: 517
- output mitoBAM for current class: /lustre/bio_running/GTEx_Long_Project/analysis/GTD1/GTD1.genome.chrM.reverse.bam.partially_cleaved_long.bam
- output mitoBAM readslist for current class: /lustre/bio_running/GTEx_Long_Project/analysis/GTD1/GTD1.genome.chrM.reverse.bam.partially_cleaved_long.bam.readslist
- output mitoBAM depth file for current class: /lustre/bio_running/GTEx_Long_Project/analysis/GTD1/GTD1.genome.chrM.reverse.bam.partially_cleaved_long.bam.depth.txt
517
    517 16	chrM
16569 /lustre/bio_running/GTEx_Long_Project/analysis/GTD1/GTD1.genome.chrM.reverse.bam.partially_cleaved_long.bam.depth.txt


######################################################################################################
######################################################################################################
######################################################################################################
GTF9 Total Processed samples: 68/73
Shape of df-reads for current sample: (741, 16)
Unique number of reads: 741

,Chr,ChrStart,ChrEnd,read_id,MAPQ,strand,read_length,alignment_length,reference_length,polyA_length,sample,overlapping_gene_ids,overlapping_gene_names,n_overlapping_gene_ids,chrM_primary_class,new_class
38421,chrM,189,397,5736e2f7-8365-4cf3-bd96-e1100f23a6b3,60,-,213.0,209,208,40,GTF9,7S,7S,1,complete_gene,fully_cleaved
38422,chrM,189,397,8044647a-cc90-48ac-9504-ced0db33ed69,60,-,218.0,209,208,36,GTF9,7S,7S,1,complete_gene,fully_cleaved

CHECKING number of reads:
Starting mito-BAM filepath: /lustre/bio_running/GTEx_Long_Project/analysis/GTF9/GTF9.genome.chrM.reverse.bam

#####
Elaborating class: fully_cleaved

sample  new_class
GTF9    fully_cleaved    37
dtype: int64

(37, 16)
Number of reads for current class: 37
- output mitoBAM for current class: /lustre/bio_running/GTEx_Long_Project/analysis/GTF9/GTF9.genome.chrM.reverse.bam.fully_cleaved.bam
- output mitoBAM readslist for current class: /lustre/bio_running/GTEx_Long_Project/analysis/GTF9/GTF9.genome.chrM.reverse.bam.fully_cleaved.bam.readslist
- output mitoBAM depth file for current class: /lustre/bio_running/GTEx_Long_Project/analysis/GTF9/GTF9.genome.chrM.reverse.bam.fully_cleaved.bam.depth.txt
37
     37 16	chrM
16569 /lustre/bio_running/GTEx_Long_Project/analysis/GTF9/GTF9.genome.chrM.reverse.bam.fully_cleaved.bam.depth.txt

#####
Elaborating class: partially_cleaved_short

sample  new_class
GTF9    partially_cleaved_short    331
dtype: int64

(331, 16)
Number of reads for current class: 331
- output mitoBAM for current class: /lustre/bio_running/GTEx_Long_Project/analysis/GTF9/GTF9.genome.chrM.reverse.bam.partially_cleaved_short.bam
- output mitoBAM readslist for current class: /lustre/bio_running/GTEx_Long_Project/analysis/GTF9/GTF9.genome.chrM.reverse.bam.partially_cleaved_short.bam.readslist
- output mitoBAM depth file for current class: /lustre/bio_running/GTEx_Long_Project/analysis/GTF9/GTF9.genome.chrM.reverse.bam.partially_cleaved_short.bam.depth.txt
331
    331 16	chrM
16569 /lustre/bio_running/GTEx_Long_Project/analysis/GTF9/GTF9.genome.chrM.reverse.bam.partially_cleaved_short.bam.depth.txt

#####
Elaborating class: partially_cleaved_long

sample  new_class
GTF9    partially_cleaved_long    373
dtype: int64

(373, 16)
Number of reads for current class: 373
- output mitoBAM for current class: /lustre/bio_running/GTEx_Long_Project/analysis/GTF9/GTF9.genome.chrM.reverse.bam.partially_cleaved_long.bam
- output mitoBAM readslist for current class: /lustre/bio_running/GTEx_Long_Project/analysis/GTF9/GTF9.genome.chrM.reverse.bam.partially_cleaved_long.bam.readslist
- output mitoBAM depth file for current class: /lustre/bio_running/GTEx_Long_Project/analysis/GTF9/GTF9.genome.chrM.reverse.bam.partially_cleaved_long.bam.depth.txt
373
    373 16	chrM
16569 /lustre/bio_running/GTEx_Long_Project/analysis/GTF9/GTF9.genome.chrM.reverse.bam.partially_cleaved_long.bam.depth.txt


######################################################################################################
######################################################################################################
######################################################################################################
GTF7 Total Processed samples: 69/73
Shape of df-reads for current sample: (707, 16)
Unique number of reads: 707

,Chr,ChrStart,ChrEnd,read_id,MAPQ,strand,read_length,alignment_length,reference_length,polyA_length,sample,overlapping_gene_ids,overlapping_gene_names,n_overlapping_gene_ids,chrM_primary_class,new_class
37803,chrM,189,397,35516957-4bdb-45c1-b61e-072ef91efbb6,60,-,248.0,216,208,21,GTF7,7S,7S,1,complete_gene,fully_cleaved
37804,chrM,190,397,d3be8629-866a-474c-aea4-d722803b19c9,60,-,216.0,209,207,31,GTF7,7S,7S,1,complete_gene,fully_cleaved

CHECKING number of reads:
Starting mito-BAM filepath: /lustre/bio_running/GTEx_Long_Project/analysis/GTF7/GTF7.genome.chrM.reverse.bam

#####
Elaborating class: fully_cleaved

sample  new_class
GTF7    fully_cleaved    25
dtype: int64

(25, 16)
Number of reads for current class: 25
- output mitoBAM for current class: /lustre/bio_running/GTEx_Long_Project/analysis/GTF7/GTF7.genome.chrM.reverse.bam.fully_cleaved.bam
- output mitoBAM readslist for current class: /lustre/bio_running/GTEx_Long_Project/analysis/GTF7/GTF7.genome.chrM.reverse.bam.fully_cleaved.bam.readslist
- output mitoBAM depth file for current class: /lustre/bio_running/GTEx_Long_Project/analysis/GTF7/GTF7.genome.chrM.reverse.bam.fully_cleaved.bam.depth.txt
25
     25 16	chrM
16569 /lustre/bio_running/GTEx_Long_Project/analysis/GTF7/GTF7.genome.chrM.reverse.bam.fully_cleaved.bam.depth.txt

#####
Elaborating class: partially_cleaved_short

sample  new_class
GTF7    partially_cleaved_short    341
dtype: int64

(341, 16)
Number of reads for current class: 341
- output mitoBAM for current class: /lustre/bio_running/GTEx_Long_Project/analysis/GTF7/GTF7.genome.chrM.reverse.bam.partially_cleaved_short.bam
- output mitoBAM readslist for current class: /lustre/bio_running/GTEx_Long_Project/analysis/GTF7/GTF7.genome.chrM.reverse.bam.partially_cleaved_short.bam.readslist
- output mitoBAM depth file for current class: /lustre/bio_running/GTEx_Long_Project/analysis/GTF7/GTF7.genome.chrM.reverse.bam.partially_cleaved_short.bam.depth.txt
341
    341 16	chrM
16569 /lustre/bio_running/GTEx_Long_Project/analysis/GTF7/GTF7.genome.chrM.reverse.bam.partially_cleaved_short.bam.depth.txt

#####
Elaborating class: partially_cleaved_long

sample  new_class
GTF7    partially_cleaved_long    341
dtype: int64

(341, 16)
Number of reads for current class: 341
- output mitoBAM for current class: /lustre/bio_running/GTEx_Long_Project/analysis/GTF7/GTF7.genome.chrM.reverse.bam.partially_cleaved_long.bam
- output mitoBAM readslist for current class: /lustre/bio_running/GTEx_Long_Project/analysis/GTF7/GTF7.genome.chrM.reverse.bam.partially_cleaved_long.bam.readslist
- output mitoBAM depth file for current class: /lustre/bio_running/GTEx_Long_Project/analysis/GTF7/GTF7.genome.chrM.reverse.bam.partially_cleaved_long.bam.depth.txt
341
    341 16	chrM
16569 /lustre/bio_running/GTEx_Long_Project/analysis/GTF7/GTF7.genome.chrM.reverse.bam.partially_cleaved_long.bam.depth.txt


######################################################################################################
######################################################################################################
######################################################################################################
GTA3 Total Processed samples: 70/73
Shape of df-reads for current sample: (613, 16)
Unique number of reads: 613

,Chr,ChrStart,ChrEnd,read_id,MAPQ,strand,read_length,alignment_length,reference_length,polyA_length,sample,overlapping_gene_ids,overlapping_gene_names,n_overlapping_gene_ids,chrM_primary_class,new_class
2764,chrM,189,397,9f658a19-cca4-484f-80ef-f025e563c5c5,60,-,231.0,201,208,26,GTA3,7S,7S,1,complete_gene,fully_cleaved
2765,chrM,189,397,21480b40-d037-4f6a-820b-0c04b2c38055,60,-,225.0,208,208,41,GTA3,7S,7S,1,complete_gene,fully_cleaved

CHECKING number of reads:
Starting mito-BAM filepath: /lustre/bio_running/GTEx_Long_Project/analysis/GTA3/GTA3.genome.chrM.reverse.bam

#####
Elaborating class: fully_cleaved

sample  new_class
GTA3    fully_cleaved    40
dtype: int64

(40, 16)
Number of reads for current class: 40
- output mitoBAM for current class: /lustre/bio_running/GTEx_Long_Project/analysis/GTA3/GTA3.genome.chrM.reverse.bam.fully_cleaved.bam
- output mitoBAM readslist for current class: /lustre/bio_running/GTEx_Long_Project/analysis/GTA3/GTA3.genome.chrM.reverse.bam.fully_cleaved.bam.readslist
- output mitoBAM depth file for current class: /lustre/bio_running/GTEx_Long_Project/analysis/GTA3/GTA3.genome.chrM.reverse.bam.fully_cleaved.bam.depth.txt
40
     40 16	chrM
16569 /lustre/bio_running/GTEx_Long_Project/analysis/GTA3/GTA3.genome.chrM.reverse.bam.fully_cleaved.bam.depth.txt

#####
Elaborating class: partially_cleaved_short

sample  new_class
GTA3    partially_cleaved_short    332
dtype: int64

(332, 16)
Number of reads for current class: 332
- output mitoBAM for current class: /lustre/bio_running/GTEx_Long_Project/analysis/GTA3/GTA3.genome.chrM.reverse.bam.partially_cleaved_short.bam
- output mitoBAM readslist for current class: /lustre/bio_running/GTEx_Long_Project/analysis/GTA3/GTA3.genome.chrM.reverse.bam.partially_cleaved_short.bam.readslist
- output mitoBAM depth file for current class: /lustre/bio_running/GTEx_Long_Project/analysis/GTA3/GTA3.genome.chrM.reverse.bam.partially_cleaved_short.bam.depth.txt
332
    332 16	chrM
16569 /lustre/bio_running/GTEx_Long_Project/analysis/GTA3/GTA3.genome.chrM.reverse.bam.partially_cleaved_short.bam.depth.txt

#####
Elaborating class: partially_cleaved_long

sample  new_class
GTA3    partially_cleaved_long    241
dtype: int64

(241, 16)
Number of reads for current class: 241
- output mitoBAM for current class: /lustre/bio_running/GTEx_Long_Project/analysis/GTA3/GTA3.genome.chrM.reverse.bam.partially_cleaved_long.bam
- output mitoBAM readslist for current class: /lustre/bio_running/GTEx_Long_Project/analysis/GTA3/GTA3.genome.chrM.reverse.bam.partially_cleaved_long.bam.readslist
- output mitoBAM depth file for current class: /lustre/bio_running/GTEx_Long_Project/analysis/GTA3/GTA3.genome.chrM.reverse.bam.partially_cleaved_long.bam.depth.txt
241
    241 16	chrM
16569 /lustre/bio_running/GTEx_Long_Project/analysis/GTA3/GTA3.genome.chrM.reverse.bam.partially_cleaved_long.bam.depth.txt


######################################################################################################
######################################################################################################
######################################################################################################
GTB9 Total Processed samples: 71/73
Shape of df-reads for current sample: (307, 16)
Unique number of reads: 307

,Chr,ChrStart,ChrEnd,read_id,MAPQ,strand,read_length,alignment_length,reference_length,polyA_length,sample,overlapping_gene_ids,overlapping_gene_names,n_overlapping_gene_ids,chrM_primary_class,new_class
12010,chrM,189,397,728cf9ec-d149-41ad-8cb2-c614afde3d7e,60,-,231.0,209,208,20,GTB9,7S,7S,1,complete_gene,fully_cleaved
12011,chrM,189,397,63266440-7ab8-4e58-8ef1-8e1382ce8365,60,-,236.0,211,208,20,GTB9,7S,7S,1,complete_gene,fully_cleaved

CHECKING number of reads:
Starting mito-BAM filepath: /lustre/bio_running/GTEx_Long_Project/analysis/GTB9/GTB9.genome.chrM.reverse.bam

#####
Elaborating class: fully_cleaved

sample  new_class
GTB9    fully_cleaved    57
dtype: int64

(57, 16)
Number of reads for current class: 57
- output mitoBAM for current class: /lustre/bio_running/GTEx_Long_Project/analysis/GTB9/GTB9.genome.chrM.reverse.bam.fully_cleaved.bam
- output mitoBAM readslist for current class: /lustre/bio_running/GTEx_Long_Project/analysis/GTB9/GTB9.genome.chrM.reverse.bam.fully_cleaved.bam.readslist
- output mitoBAM depth file for current class: /lustre/bio_running/GTEx_Long_Project/analysis/GTB9/GTB9.genome.chrM.reverse.bam.fully_cleaved.bam.depth.txt
57
     57 16	chrM
16569 /lustre/bio_running/GTEx_Long_Project/analysis/GTB9/GTB9.genome.chrM.reverse.bam.fully_cleaved.bam.depth.txt

#####
Elaborating class: partially_cleaved_short

sample  new_class
GTB9    partially_cleaved_short    199
dtype: int64

(199, 16)
Number of reads for current class: 199
- output mitoBAM for current class: /lustre/bio_running/GTEx_Long_Project/analysis/GTB9/GTB9.genome.chrM.reverse.bam.partially_cleaved_short.bam
- output mitoBAM readslist for current class: /lustre/bio_running/GTEx_Long_Project/analysis/GTB9/GTB9.genome.chrM.reverse.bam.partially_cleaved_short.bam.readslist
- output mitoBAM depth file for current class: /lustre/bio_running/GTEx_Long_Project/analysis/GTB9/GTB9.genome.chrM.reverse.bam.partially_cleaved_short.bam.depth.txt
199
    199 16	chrM
16569 /lustre/bio_running/GTEx_Long_Project/analysis/GTB9/GTB9.genome.chrM.reverse.bam.partially_cleaved_short.bam.depth.txt

#####
Elaborating class: partially_cleaved_long

sample  new_class
GTB9    partially_cleaved_long    51
dtype: int64

(51, 16)
Number of reads for current class: 51
- output mitoBAM for current class: /lustre/bio_running/GTEx_Long_Project/analysis/GTB9/GTB9.genome.chrM.reverse.bam.partially_cleaved_long.bam
- output mitoBAM readslist for current class: /lustre/bio_running/GTEx_Long_Project/analysis/GTB9/GTB9.genome.chrM.reverse.bam.partially_cleaved_long.bam.readslist
- output mitoBAM depth file for current class: /lustre/bio_running/GTEx_Long_Project/analysis/GTB9/GTB9.genome.chrM.reverse.bam.partially_cleaved_long.bam.depth.txt
51
     51 16	chrM
16569 /lustre/bio_running/GTEx_Long_Project/analysis/GTB9/GTB9.genome.chrM.reverse.bam.partially_cleaved_long.bam.depth.txt


######################################################################################################
######################################################################################################
######################################################################################################
GTB1 Total Processed samples: 72/73
Shape of df-reads for current sample: (83, 16)
Unique number of reads: 83

,Chr,ChrStart,ChrEnd,read_id,MAPQ,strand,read_length,alignment_length,reference_length,polyA_length,sample,overlapping_gene_ids,overlapping_gene_names,n_overlapping_gene_ids,chrM_primary_class,new_class
7698,chrM,189,397,98015bf8-4747-43e1-b135-24271da4f74a,60,-,208.0,207,208,0,GTB1,7S,7S,1,complete_gene,fully_cleaved
7699,chrM,191,400,943ecc43-9399-45c7-96e1-48eeed61c39e,60,-,237.0,206,209,31,GTB1,7S,7S,1,complete_gene,fully_cleaved

CHECKING number of reads:
Starting mito-BAM filepath: /lustre/bio_running/GTEx_Long_Project/analysis/GTB1/GTB1.genome.chrM.reverse.bam

#####
Elaborating class: fully_cleaved

sample  new_class
GTB1    fully_cleaved    4
dtype: int64

(4, 16)
Number of reads for current class: 4
- output mitoBAM for current class: /lustre/bio_running/GTEx_Long_Project/analysis/GTB1/GTB1.genome.chrM.reverse.bam.fully_cleaved.bam
- output mitoBAM readslist for current class: /lustre/bio_running/GTEx_Long_Project/analysis/GTB1/GTB1.genome.chrM.reverse.bam.fully_cleaved.bam.readslist
- output mitoBAM depth file for current class: /lustre/bio_running/GTEx_Long_Project/analysis/GTB1/GTB1.genome.chrM.reverse.bam.fully_cleaved.bam.depth.txt
4
      4 16	chrM
16569 /lustre/bio_running/GTEx_Long_Project/analysis/GTB1/GTB1.genome.chrM.reverse.bam.fully_cleaved.bam.depth.txt

#####
Elaborating class: partially_cleaved_short

sample  new_class
GTB1    partially_cleaved_short    40
dtype: int64

(40, 16)
Number of reads for current class: 40
- output mitoBAM for current class: /lustre/bio_running/GTEx_Long_Project/analysis/GTB1/GTB1.genome.chrM.reverse.bam.partially_cleaved_short.bam
- output mitoBAM readslist for current class: /lustre/bio_running/GTEx_Long_Project/analysis/GTB1/GTB1.genome.chrM.reverse.bam.partially_cleaved_short.bam.readslist
- output mitoBAM depth file for current class: /lustre/bio_running/GTEx_Long_Project/analysis/GTB1/GTB1.genome.chrM.reverse.bam.partially_cleaved_short.bam.depth.txt
40
     40 16	chrM
16569 /lustre/bio_running/GTEx_Long_Project/analysis/GTB1/GTB1.genome.chrM.reverse.bam.partially_cleaved_short.bam.depth.txt

#####
Elaborating class: partially_cleaved_long

sample  new_class
GTB1    partially_cleaved_long    39
dtype: int64

(39, 16)
Number of reads for current class: 39
- output mitoBAM for current class: /lustre/bio_running/GTEx_Long_Project/analysis/GTB1/GTB1.genome.chrM.reverse.bam.partially_cleaved_long.bam
- output mitoBAM readslist for current class: /lustre/bio_running/GTEx_Long_Project/analysis/GTB1/GTB1.genome.chrM.reverse.bam.partially_cleaved_long.bam.readslist
- output mitoBAM depth file for current class: /lustre/bio_running/GTEx_Long_Project/analysis/GTB1/GTB1.genome.chrM.reverse.bam.partially_cleaved_long.bam.depth.txt
39
     39 16	chrM
16569 /lustre/bio_running/GTEx_Long_Project/analysis/GTB1/GTB1.genome.chrM.reverse.bam.partially_cleaved_long.bam.depth.txt



Computation Finised!
Total Processed samples: 73/73
Failed sample|new_class combinations: 0